### ISSUE TITLE
Can't compile project

### ISSUE THREAD

**Issue by yakubbaev** [QuickBlox/q-municate-services-ios#100]
1. `git clone https://github.com/QuickBlox/q-municate-services-ios.git` 
2. Fix framework search paths in `Quickblox.xcconfig` to `../Frameworks`
3. Replace old `Quickblox.framework` in `Frameworks` with latest one.
4. Add `libextobjc` library to `External/libextobjc`
5. Add `libextobjc` to `QMUsersService.xcodeproj`, `QMChatService.xcodeproj`, add corresponding `#imports` of `libextobjc` files.
6. Fix missing `#import <Bolts/Bolts.h>` in `QMAuthService`, `QMChatService`, and `QMContactListService` prefix headers.
   - Now each separate subproject of `QMServices` project compiles without errors.
7. Build `QMServices` target. 

**Expected result:**
It should build successfully after step 1.

**Actual result:**
Build fails on the line 10 of `QMServices.h` with error `'Quickblox/Quickblox.h'` file not found, however it s there.

**Comment by Raikerian** [comment]
Hi,

Does the compiler actually see Quickblox framework?

**Comment by yakubbaev** [comment]
Of course yes, otherwise after step 6 I wouldn't be able to compile any subprojects as they use Quickblox too.
Have you tried to reproduce step by step?

**Comment by Raikerian** [comment]
Have you configured framework search paths for both all QMServices .xcodeproj ?

**Comment by yakubbaev** [comment]
Yes.

**Comment by Raikerian** [comment]
Please show your Podfile content.

**Comment by yakubbaev** [comment]
Podfile? Here I'm trying to compile your q-municate-services-ios and it doesn't seem to use pods for it's own dependencies.

**Comment by Raikerian** [comment]
We will investigate this problem about manual installation. The fastest way for you to make it work for now is to use our development spec on Cocoapods.
For this you need only to configure podfile to look into a specific github branch or even specific commit.
Examples:

```
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :commit => 'ab56ac143bb770e76409a027bfb38de582d728aa'
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'master'
```

This way Quickblox framework will not be downloaded as dependency and you will need to manually add it to your own project.

**Comment by yakubbaev** [comment]
This way after `pod install` and putting `Quickblox.framework` to `External/` folder in project root, it fails with errors:
![Image of error](http://i.imgur.com/khNKbs5.png)

If drag & drop Quickblox.framework into `Pods` project it builds, but as you know Pods project is regenerated on each `pod install`.

**Comment by Raikerian** [comment]
Have you tried deleting Podfile.lock, Pods folder and .xworkspace file before pod install?

**Comment by yakubbaev** [comment]
Can't delete Podfile.lock as some pods has no version declaration and are leading to breaking updates.
Delete Pods folder and .xcworkspace file and run pod install end up with the same errors.

**Comment by yakubbaev** [comment]
I think here is issue with Quickblox.framework as warning states `is not a dylib`. I've copied it from Frameworks folder of the same commit as my Podfile specifies:

```
platform :ios, '8.0'
use_frameworks!

# ... Other pods
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'development', :commit => '533877a6ea527f09ee8bf5b339e6ed00516a78da'
```

**Comment by yakubbaev** [comment]
Fixed by hacking your development podspec and adding <code>'OTHER_LDFLAGS' => "-framework 'Quickblox'"</code> to <code>.xcconfig</code>

**Comment by Raikerian** [comment]
Glad to hear you fixed it for yourself, we will investigate this issue and fix manual installation as soon as possible.

**Comment by yakubbaev** [comment]
Story continues... 
After `#import <QMServices.h>` in bridging header it shows error "'QMServices.h' not found". As I have `use_frameworks!` in my Podfile, cocoapods is building `QMServicesDevelopment` as a framework too. So I tried to `#import <QMServicesDevelopment/QMServices.h>`. Now it fails with "Could not build module 'QMServicesDevelopment'" and bunch of `Expected a type` errors:
![Image of error](http://i.imgur.com/ju6EXwT.png)

**Comment by Raikerian** [comment]
@yakubbaev,

We have updated QMServices to 0.3.5 and it is available in master branch now. We have also updated out manual installation guide, please check it out. Try to manual install it using submodule.

**Comment by yakubbaev** [comment]
Documentation sucks. Still.
![Image of doc](http://i.imgur.com/F16NJPy.png)

**Comment by yakubbaev** [comment]
Manual installation finally fixed by #106

**Comment by Raikerian** [comment]
Thank you for contributing to our project! :)
Merged.

**Comment by hadwanihardik** [comment]
getting below issue on QMAssetLoader.m file

![screen shot 2018-02-08 at 9 28 52 am](https://user-images.githubusercontent.com/5634693/35954994-cc705100-0cb2-11e8-96e7-e7131e004dd2.png)

**Comment by Raikerian** [comment]
@hadwanihardik please create a separate own issue and describe your problem with as much details as possible.
