### ISSUE TITLE
linker command failed with exit code 1

### ISSUE THREAD

**Issue by rathodbhavikkqc** [QuickBlox/q-municate-services-ios#104]
I am using xcode 7.2 with,
QuickBlox 2.6.2
QMServices 0.3.4
QMChatViewController 0.3.3
Quickblox-WebRTC 2.1.1 libraries

and error is following
ld: library not found for -lQMChatViewController
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Raikerian** [comment]
Which way are you installing QMChatViewController?
If Cocoapods, try deleting Podfile.lock file, Pods folder and .xcworkspace file and run pod install again.

**Comment by rathodbhavikkqc** [comment]
Ok i removed all the files and folders which you have mentioned,  and now pods are installing.

**Comment by rathodbhavikkqc** [comment]
Same error occures after installing all libraries again

**Comment by rathodbhavikkqc** [comment]
@Raikerian if you need full error for reference then let me know, i will post here

**Comment by Raikerian** [comment]
@rathod24 yeah, full error will be helpful :)

**Comment by rathodbhavikkqc** [comment]
Ah.. sorry it was silly mistake , i have forgotten to set Build Active Architectures to YES, now it is working
