### ISSUE TITLE
Is it possible to cache image attachment before upload it?

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#107]
I would like to achieve a situation when user upload his image without showing him any status(In other words I would like to store the image as soon as user send it without waiting for confirmation) .(so all the work is done in the background thread).In your case :

```
 - (void)uploadAndSendAttachmentMessage:(QBChatMessage *)message toDialog:(QBChatDialog *)dialog withChatService:(QMChatService *)chatService withAttachedImage:(UIImage *)image completion:(QBChatCompletionBlock)completion { 
   [self changeMessageAttachmentStatus:QMMessageAttachmentStatusLoading forMessage:message];

    NSData *imageData = UIImagePNGRepresentation(image);

    [QBRequest TUploadFile:imageData fileName:@"attachment" contentType:@"image/png" isPublic:NO successBlock:^(QBResponse *response, QBCBlob *blob) {

        QBChatAttachment *attachment = [QBChatAttachment new];
        attachment.type = @"image";
        attachment.ID = [@(blob.ID) stringValue];
        attachment.url = [blob privateUrl];

        message.attachments = @[attachment];
        message.text = @"Attachment image";

        [self saveImageData:imageData chatAttachment:attachment error:nil];
        [self.attachmentsStorage setObject:image forKey:attachment.ID];

        [self changeMessageAttachmentStatus:QMMessageAttachmentStatusLoaded forMessage:message];

        [chatService sendMessage:message type:QMMessageTypeText toDialog:dialog saveToHistory:YES saveToStorage:YES completion:completion];

    } statusBlock:^(QBRequest *request, QBRequestStatus *status) {

    } errorBlock:^(QBResponse *response) {

        [self changeMessageAttachmentStatus:QMMessageAttachmentStatusNotLoaded forMessage:message];

        if (completion) completion(response.error.error);
    }];
}
```

So you cache it after you get a response (So for instance if we look at wats up the user can see the image right away).
Another thing that it can be nice to show a user an error near his image which will indicate on error uploading...
currently if the Image wasn't uploaded I need to delete it (but unfortunately I cannot find a way to do it with 0.3.3 version ).
The only option that i found is :
`- (void)deleteMessages:(NSArray *)messages inContext:(NSManagedObjectContext *)context ;`
Which I am not sure how to use...

Appreciate your assistance.

**Comment by Raikerian** [comment]
Hi,

Uploading messages without progress hud is available in our latest sample-chat. Also, latest QMServices has methods to locally delete messages.

If you want to cache image before upload just move 

```
[self saveImageData:imageData chatAttachment:attachment error:nil];
[self.attachmentsStorage setObject:image forKey:attachment.ID];
```

out of block and you are good to go.

**Comment by mikeRozen** [comment]
Just few things to note.
Unfortunately we cant move to last version (currently).

```
- `Bolts (= 1.3.0)` required by `Podfile.lock`
- `Bolts (~> 1.1)` required by `FBSDKCoreKit (4.5.1)`
- `Bolts (= 1.5.0)` required by `QMServices (0.3.5)`

```

You change your Bolts (in the new version) to 1.5.0 which demands a new FacebookCoreKit.
(FacebookCoreKit starting from version 4.5.1 demand login only via Web which we try to avoid).
Please notice that:

```
[self saveImageData:imageData chatAttachment:attachment error:nil];
[self.attachmentsStorage setObject:image forKey:attachment.ID];
```

Will demand a data like `attachment.ID` which we get ONLY after we receive your response from the server.(please look at your implamintation  of 
`- (void)uploadAndSendAttachmentMessage:(QBChatMessage *)message toDialog:(QBChatDialog *)dialog withChatService:(QMChatService *)chatService withAttachedImage:(UIImage *)image completion:(QBChatCompletionBlock)completion ;` pasted in the beginning of the thread.
While this implementation waiting for your server response to store the attachment, sending text message store the message and update it after getting response(Which I think is proper way for to do in both cases.)
-Another thing that I notice is , you convert the data/image to PNG representation (even though I would like to send it in JPEG format to save time and size).It can be nice if we could control the data type.
Thanks for your time.

**Comment by Raikerian** [comment]
You can change image representation by your needs for now, we will update this method to make it more customisable in the near future.
Also, you can show image whenever you want, cause you know about it before sending, and cache it only when it done upload.
For more information on uploading without progress hud check out our latest samples.

According Bolts dependency, if you want to use 1.3.0, install QMServices using our manual installation guide (so, no cocoapods). Then you will be able to run it with your own version of framework.

**Comment by Raikerian** [comment]
We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.
