### ISSUE TITLE
File not found in version 0.3.5

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#108]
After upgrade to version 0.3.5 we can not run project.
Maybe framework is missing file **ChatDelegates.h**

![screen shot 2016-01-29 at 4 21 11 pm](https://cloud.githubusercontent.com/assets/1511264/12671753/601979ce-c6a4-11e5-9306-46f0cf3d75ae.png)

**Comment by Raikerian** [comment]
Hi,

According to the screenshot you have undeclared identifier which is not an identifier of QMServices.

**Comment by tranngoclinh88** [comment]
These strings are defined in ChatDelegates.h
I've checked out and fresh install from pod.

Does not happen if I update from old project.

**Comment by tranngoclinh88** [comment]
I tried import "ChatDelegates.h" but it displayed file not found.

**Comment by iSevenDays** [comment]
Hi!

Is this issue about QMServices? In QMServices we don't have QMSoundManager

Maybe you are talking about Q-municate?

**Comment by tranngoclinh88** [comment]
I copy some classes from Q-municate to my application.
Before I update, it can run. After update, it can not. I've tried using version 0.3.4 and it's still error.

**Comment by Raikerian** [comment]
Add this to your constants file:

``` objectivec
static NSString *const kStopVideoChatCallStatus_OpponentDidNotAnswer = @"kStopVideoChatCallStatus_OpponentDidNotAnswer";
static NSString *const kStopVideoChatCallStatus_Manually = @"kStopVideoChatCallStatus_Manually";
static NSString *const kStopVideoChatCallStatus_Cancel = @"kStopVideoChatCallStatus_Cancel";
static NSString *const kStopVideoChatCallStatus_BadConnection = @"kStopVideoChatCallStatus_BadConnection";
```

These identifiers were removed from the latest Quickblox iOS SDK.

**Comment by tranngoclinh88** [comment]
Thank @Raikerian
