### ISSUE TITLE
Can you provide a demo using QMServices at sub-module?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#109]
Currently, QMServices only allow upload/download image for attachment message.
I want to upload/download some type of file that is not image, so I write new functions. I had tried integrating QMServices via sub-module follow your guide but not success.

Can you provide an example for this guide, please?

**Comment by Raikerian** [comment]
Hi,

You can use development pods for this, just clone our repository, and add this to your podfile:

```
pod 'QMServicesDevelopment', :path => '__path_to_cloned_repository__'
```

Or you can install development pods without repository cloning:

```
pod 'QMServicesDevelopment', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'master'
```

**Comment by tranngoclinh88** [comment]
Thank @Raikerian
