### ISSUE TITLE
!] The 'Pods-CSocial' target has transitive dependencies that include static binaries: (/Users/gayathri_b/Desktop/CSocialPrototype/csocial/Pods/QuickBlox/Quickblox.framework)

### ISSUE THREAD

**Issue by gthrb22** [QuickBlox/q-municate-services-ios#118]
Hi ,
In my swift project 
Im installing QMServices and QMChatViewController using following commands in pod file pod 'QMServices', '~> 0.3'
pod 'QMChatViewController', '~> 0.3'
but i get the following error
!] The 'Pods' target has transitive dependencies that include static binaries: (/Users/gayathri_b/Desktop/Prototype/kdsj/Pods/QuickBlox/Quickblox.framework)

Alternatively i used git link to for the above but dependencies are not getting installed even if i install if the branch is master

Need help kindly give suggestions
Note:I dont face the problem if i integrate the same in objective c project

**Comment by iSevenDays** [comment]
Hi gthrb22,

Problem can be with !use_frameworks

We do not support this, please check

Thanks!

**Comment by iSevenDays** [comment]
https://github.com/QuickBlox/q-municate-services-ios/issues/119
