### ISSUE TITLE
Adding Production Certificate.

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#120]
When I try to add a production certificate in the DashBoard I receive the following error.(I alredy have a development profile which works fine).

```
Certificate errors:
2016-02-10 18:10:41 UTC: Connection reset by APNS: OpenSSL::SSL::SSLError, SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A
```

Can you please assist me with that?(Can you please also clarify how you distinguish between the production and the development to trigger the correct certificate. Should I add something to my code. )

**Comment by iSevenDays** [comment]
Hi mikeRozen,

Could you please specify the following
1. What project
2. Steps to reproduce
3. Logs

This will help us resolve your issue

Thanks!

**Comment by mikeRozen** [comment]
Hi iSevenDays,
In QuickBlox dashboard -> push notification -> Settings.
1. Project name: Dogiz
2.I try to add production certificate to already existing development certificate (APNS).
3.View error log blue button reproduce this log. (The state of the certificate : PERMANENTLY DISABLED DUE TO ERROR COUNT )
- I tried to remove and add it again , didn't help.
- maybe to remove all of them and add them again will help..... but I a little bit afraid to spoil already working development Certificate)

**Comment by mikeRozen** [comment]
Hi iSevenDays,
Do you have some progress regarding that issue?
Thanks.

**Comment by iSevenDays** [comment]
Hi mikeRozen,

Please follow the guide http://quickblox.com/developers/SimpleSample-messages_users-ios#Creating_APNS_certificates

If it is possible, please re-upload certificates.

> 2016-02-10 18:10:41 UTC: Connection reset by APNS: OpenSSL::SSL::SSLError, SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A

It means that Apple APNS declines your certificate, please re-create it.

**Comment by Raikerian** [comment]
Hi,

were you able to fix this issue?

**Comment by mikeRozen** [comment]
Hi ,
Will try it tomorrow.
Thanks.

**Comment by mikeRozen** [comment]
Hi iSevenDays,
I believe it was my mistake in the way I create the p.12. Because our sever has the same problem.So I recreated the certificates and it start working.
Thanks for help.

**Comment by Raikerian** [comment]
Good to see that you have fixed it.
If you are still having any troubles please let us know by creating a separate issue :)
