### ISSUE TITLE
File not found issue

### ISSUE THREAD

**Issue by gthrb22** [QuickBlox/q-municate-services-ios#121]
While doing manual installation i face bolts file not found issue attached screenshot.
![screen shot 2016-02-11 at 5 04 59 pm](https://cloud.githubusercontent.com/assets/16421915/12975497/3a2b5974-d0e2-11e5-93fd-d87ec3bd4351.png)

**Comment by iSevenDays** [comment]
Hi gthrb22,

By default QM services include Frameworks with Bolts.framework and Quickblox.framework

**Comment by gthrb22** [comment]
Yes bolts framework is present in the submodule but am adding the submodule to a swift project with libQMServices as target dependencies and when i compile the project i get bolts file not  found error but it exits in "Frameworks" path.

**Comment by iSevenDays** [comment]
Please ensure that you have folder with Bolts.framework in your framework_search_path in Xcode build settings

Also you can attach your test project and I will try to help you

**Comment by gthrb22** [comment]
Yes it exists in Vendor/QMServices/Frameworks and the same i have given in framework search path

**Comment by iSevenDays** [comment]
It can be the only one problem — search path
Also please ensure that you have correct header search path

**Comment by iSevenDays** [comment]
We haven't heard back from you in a few days, so we are marking this post as Closed for tracking purposes. If you're still experiencing this issue, please provide us with additional information.
