### ISSUE TITLE
QB Enterprise Licencsing

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/q-municate-services-ios#124]
We are using QB Enterprise Medium Instance. Just wondering if we can use this library without sharing our code. In other words, Q-munity license don't apply to us, correct?

Thanks.

**Comment by soulfly** [comment]
that's correct. You can use this library without sharing your code.

**Comment by iSevenDays** [comment]
Hi itsaboutcode,

**BSD** for QMServices, QMChatViewController, Samples and other projects

**Apache** for Q-municate

**Comment by itsaboutcode** [comment]
Thanks. Can you mention exact version of BSD and Apahce?

Thanks.
