### ISSUE TITLE
Can not merge QMService to my clone git.

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#127]
I saw QMService had updated to version 0.3.6 and I want to merge your code with mine.
But I got an issue:

```
git-lfs smudge 'Frameworks/Quickblox.framework/Versions/A/Quickblox': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Quickblox.framework/Versions/A/Quickblox: smudge filter lfs failed
```

Please help!

**Comment by iSevenDays** [comment]
Hi!
You don't have git-lfs installed.

Please follow installation rules here: https://git-lfs.github.com

Also please don't forget to delete Podfile.lock, Pods folder and .xcworkspace file before next pod install.

Thanks!

**Comment by tranngoclinh88** [comment]
I tried but always fail. Please help!

```
Linh-Trans-MacBook-Pro:~ TranNgocLinh88$ brew install git-lfs
==> Downloading https://homebrew.bintray.com/bottles/git-lfs-1.0.2.el_capitan.bo
######################################################################## 100.0%
==> Pouring git-lfs-1.0.2.el_capitan.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/git-lfs
Target /usr/local/bin/git-lfs
already exists. You may want to remove it:
  rm '/usr/local/bin/git-lfs'

To force the link and overwrite all conflicting files:
  brew link --overwrite git-lfs

To list all files that would be deleted:
  brew link --overwrite --dry-run git-lfs

Possible conflicting files are:
/usr/local/bin/git-lfs
==> Summary
🍺  /usr/local/Cellar/git-lfs/1.0.2: 5 files, 9.6M
```

**Comment by iSevenDays** [comment]
Please do the following

"You may want to remove it:
  rm '/usr/local/bin/git-lfs'"

**Comment by tranngoclinh88** [comment]
Now I have this issue:

Using Tower.

```
fatal: could not read Username for 'https://github.com': Device not configured
```

**Comment by iSevenDays** [comment]
This error is not related to Quickblox QMServices, please fix your github settings and then try again

For example, you can try
https://github.com/kemayo/sublime-text-git/issues/176
http://stackoverflow.com/questions/22147574/fatal-could-not-read-username-for-https-github-com-no-such-file-or-directo
https://github.com/OHI-Science/ohicore/issues/104
http://stackoverflow.com/questions/20871549/error-when-push-commits-with-github-fatal-could-not-read-username

**Comment by tranngoclinh88** [comment]
I can not commit to git. This is my error.

```
git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree commit -q -F /var/folders/y8/540lbgjx4g14nrcc91qm5st40000gn/T/SourceTreeTemp.as40yL 


git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags --set-upstream UAS refs/heads/development_UAS:refs/heads/development_UAS 
Pushing to https://github.com/unityappstudio/q-municate-services-ios
Frameworks/Quickblox.framework/Versions/A/Quickblox is an LFS pointer to 587687c7b20b58ce4f6ed3fd0048f04a1181d20c1638d8ed84665511c52518fe, which does not exist in .git/lfs/objects.

Run 'git lfs fsck' to verify Git LFS objects.
error: failed to push some refs to 'https://github.com/unityappstudio/q-municate-services-ios'
Completed with errors, see above
```

**Comment by Raikerian** [comment]
We are currently investigating this issue and will post update soon.

**Comment by Raikerian** [comment]
Thank you for reporting the issue, we have fixed it.
Try to clone it again, everything should be fine.

Please verify this.

**Comment by tranngoclinh88** [comment]
I can check out but can not install via cocoapods.

**Comment by iSevenDays** [comment]
Hi tranngoclinh88,

Do you still have the same error log?

Please check that

**Comment by tranngoclinh88** [comment]
Now. I can merge code but still can not install.

**Comment by iSevenDays** [comment]
Please provide us logs

**Comment by tranngoclinh88** [comment]
Here is my log.

```
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /Applications/CocoaPods.app/Contents/Resources/bundle/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/y8/540lbgjx4g14nrcc91qm5st40000gn/T/d20160217-82997-s7d1bj --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/y8/540lbgjx4g14nrcc91qm5st40000gn/T/d20160217-82997-s7d1bj'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

I installed git-lfs.

```
Linh-Trans-MacBook-Pro:~ TranNgocLinh88$ git-lfs install
Git LFS initialized.
Linh-Trans-MacBook-Pro:~ TranNgocLinh88$
```

**Comment by iSevenDays** [comment]
Hi

Please see this https://github.com/QuickBlox/q-municate-services-ios/issues/133#issuecomment-185756194

**Comment by tranngoclinh88** [comment]
@iSevenDays 
I got an error while install QMServices from my clone git.

```
Pre-downloading: `QMServices` from `https://github.com/unityappstudio/q-municate-services-ios.git`
Unable to find a specification for 'QMServices'.
```

Here is my pod:

```
pod 'QMServices', :git =>'https://github.com/unityappstudio/q-municate-services-ios.git'
```

**Comment by Raikerian** [comment]
Please try to use
`pod 'QMServices', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'development'`

**Comment by tranngoclinh88** [comment]
@Raikerian 
I want to use my clone git because I want to use some functions that I added.

**Comment by Raikerian** [comment]
Try to clone it using SSH:
git@github.com:tranngoclinh88/q-municate-services-ios.git

**Comment by tranngoclinh88** [comment]
@Raikerian 
Using SSH is hard to config. Do you know why I can not use _https_?

**Comment by Raikerian** [comment]
Just double checked your error, seems like problem is occured due to git lfs is being enabled on your repository. Can you check it and turn it off?

**Comment by tranngoclinh88** [comment]
How can I do that @Raikerian ?

**Comment by Raikerian** [comment]
Apply this patch to your forked repository: https://github.com/QuickBlox/q-municate-services-ios/commit/44d1b8940d2a3c123e42606fa471623034847dd2

**Comment by tranngoclinh88** [comment]
Thank @Raikerian!

**Comment by tranngoclinh88** [comment]
@Raikerian 
I tried to delete forked git, re-fork QMServices then config Pod file.
Still get the same error.

```
Analyzing dependencies
Pre-downloading: `QMServices` from `https://github.com/unityappstudio/q-municate-services-ios.git`
[!] Unable to find a specification for 'QMServices'.
```

My pod file

```
pod 'QMServices', :git =>'https://github.com/unityappstudio/q-municate-services-ios.git'
```

**Comment by Raikerian** [comment]
You still have this in your forked repository: https://github.com/tranngoclinh88/q-municate-services-ios/blob/master/.gitattributes

**Comment by tranngoclinh88** [comment]
Did you check https://github.com/unityappstudio/q-municate-services-ios.git?
This git does not have that file. Still can not install.

**Comment by Raikerian** [comment]
My bad, try to modify podfile with this:

```
pod 'QMServicesDevelopment', :git =>'https://github.com/unityappstudio/q-municate-services-ios.git'
```

**Comment by tranngoclinh88** [comment]
Thank @Raikerian for your supporting.
I can install now. :)
