### ISSUE TITLE
canot install QMServices

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#131]
hi 
I'm trying to integrate QuickBlox with my project but when I'm trying to Installing QMServices I get the next result: 

hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Downloading Frameworks/Bolts.framework/Versions/A/Bolts (940.64 KB)
Error downloading object: Frameworks/Bolts.framework/Versions/A/Bolts (238480d343f8e10def84cf56218ab6c54868dafc0e2c803ecdf989b1a2f2efb8)

Errors logged to /private/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg/.git/lfs/objects/logs/20160216T140807.145508476.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by Raikerian** [comment]
Hi,

Please follow this issue in order to fix it: https://github.com/github/git-lfs/issues/911

**Comment by RivkiGlick** [comment]
i have tried to do these lines but this is what i get back:

hodayas-iMac:TryChat1 hodayaohana$ git lfs install --skip-smudge
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
    log

**Comment by Raikerian** [comment]
We are currently investigating this issue and will post update soon.

**Comment by Raikerian** [comment]
Thank you for reporting the issue, we have fixed it.
Try to clone it again, everything should be fine.

If you are still having any other questions feel free to create separate issue :)

**Comment by RivkiGlick** [comment]
I have tried to clone it again and I'm still get the same error:

hodayas-iMac:TryChat1 hodayaohana$  pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160217-31555-oga6gt --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160217-31555-oga6gt'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

hodayas-iMac:TryChat1 hodayaohana$ git lfs install --skip-smudge
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
    log

**Comment by RivkiGlick** [comment]
I have traied to clone again but this is what i get back :+1: 

hodayas-iMac:TryChat1 hodayaohana$  pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160217-31555-oga6gt --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160217-31555-oga6gt'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'


hodayas-iMac:TryChat1 hodayaohana$ git lfs install --skip-smudge
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log
