### ISSUE TITLE
canot install QMServices

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#133]
I have tried to clone it again and I'm still get the same error:

hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: gem install cocoapods --pre
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160217-31555-oga6gt --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160217-31555-oga6gt'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

hodayas-iMac:TryChat1 hodayaohana$ git lfs install --skip-smudge
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
log

**Comment by iSevenDays** [comment]
Hi RivkiGlick,

Please post your steps to reproduce the issue.

Thanks!

**Comment by RivkiGlick** [comment]
hi 
I'm trying to integrate QuickBlox with my project but when I'm trying to Installing QMServices I get the next result:

hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: gem install cocoapods --pre
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b

Downloading Frameworks/Bolts.framework/Versions/A/Bolts (940.64 KB)
Error downloading object: Frameworks/Bolts.framework/Versions/A/Bolts (238480d343f8e10def84cf56218ab6c54868dafc0e2c803ecdf989b1a2f2efb8)

Errors logged to /private/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg/.git/lfs/objects/logs/20160216T140807.145508476.log
Use git lfs logs last to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by iSevenDays** [comment]
Please post your podspec

**Comment by RivkiGlick** [comment]
# Uncomment this line to define a global platform for your project

# platform :ios, '8.0'

# Uncomment this line if you're using Swift

# use_frameworks!

target 'TryChat1' do

```
pod 'QMServices'
```

end

target 'TryChat1Tests' do

end

**Comment by iSevenDays** [comment]
Please remove use_frameworks! and try again from scratch

Thanks!

**Comment by RivkiGlick** [comment]
I tried again and the same message:

hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160218-22077-199sxqp --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160218-22077-199sxqp'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by iSevenDays** [comment]
Thanks! I was able to reproduce the issue. I need some time to fix it and I will let you know when I'm done.

**Comment by iSevenDays** [comment]
I had the issue when I was using ruby 2.3, do you use system ruby 2.0?

Please execute ruby --version and post result

**Comment by RivkiGlick** [comment]
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by iSevenDays** [comment]
I was able to fix that by committing all the changes I had.

Please commit your changes and then do pod install

Thanks!

**Comment by RivkiGlick** [comment]
how I do commit? for what?

**Comment by iSevenDays** [comment]
By default Xcode initializes empty git repo in your folder.

For example
1. cd your_project_folder
2. git init .
step 2 may not be required
3. git add .
4. git commit -m "test commit message"
5. pod install

**Comment by RivkiGlick** [comment]
i have tried but again i get the same messege:

hodayas-iMac:TryChat1 hodayaohana$ git init 
Reinitialized existing Git repository in /Users/hodayaohana/Desktop/TryChat1/.git/
hodayas-iMac:TryChat1 hodayaohana$ git add
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
hodayas-iMac:TryChat1 hodayaohana$ git add .
hodayas-iMac:TryChat1 hodayaohana$ git commit -m "test commit message"
[master 90b1978] test commit message
 10 files changed, 267 insertions(+), 4 deletions(-)
 create mode 100644 Podfile.lock
 create mode 100644 Pods/Manifest.lock
 create mode 100644 Pods/Pods.xcodeproj/project.pbxproj
 create mode 100644 Pods/Pods.xcodeproj/xcuserdata/hodayaohana.xcuserdatad/xcschemes/xcschememanagement.plist
 rewrite TryChat1.xcodeproj/project.xcworkspace/xcuserdata/hodayaohana.xcuserdatad/UserInterfaceState.xcuserstate (79%)
 create mode 100644 TryChat1.xcworkspace/contents.xcworkspacedata
 create mode 100644 TryChat1.xcworkspace/xcuserdata/hodayaohana.xcuserdatad/UserInterfaceState.xcuserstate
 create mode 160000 Vendor/QMServices
hodayas-iMac:TryChat1 hodayaohana$ pod install

Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160218-23518-1q388pe --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160218-23518-1q388pe'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by iSevenDays** [comment]
You forgot to add "." to git init command

`git init . `

**Comment by RivkiGlick** [comment]
I get the same messege

 hodayas-iMac:TryChat1 hodayaohana$ git init .
Reinitialized existing Git repository in /Users/hodayaohana/Desktop/TryChat1/.git/
hodayas-iMac:TryChat1 hodayaohana$ git add .
hodayas-iMac:TryChat1 hodayaohana$ git commit -m "test commit message"
[master 0ad5bd8] test commit message
 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite TryChat1.xcworkspace/xcuserdata/hodayaohana.xcuserdatad/UserInterfaceState.xcuserstate (84%)
hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160218-24623-10yeoh0 --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160218-24623-10yeoh0'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by iSevenDays** [comment]
Thanks for reporting!

We have fixed this in development branch

Please try to use
`pod 'QMServices', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'development'`

We will merge this to master branch soon.

Thanks!

**Comment by RivkiGlick** [comment]
than you for the help but I tried to do what you told me but i get the next issue:

hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `QMServices` from `git@github.com:QuickBlox/q-municate-services-ios.git`, branch `development`

[!] Error installing QMServices
[!] /usr/bin/git clone git@github.com:QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160221-3240-asuorl --single-branch --depth 1 --branch development

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160221-3240-asuorl'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

my podfile lookes like this:

# Uncomment this line to define a global platform for your project

# platform :ios, '8.0'

# Uncomment this line if you're using Swift

target 'TryChat1' do

   pod 'QMServices', :git => 'git@github.com:QuickBlox/q-municate-services-ios.git', :branch => 'development'

end

target 'TryChat1Tests' do

end

**Comment by Raikerian** [comment]
> Permission denied (publickey).

Looks like you haven't set up neither github credentials nor ssh key. Please check it out: https://help.github.com/articles/set-up-git/

**Comment by RivkiGlick** [comment]
this is what i get back:

hodayas-iMac:TryChat1 hodayaohana$ ssh-keygen -t rsa -b 4096 -C "rivki@shantiapp.com"
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/hodayaohana/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /Users/hodayaohana/.ssh/id_rsa.
Your public key has been saved in /Users/hodayaohana/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:AOnbfPojmyp3bhT283qPA5DV0v9gayOkMlOi1AlNV2I rivki@shantiapp.com
The key's randomart image is:
+---[RSA 4096]----+
|    .+. E+.      |
|    o..oo.o      |
|   . o.+ . .     |
|    o O.. . +    |
|   . \* *So . +   |
|    o B \* . + .  |
|     . \* + o .   |
|  . . =.. +.     |
|   o.=++o+.o.    |
+----[SHA256]-----+
hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `QMServices` from `git@github.com:QuickBlox/q-municate-services-ios.git`, branch `development`

[!] Error installing QMServices
[!] /usr/bin/git clone git@github.com:QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160222-37500-16sqnt5 --single-branch --depth 1 --branch development

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160222-37500-16sqnt5'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

---

**Comment by Raikerian** [comment]
This can be helpful: https://help.github.com/articles/error-permission-denied-publickey/

You can also change your connection type from SSH to https, for example

> git@github.com:QuickBlox/q-municate-services-ios.git

to

> https://github.com/QuickBlox/q-municate-services-ios.git

**Comment by RivkiGlick** [comment]
thank you it worket

**Comment by Raikerian** [comment]
No problem, if you are still having any other troubles, feel free to create separate issue :)
