### ISSUE TITLE
 'Quickblox/Quickblox.h' file not found

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#137]
I get this message 'Quickblox/Quickblox.h' file not found in the file QMServicesDevelopment-prefix.pch after adding it in the podfile:  pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'
any help?

**Comment by Raikerian** [comment]
Hi,

Seems like you haven't installed Quickblox iOS SDK.
Use pod 'QuickBlox', or install QMServices using public cocoapods: pod 'QMServices' and it will install all dependencies including our SDK.

**Comment by RivkiGlick** [comment]
this is how my podfile lookes: 

# Uncomment this line to define a global platform for your project

# platform :ios, '8.0'

# Uncomment this line if you're using Swift

# use_frameworks!

target 'chat2' do

pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'

pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'

pod 'QMCVDevelopment' , :git => 'https://github.com/QuickBlox/QMChatViewController-ios', :branch => 'development'

end

target 'chat2Tests' do

end

**Comment by Raikerian** [comment]
Add this to your podfile:
`
pod 'QuickBlox'
`

**Comment by RivkiGlick** [comment]
I added it but now he didn't recognize the files of quickblox i get the next messege:
 Use of undeclared type 'QBChatDialog'

**Comment by RivkiGlick** [comment]
what can I do?

**Comment by Raikerian** [comment]
Open your project build settings, navigate to bridging header option and add this:

`
${PROJECT_NAME}/chat2-bridging-Header.h
`

Then change 

`
@import Quickblox;
`

for

`
#import <Quickblox/Quickblox.h>
`

Let me know result.

**Comment by RivkiGlick** [comment]
thank you so much it really did the job

**Comment by Raikerian** [comment]
Good to see that you have fixed it.
If you are still having any troubles please let us know by creating a separate issue :)

P.S. We will update our Swift integration guide soon.

**Comment by AbhayPansora** [comment]
hello raikerian sir,
Please help me, i am using Quickblox and also install QMService and QMChatViewContoller but some problem are generating in  QMChatViewContoller so please help me how install it.
Thank you.

**Comment by Raikerian** [comment]
@AbhayPansora please create a separate issue. More detailed problem describing would be good.

**Comment by bestquality777** [comment]
Thanks,
I have too a same issue but i fixed using this way.
