### ISSUE TITLE
Dosen't recognize the filles of QuickBlox

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#138]
Hi I am trying to add quickblox to my project
I add it with coocapods but when I'm trying to use the classes of quickBlox it dosnt recognize the class:
 Use of undeclared type 'QBChatDialog'
mu podfile lookes like this: pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'

pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'

pod 'QMCVDevelopment' , :git => 'https://github.com/QuickBlox/QMChatViewController-ios', :branch => 'development'
pod 'QuickBlox'

**Comment by Raikerian** [comment]
Hi,

Try to modify this podfile by deleting QMServicesDevelopment, QMCVDevelopment and QuickBlox. Then just add this:

```
pod 'QMServices'
pod 'QMChatViewController'
```

**Comment by RivkiGlick** [comment]
I changed it but still  I get this message: Use of undeclared type 'QBChatDialog'

**Comment by Raikerian** [comment]
Can you attach your test project?

**Comment by RivkiGlick** [comment]
its 32.2 MB its too big

**Comment by Raikerian** [comment]
Have you added this line to your pch file?

`
#import <Quickblox/Quickblox.h>
`

Or if you are using Swift (to the bridging header):

`
@import Quickblox;
`

**Comment by RivkiGlick** [comment]
this is how it looks:
#ifndef chat2_chat2_bridging_Header_h
#define chat2_chat2_bridging_Header_h

@import UIKit;
@import Foundation;
@import SystemConfiguration;
@import MobileCoreServices;
@import Quickblox;

#import <QMServices.h>
#import <SVProgressHUD.h>

#import "QMChatViewController.h"
#import "QMChatContactRequestCell.h"
#import "QMChatNotificationCell.h"
#import "QMChatIncomingCell.h"
#import "QMChatOutgoingCell.h"
#import "QMCollectionViewFlowLayoutInvalidationContext.h"

#import "TTTAttributedLabel.h"

#import "TWMessageBarManager.h"

#import "_CDMessage.h"
#import "UIImage+QM.h"
#import "UIColor+QM.h"
#import "UIImage+fixOrientation.h"

#endif

**Comment by RivkiGlick** [comment]
#ifndef chat2_chat2_bridging_Header_h
#define chat2_chat2_bridging_Header_h

@import UIKit;
@import Foundation;
@import SystemConfiguration;
@import MobileCoreServices;
@import Quickblox;

#import <QMServices.h>
#import <SVProgressHUD.h>

#import "QMChatViewController.h"
#import "QMChatContactRequestCell.h"
#import "QMChatNotificationCell.h"
#import "QMChatIncomingCell.h"
#import "QMChatOutgoingCell.h"
#import "QMCollectionViewFlowLayoutInvalidationContext.h"

#import "TTTAttributedLabel.h"

#import "TWMessageBarManager.h"

#import "_CDMessage.h"
#import "UIImage+QM.h"
#import "UIColor+QM.h"
#import "UIImage+fixOrientation.h"



#endif

**Comment by RivkiGlick** [comment]
Attachment available until 24 Mar 2016

**Comment by RivkiGlick** [comment]
what can I do?

**Comment by Raikerian** [comment]
Duplicate: https://github.com/QuickBlox/q-municate-services-ios/issues/137
