### ISSUE TITLE
dosent recognize fiels of quickBlox framework

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#139]
I have added QuickBlox framework to my project but when I'm trying to use the classes of the framework it gives me the next message:
 Use of undeclared type 'QBChatDialog' 

I added quickBlox with pods, this is my podfile:

target 'chat2' do

pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'
# pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'
# 
# pod 'QMCVDevelopment' , :git => 'https://github.com/QuickBlox/QMChatViewController-ios', :branch => 'development'
# pod 'QuickBlox'

 pod 'QMServices'
 pod 'QMChatViewController'
end

and my |Header file lookes like this:
@import UIKit;
@import Foundation;
@import SystemConfiguration;
@import MobileCoreServices;
@import Quickblox;
# import <QMServices.h>
# import <SVProgressHUD.h>
# import "QMChatViewController.h"
# import "QMChatContactRequestCell.h"
# import "QMChatNotificationCell.h"
# import "QMChatIncomingCell.h"
# import "QMChatOutgoingCell.h"
# import "QMCollectionViewFlowLayoutInvalidationContext.h"
# import "TTTAttributedLabel.h"
# import "TWMessageBarManager.h"
# import "_CDMessage.h"
# import "UIImage+QM.h"
# import "UIColor+QM.h"
# import "UIImage+fixOrientation.h"

**Comment by Raikerian** [comment]
Duplicate: https://github.com/QuickBlox/q-municate-services-ios/issues/137
