### ISSUE TITLE
changeFramworks

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#141]
Hi,

I am changing QuickBlox framework in my project to a new one but I have some issues,
what can I use instead of: 
- (QBRequest *)createSessionWithExtendedParameters:(QBSessionParameters *)extendedParameters successBlock:(void (^)(QBResponse *response, QBASession *session))successBlock errorBlock:(QBRequestErrorBlock)errorBlock;

or: 
- (QBRequest *)createSessionWithSuccessBlock:(void (^)(QBResponse *response, QBASession *session))successBlock errorBlock:(QBRequestErrorBlock)errorBlock;

**Comment by Raikerian** [comment]
Hi,

The latest versions of our iOS SDK are managing session automatically, so you can just remove those methods from your project.

**Comment by RivkiGlick** [comment]
what happen's if there is an error?

**Comment by Raikerian** [comment]
If you will get session creation error you will receive errorBlock callback on any of QBRequest methods.

**Comment by RivkiGlick** [comment]
what happen's in this case: QBResponseStatusCode.UnAuthorized?

**Comment by Raikerian** [comment]
No, but It could be a different case scenario. You will receive full error in '[response.error reasons];'.

**Comment by RivkiGlick** [comment]
for example I'm trying to do logInWithUser what function of QBRequest I'm supposed to us?

**Comment by Raikerian** [comment]
This link should be helpful: http://quickblox.com/developers/SimpleSample-users-ios#Adding_a_User_Base_to_your_application

**Comment by Raikerian** [comment]
Is there any other questions? :)

**Comment by RivkiGlick** [comment]
what can be instead of completedWithResult()

**Comment by Raikerian** [comment]
You can pass nil there if there is no need for completion block.

**Comment by RivkiGlick** [comment]
I want to get the list of chat for a specific user
in the previous framework i used   completedWithResult how can I get it now?

**Comment by Raikerian** [comment]
Please checkout our samplechat documentation here: http://quickblox.com/developers/SimpleSample-chat_users-ios#Retrieve_list_of_dialogs

**Comment by Raikerian** [comment]
Any other questions regarding SDK update?

**Comment by Raikerian** [comment]
If you are still having any other troubles, feel free to create separate issue :)
