### ISSUE TITLE
How can I detect QB user had logged in another device?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#142]
User A login to device D1 then login to device D2.
How can I know user A logged in an other device (D2) when using device D1?

**Comment by iSevenDays** [comment]
Hi tranngoclinh88,

You can do it with http://quickblox.com/developers/SimpleSample-customObjects-ios

D2 and D1 writes their last request time.

For example

UDID D1: last request time
UDID D2: last request time

If last request time D1 less than 5 minutes, than D1 is online.

Thanks!

**Comment by tranngoclinh88** [comment]
User A is using D1 with account X
User B logins to D2 with account X.

Does QB send notification to D1 for user A know that account X logged into an other device?

**Comment by iSevenDays** [comment]
QB does not send any notifications about second, third etc. logged in user on your account.

You can do it with custom objects.

**Comment by tranngoclinh88** [comment]
Thanks.
