### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by Entea** [QuickBlox/q-municate-services-ios#144]
Pod install fails with message: `The 'Pods' target has transitive dependencies that include static binaries`

**Comment by iSevenDays** [comment]
Hi Entea,

Seems that you use !use_frameworks in your podfile. We do not support that.

https://github.com/QuickBlox/q-municate-services-ios/issues/132
https://github.com/QuickBlox/q-municate-services-ios/issues/119
https://github.com/QuickBlox/q-municate-services-ios/issues/118

**Comment by Entea** [comment]
Are there any plans to support dynamic frameworks in future? Would be great for users with swift projects. Closing this issue as it's a duplicate.

**Comment by Raikerian** [comment]
@Entea thanks for your question, yes, we are planning on distributing our SDK as dynamic framework in a near future, but unfortunately there is no any ETA for now.
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).
