### ISSUE TITLE
Remove user from group issue.

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#149]
I tried the remove user function.
1. A create group with B, C, D.
2. A remove B.
3. A add B into group.
   => B can not receive message A added B.
4. A, C, D type some messages in group
   => B can not receive any messages until go to other screen and comeback.

**Comment by Raikerian** [comment]
Hi,

In order to receive any messages from the group chat you need to join it.
We don't have user removal feature in our services, so you need to handle dialog join manually.

**Comment by Raikerian** [comment]
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).
If you are still having any other troubles, feel free to create separate issue.
