### ISSUE TITLE
Need method for send message about remove users in group.

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#150]
Currently, you have method sending message about leaving group but does not have method sending message about remove member in group.
Do you have task for this?

**Comment by Raikerian** [comment]
Hi,

No, and we do not have any plans on implementing such feature in a near future. Removing user from a group chat is not working at their best now, cause you cannot change the owner ID of dialog.
You can implement this method by adding custom parameter to the chat message, for example "removed_occupants_ids" and parse it on your own side just like we parse other custom parameters in [Q-municate](https://github.com/QuickBlox/q-municate-ios).

**Comment by Raikerian** [comment]
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).
If you are still having any other troubles, feel free to create separate issue.
