### ISSUE TITLE
Did not update last message userID when receive message

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#155]
I found that QMService did not update lastMessageUserID when receive/send message, only update last message text.
Please check.

**Comment by iSevenDays** [comment]
Hi tranngoclinh88,

Please provide us full logs with this issue

**Comment by tranngoclinh88** [comment]
Related issue
https://github.com/QuickBlox/quickblox-ios-sdk/issues/342

**Comment by iSevenDays** [comment]
tranngoclinh88, thank you for the report!

I was able to reproduce the issue, you can apply git diff or merge from feature/QMSERVICES-13 git branch.

This branch will be merged into develop branch and then will be merged in master in the next release.

Thanks!
