### ISSUE TITLE
Can not receive messages after delete dialog from memory storage

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#156]
I delete dialog from memory storage by these methods:

```
 [[QMApi instance].chatService.dialogsMemoryStorage deleteChatDialogWithID:chatDialog.ID];
  [[QMApi instance].chatService.messagesMemoryStorage deleteMessagesWithDialogID:chatDialog.ID];
```

After that, I can not receive any message in this dialog anymore. Please check!

**Comment by iSevenDays** [comment]
Hi tranngoclinh88,

After deleting a dialog from memory storage there is no instance which holds a reference to that dialog.

After releasing a dialog from memory, it calls -leave and you will not receive any message.

**Comment by tranngoclinh88** [comment]
@iSevenDays 
I just want to implement function like Facebook Messenger, delete dialog from list only.
Please tell me know how to do that.

**Comment by tranngoclinh88** [comment]
@iSevenDays 

```
 [[QMApi instance].chatService.dialogsMemoryStorage deleteChatDialogWithID:chatDialog.ID];
```

did not call -leave method.
Please check.

**Comment by iSevenDays** [comment]
tranngoclinh88, when there is no instance which references QBChatDialog, then QBChatDialog deallocates

In -deallocate method leave is called

If you have dedicated instance, you can ask admins to enable auto-join to rooms.

Else
You can write your custom datasource for UITableView/UICollectionView which will not be equal to the dialogsMemoryStorage and then you can exclude unneeded dialogs.

Thanks!

**Comment by Raikerian** [comment]
We haven't heard any updates from you regarding this issue. Closing this for now.
If you are still having any other troubles, feel free to create separate issue.
