### ISSUE TITLE
Quickblox/Quickblox.h not found when manually add QMServices into my project 

### ISSUE THREAD

**Issue by pt-nakul-sharma** [QuickBlox/q-municate-services-ios#157]
Quickblox/Quickblox.h not found in QMServices.h when manually added QMServices into my project, although compiler actually see Quickblox framework.

**Comment by iSevenDays** [comment]
Hi nakul1296,

Please double check framework search paths in Build settings

**Comment by pt-nakul-sharma** [comment]
Hi ISevenDays,
I check the frameworks search paths in build setting and set desired path. Now 13 errors are occurring like /TecorbProjects/MyProjects/Opportunity/Opportuniti/QMServices/QMServices/QMServices.h:13:9: 'QMDBStorage.h' file not found with <angled> include; use "quotes" instead

**Comment by iSevenDays** [comment]
It means the you use User header search paths, not Header search paths.

Please double check

**Comment by Raikerian** [comment]
Were you able to fix it?

**Comment by pt-nakul-sharma** [comment]
Not yet, i am still trying 

-----Original Message-----

**Comment by pt-nakul-sharma** [comment]
Hi, as per guide for manual integration I checked the framework search paths and header search paths. Now I am getting an error "Duplicate interface definition for class 'Bolts'". How can I fix it?

**Comment by iSevenDays** [comment]
It means that you have included bolts framework twice
Duplicate interface definition error will show you where are duplicates in Xcode build log

**Comment by pt-nakul-sharma** [comment]
Basically I am using FacebookSDK through Pods, so Bolts is a dependency for this and it's added though  pod. Bolts.framework is also there in QMService. But There are 10+ more ThirdParty Library that's using in my project. How can I fix it without deleting pod?

**Comment by Raikerian** [comment]
Try to remove our Bolts framework. As yours one is in pods, you should not need to set it in search paths.

**Comment by Raikerian** [comment]
Any updates on this? Were you able to fix it?

**Comment by pt-nakul-sharma** [comment]
Hi @Raikerian,
I have fixed it.
Thanks for your valuable guidance.

**Comment by Raikerian** [comment]
Glad to hear you were able to fix this :)
If you will have any other problems, let us know by creating a separate issue. Have a nice day!

**Comment by AbhayPansora** [comment]
Hi @Raikerian,
I face same issue like using FacebookSDK is depending on Bolts framework and now i am installing QMServices using pod,so its generating error.
And i am also applying this "Try to remove our Bolts framework. As yours one is in pods, you should not need to set it in search paths." but it is not useful for me. i am using ios swift.
So please help me  anyone how to solve this problem.

**Comment by ghost** [comment]
Hi @AbhayPansora , Please create separate issue for your question.

**Comment by Meet1313** [comment]
I have added QuickBlox manually but it throws error like 'Quickblox/Quickblox.h' file not found and Lexical or Preprocessor.
![screen shot 2018-04-23 at 2 10 04 pm](https://user-images.githubusercontent.com/29776778/39115733-3eb8bd56-4700-11e8-8ecf-f7176ffc93cd.png)
