### ISSUE TITLE
How to install the QMServices pods(Currently used in the Chat sample).

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/q-municate-services-ios#160]
Hi I am using the QuickBlox in my project. I updated Quickblox pods recently. I want to QMServices and QMChatViewController in the app. I am getting lot of issues with BFTask Like "Type arguments cannot be applied to non-parameterized class 'BFTask'".I  want  to add the latest QMChatViewController and  QMServices pods currently which are used in Chat sample.Please Give suggestions

Thank you

**Comment by Raikerian** [comment]
Hi,

Please follow this guide https://github.com/QuickBlox/q-municate-services-ios#1-cocoapods

**Comment by ajay2c9** [comment]
I install the pods like this

pod 'QuickBlox'
pod 'QMChatViewController'
 pod 'QMServices'. 

I directly used the few files like ServicesManager,NotificationService in the project. while comparing with the chat sample there are few new files added in QMservices. how can i update this pod to the latest one which is used in the chat sample.

I also tried to added as project with this which is mentioned in point 
1. Using an Xcode subproject
   i followed the steps mostly i get the errors with Bftask and I fix them. But lastly i got this error

ld: 92 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please give suggestions.

**Comment by Raikerian** [comment]
Remove 'pod Quickblox' and you will be good to go. QMChatViewController and QMServices will automatically fetch Quickblox iOS SDK as dependency through cocoapods.

**Comment by ajay2c9** [comment]
I am getting these issue I am getting lot of issues with BFTask Like "Type arguments cannot be applied to non-parameterized class 'BFTask'"
![screen shot 2016-03-17 at 11 43 25 pm](https://cloud.githubusercontent.com/assets/9112899/13856233/3b552afe-ec9a-11e5-8b6d-b96d1a618985.png)
![screen shot 2016-03-17 at 11 45 31 pm](https://cloud.githubusercontent.com/assets/9112899/13856272/65456b58-ec9a-11e5-94b7-d40c2a2b2c7d.png)
pod 'Fabric'
pod 'Crashlytics'
pod 'Taplytics'

I am using these pods and facebook framework old version.(2.2)

errors count is 20.Please give suggestions to fix these errors

Thank you

**Comment by ajay2c9** [comment]
After installing the pods i am getting the type argument cannot be applied to non parameterized class 'BFTask' and also this error. these are the screenshots are given below
![screen shot 2016-03-18 at 9 43 36 am](https://cloud.githubusercontent.com/assets/9112899/13868433/a2c73b10-ecee-11e5-835d-4695552f655f.png)
![screen shot 2016-03-17 at 11 43 25 pm](https://cloud.githubusercontent.com/assets/9112899/13868434/a2cc8d68-ecee-11e5-9fcd-79cd4d1c14b0.png)
please give suggestions to fix these issues.

**Comment by iSevenDays** [comment]
Hi ajay2c9,

I've just tried to reproduce the issue, but I couldn't.

Could you please give us your sample test project where we can reproduce the given issue?

Also please try to remove .xcworkspace, podfile.lock and Pods folder.
And then execute pod install.
Sometimes CocoaPods produces errors after updating pods.

**Comment by ajay2c9** [comment]
Thank you for suggestion i removed .xcworkspace, podfile.lock and Pods folder. its working fine now without facebook. in my project we have facebook login. the error is causing due to facebook framework. i removed it.After installing the facebook sdk, errors are generating some times like above errors and some times clang error is generating. I am attaching the facebook sdks here.please suggest me how to handle those errors. and also i tried this with chat sample. Same issue is generating. i am attaching the chat sample too . Please give suggestions to solve these errors

[sample-chat.zip](https://github.com/QuickBlox/q-municate-services-ios/files/179930/sample-chat.zip)

[FacebookSDK.zip](https://github.com/QuickBlox/q-municate-services-ios/files/179923/FacebookSDK.zip)  

Thank you

**Comment by Raikerian** [comment]
Please stick to one issue if the problem is the same: https://github.com/QuickBlox/quickblox-ios-sdk/issues/344
