### ISSUE TITLE
Add users to dialog

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#163]
I'm trying to add users to a dialog but I get this message:

 Error reasons:{
    errors =     (
        "You don't have appropriate permissions to perform this operation"
    );
}

this is my code:

  QBRequest.updateDialog(self.dialog!, successBlock: {(responce: QBResponse?, dialog: QBChatDialog?) in
                        println("sucsses")
                        for currGroup in self.pendingGroups{
                            if (currGroup as! Group).iGroupId == presedBtn.tag{
                                self.approvedGroups.addObject(currGroup)
                                self.pendingGroups.removeObject(currGroup)
                                self.tableView.reloadData()
                            }
                        }
                        }, errorBlock: {(response: QBResponse!) in
                            println("fail")
                    })

**Comment by Raikerian** [comment]
Hi,

You have created this issue in QMServices repository, can you try to reproduce this issue with QMServices method:

``` objectivec
- (void)joinOccupantsWithIDs:(NSArray *)ids toChatDialog:(QBChatDialog *)chatDialog
completion:(void(^)(QBResponse *response, QBChatDialog *updatedDialog))completion;
```

If you are not using QMServices, please provide us full log of that operation. Also make sure, that dialog you are updating is QBChatDialogTypeGroup and you are existent in the occupants list of it.

**Comment by RivkiGlick** [comment]
sorry but i didnt understand the answere

**Comment by Raikerian** [comment]
1. Please print self.dialog and show us the output.
2. Attach full log from a developer console here.
3. Try to reproduce the issue with the method i posted in the previous post.

**Comment by RivkiGlick** [comment]
now I get this messege:

Optional(
   Error reasons:{
    errors =     (
        "The resource wasn't found"
    );
})

and this is the log:

11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:07.088 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:08.080 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:09.085 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:10.077 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:11.089 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:12.076 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:13.083 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:14.089 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:15.089 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:16.080 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:17.079 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:18.080 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:19.079 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:20.087 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:21.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:22.079 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:23.081 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:24.079 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:25.079 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:26.089 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:27.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:28.079 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:29.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:30.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:31.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:32.093 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:33.088 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:34.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:35.089 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
112016-03-23 12:18:35.760 Shanti[315:35162] [ChatService] Presence RCV: <presence xmlns="jabber:client" from="6084079-19515@chat.quickblox.com/55168279-0CD9-44D2-A06C-8870C31ABDD9" to="6084079-19515@chat.quickblox.com"/>
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:36.076 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:37.076 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:38.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
112016-03-23 12:18:38.503 Shanti[315:35052] [ChatService] Presence SNT: <presence/>
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:39.088 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
112016-03-23 12:18:39.103 Shanti[315:35182] [ChatService] Presence RCV: <presence xmlns="jabber:client" from="6084079-19515@chat.quickblox.com/654CC43F-56FD-419D-AE6B-70B78E970B83" to="6084079-19515@chat.quickblox.com"/>
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:40.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:41.085 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:42.082 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:43.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:44.079 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:45.077 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:46.088 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:47.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:48.085 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:49.086 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:50.078 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:51.087 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:52.084 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:53.088 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:54.081 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:55.086 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:56.082 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:57.090 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:58.087 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:18:59.093 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
11ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING112016-03-23 12:19:00.090 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
112016-03-23 12:19:00.492 Shanti[315:34405] -[UIApplication endIgnoringInteractionEvents] called without matching -beginIgnoringInteractionEvents. Ignoring.
 self.dialog:Optional(
    ID:56714266a28f9a8201000b6e  
    Created At:(null)  
    Updated At:(null)  
    Room JID:19515_56714266a28f9a8201000b6e@muc.chat.quickblox.com  
    name:(null)  
    photo:(null)  
    type:2  
    lastMessage:(null)  
    lastMessageDate:(null)  
    occupantIDs:(null)  
    userID:0  
    data:(null)  
    unreadMessagesCount:0  
    lastMessageUserID:0)
2016-03-23 12:19:00.500 Shanti[315:35052] [QBCore] Request URL:https://api.quickblox.com/chat/Dialog/56714266a28f9a8201000b6e.json?push_all%5Boccupants_ids%5D%5B%5D=6084079
2016-03-23 12:19:00.501 Shanti[315:35052] [QBCore] Request method: PUT
2016-03-23 12:19:00.501 Shanti[315:35052] [QBCore] Request parameters:{
    "push_all" =     {
        "occupants_ids" =         (
            6084079
        );
    };
}
2016-03-23 12:19:00.502 Shanti[315:35052] [QBCore] Request headers: {
    "Content-Type" = "application/json";
    "QB-OS" = "iOS 8.3";
    "QB-SDK" = "iOS 2.6.6";
    "QB-Token" = e05689bfa2df5251fe61ba25b0167e8d1a77de40;
    "QuickBlox-REST-API-Version" = "0.1.1";
}
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDINGASCENDING^^^^^^^^^^^^^:22/03/2016 15:04:05
ASCENDINGASCENDINGASCENDINGASCENDINGASCENDING11112016-03-23 12:19:01.397 Shanti[315:35227] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo=0x168587a0 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x156eaa10> { URL: https://api.quickblox.com/chat/Dialog/56714266a28f9a8201000b6e.json?push_all%5Boccupants_ids%5D%5B%5D=6084079 } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "_";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 40;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 23 Mar 2016 10:19:01 GMT";
    "QB-Token-ExpirationDate" = "2016-03-23 12:05:20 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "404 Not Found";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = de59589eba530c652114e3ecbd8e0b66;
    "X-Runtime" = "0.010676";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/chat/Dialog/56714266a28f9a8201000b6e.json?push_all[occupants_ids][]=6084079, NSLocalizedDescription=Request failed: not found (404), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a5b22 54686520 7265736f 75726365 20776173 6e277420 666f756e 64225d7d>}
Optional(Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo=0x15718c10 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x156eaa10> { URL: https://api.quickblox.com/chat/Dialog/56714266a28f9a8201000b6e.json?push_all%5Boccupants_ids%5D%5B%5D=6084079 } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "_";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 40;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 23 Mar 2016 10:19:01 GMT";
    "QB-Token-ExpirationDate" = "2016-03-23 12:05:20 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "404 Not Found";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = de59589eba530c652114e3ecbd8e0b66;
    "X-Runtime" = "0.010676";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSLocalizedRecoverySuggestion={"errors":["The resource wasn't found"]}, NSErrorFailingURLKey=https://api.quickblox.com/chat/Dialog/56714266a28f9a8201000b6e.json?push_all[occupants_ids][]=6084079, NSLocalizedDescription=Request failed: not found (404), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a5b22 54686520 7265736f 75726365 20776173 6e277420 666f756e 64225d7d>})

**Comment by Raikerian** [comment]
The error you are getting basically saying to you that there is no such dialog on server. Can you check your admin panel for it?

**Comment by RivkiGlick** [comment]
this is my self.dialog:

Optional(
    ID:56714266a28f9a8201000b6e  
    Created At:(null)  
    Updated At:(null)  
    Room JID:19515_56714266a28f9a8201000b6e@muc.chat.quickblox.com  
    name:(null)  
    photo:(null)  
    type:2  
    lastMessage:(null)  
    lastMessageDate:(null)  
    occupantIDs:(null)  
    userID:0  
    data:(null)  
    unreadMessagesCount:0  
    lastMessageUserID:0)

**Comment by Raikerian** [comment]
Perform this operation to see whether dialog is existent on server:

``` objectivec
[QBRequest dialogsForPage:[QBResponsePage responsePageWithLimit:0] extendedRequest:@{@"_id":@"56714266a28f9a8201000b6e"} successBlock:^(QBResponse *response, NSArray *dialogObjects, NSSet *dialogsUsersIDs, QBResponsePage *page) {

        NSLog(@"Dialog was found: %@", dialogObjects.firstObject);
    } errorBlock:^(QBResponse *response) {

        NSLog(@"Dialog was not found on server");
    }];
```

Or convert it to swift in order to run in your swift project.

**Comment by RivkiGlick** [comment]
so now i cheket if it exists and it is but  I get the first message:

{com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17151970> { URL: https://api.quickblox.com/chat/Dialog/56f27eb6a28f9a198b00000c.json?push_all%5Boccupants_ids%5D%5B%5D=6827251 } { status code: 403, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 79;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 23 Mar 2016 11:43:25 GMT";
    "QB-Token-ExpirationDate" = "2016-03-23 13:37:06 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    Status = "403 Forbidden";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = ae0301fa557339a70d518069f2dabb44;
    "X-Runtime" = "0.029374";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSLocalizedRecoverySuggestion={"errors":["You don't have appropriate permissions to perform this operation"]}, NSErrorFailingURLKey=https://api.quickblox.com/chat/Dialog/56f27eb6a28f9a198b00000c.json?push_all[occupants_ids][]=6827251, NSLocalizedDescription=Request failed: forbidden (403), com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a5b22 596f7520 646f6e27 74206861 76652061 7070726f 70726961 74652070 65726d69 7373696f 6e732074 6f207065 72666f72 6d207468 6973206f 70657261 74696f6e 225d7d>})(lldb) po response.error

Optional(
   Error reasons:{
    errors =     (
        "You don't have appropriate permissions to perform this operation"
    );
})

and this is my self.dialog:

self.dialog:Optional(
    ID:56f27eb6a28f9a198b00000c  
    Created At:(null)  
    Updated At:(null)  
    Room JID:19515_56f27eb6a28f9a198b00000c@muc.chat.quickblox.com  
    name:(null)  
    photo:(null)  
    type:2  
    lastMessage:(null)  
    lastMessageDate:(null)  
    occupantIDs:(null)  
    userID:0  
    data:(null)  
    unreadMessagesCount:0  
    lastMessageUserID:0)

**Comment by Raikerian** [comment]
> You don't have appropriate permissions to perform this operation

Your occupantIDs for dialog are nil for some reason, and the error you are getting just telling that you does not belong to this dialog, therefore you cannot perform any changes to it.

**Comment by RivkiGlick** [comment]
can you explain me what I need to do
what needs to be in occupantIDs?

I whant to add my self to the dialog how do I do it?

**Comment by Raikerian** [comment]
You need to be added there or you need to create a dialog by yourself with self user ID set in occupantIDs.

**Comment by Raikerian** [comment]
@RivkiGlick 

Were you able to fix this?

**Comment by Raikerian** [comment]
We haven't hear any updates from you, if you are still experiencing this issue, just reopen it. If you are having any other troubles - just create a separate issue. Closing this for now.
