### ISSUE TITLE
How can I clear cached users?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#169]
How can I clear user memory storage, fetch latest data of users and store in cache?

**Comment by Raikerian** [comment]
Hi @tranngoclinh88 

We are planning to add force user update (in cache) parameter in a near future. But there is no any ETA for now.
Here is a solution for you:
1) Perform cache removal first:

``` objectivec
/**
 *  Delete all users
 *
 *  @param completion Completion block that is called after the delete operation has completed.
 */
- (QB_NONNULL BFTask *)deleteAllUsers;
```

2) Nil the the loadFromCacheTask ivar in QMUsersService file:

``` objectivec
@implementation QMUsersService {
    BFTask* loadFromCacheTask;
}
```

And now just load users as usual. Let me know if it works for you.

**Comment by tranngoclinh88** [comment]
Thank @Raikerian

**Comment by yishus** [comment]
Hi @Raikerian 

I'm getting `-[NSManagedObjectContext saveToPersistentStoreAndWait]: unrecognized selector sent to instance` for `deleteAllUsers`

**Comment by Raikerian** [comment]
Hi @yishus 

Check that you have `-ObjC` flag in other linker flags of your project. And if that doesn't help, create a separate issue with any information you think will be helpful for us.
