### ISSUE TITLE
Assignment to readonly property in class CDDialog.m

### ISSUE THREAD

**Issue by SSGangwar** [QuickBlox/q-municate-services-ios#170]
- (QBChatDialog *)toQBChatDialog {
  
  QBChatDialog *dialog = [[QBChatDialog alloc] initWithDialogID:self.dialogID type:self.dialogType.intValue];
  
  dialog.roomJID = self.roomJID; //here
  dialog.name = self.name;
  dialog.photo = self.photo;
  dialog.lastMessageText = self.lastMessageText;
  dialog.lastMessageDate = self.lastMessageDate;
  dialog.updatedAt = self.updatedAt;
  dialog.lastMessageUserID = self.lastMessageUserID.integerValue;
  dialog.unreadMessagesCount = self.unreadMessagesCount.integerValue;
  dialog.occupantIDs = self.occupantsIDs;
  dialog.userID = self.userID.unsignedIntegerValue;
  
  return dialog;
  }

**Comment by Raikerian** [comment]
Hi,

There was an iOS SDK update where roomJID was made readonly. In order to use QMServices with it you need to update to the latest version from master.

**Comment by Raikerian** [comment]
@SSGangwar were you able to resolve the issue?

**Comment by Raikerian** [comment]
@SSGangwar If you are still having any other troubles feel free to create a separate issue.

**Comment by gizmeondev** [comment]
Installing QMChatViewController (0.3.8)
Installing QMServices (0.2.5)
Installing QuickBlox (2.7.3)

its the latest one right

but still i am facing the same error . please advice us

Quick reply is really appreciated thanks in advance

Thanks
Nicky Patson
