### ISSUE TITLE
Install lastest version of QMServices

### ISSUE THREAD

**Issue by SSGangwar** [QuickBlox/q-municate-services-ios#171]
I am unable to install latest version of qmservices. I am using currently

  pod  'QMServices' 

 It always download version 0.2.5

**Comment by Raikerian** [comment]
Hi,

It is working correct for me, can you provide any logs and your exact podfile?

**Comment by Raikerian** [comment]
@SSGangwar were you able to resolve the issue?

**Comment by Raikerian** [comment]
@SSGangwar We haven't received any updates from you. If you are still having any other troubles feel free to create separate issue.

**Comment by gizmeondev** [comment]
Installing QMChatViewController (0.3.8)
Installing QMServices (0.2.5)
Installing QuickBlox (2.7.3)

is this is the latest one , Please confirm i am getting compilation error 

Thanks
Nicky Patson
