### ISSUE TITLE
How can I make volume while video call louder?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#174]
While in video calling, the volume is very low. How can I make it louder?

**Comment by Raikerian** [comment]
Hi,

Which QBRTCSoundRoute are you using?

**Comment by iSevenDays** [comment]
Hi @tranngoclinh88
QuickbloxWebRTC does not manage audio level. You can do this by yourself, or with hardware audio buttons.
Thanks
