### ISSUE TITLE
Issue about the path of the 3 bundle files in qmservice

### ISSUE THREAD

**Issue by yaodong-li** [QuickBlox/q-municate-services-ios#176]
First thanks for this powerful qmservice. I enjoyed it a lot. But I'm facing a issue: I installed the lib using cocoapods. The issue is like below:

/Build/Products/Debug-iphonesimulator/QMServices/QMChatCacheModel.bundle" not found. Run 'pod install' to update the copy resources script

Actually I did found all the bundles in QMServices/QMServices/xxx.bundle. After I moved all the bundles to the root path of QMServices folder, everything is working fine again. May I know why there is a nested "QMServices" folder in my simulator? How can I resolve this in the future? Thanks a lot!

**Comment by Raikerian** [comment]
Hi @fans3210 

Please provide us full log from pod install.

**Comment by yaodong-li** [comment]
Thanks. Although I cannot use this approach anymore because I really need to use dynamic framework in my swift project, but I tried again and here is the log:

YAOs-MacBook-Pro:TestAddQmPods FANS$ pod install --verbose
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-TestAddQmPods`: (``)

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A Bolts
  A QMServices
  A QuickBlox

Downloading dependencies

-> Installing Bolts (1.5.0)

> Copying Bolts from `/Users/FANS/Library/Caches/CocoaPods/Pods/Release/Bolts/1.5.0-722ab` to `Pods/Bolts`

-> Installing QMServices (0.3.8)

> Copying QMServices from `/Users/FANS/Library/Caches/CocoaPods/Pods/Release/QMServices/0.3.8-3e3b9` to `Pods/QMServices`

-> Installing QuickBlox (2.6.6)

> Copying QuickBlox from `/Users/FANS/Library/Caches/CocoaPods/Pods/Release/QuickBlox/2.6.6-8a860` to `Pods/QuickBlox`
> - Running pre install hooks

Generating Pods project
- Creating Pods project
- Adding source files to Pods project
- Adding frameworks to Pods project
- Adding libraries to Pods project
- Adding resources to Pods project
- Linking headers
- Installing targets
  - Installing target `Bolts` iOS 6.0
  - Installing target `QMServices` iOS 7.0
  - Installing target `Pods-TestAddQmPods` iOS 9.3
- Running post install hooks
- Writing Xcode project file to `Pods/Pods.xcodeproj`
  - Generating deterministic UUIDs
- Writing Lockfile in `Podfile.lock`
- Writing Manifest in `Pods/Manifest.lock`

Integrating client project

[!] Please close any current Xcode sessions and use `TestAddQmPods.xcworkspace` for this project from now on.

Integrating target `Pods-TestAddQmPods` (`TestAddQmPods.xcodeproj` project)
  Adding Build Phase '📦 Embed Pods Frameworks' to project.
  Adding Build Phase '📦 Copy Pods Resources' to project.
  Adding Build Phase '📦 Check Pods Manifest.lock' to project.
- Running post install hooks
  - cocoapods-stats from `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.3/lib/cocoapods_plugin.rb`

Sending stats
      - Bolts, 1.5.0
      - QMServices, 0.3.8
      - QuickBlox, 2.6.6
  Pod installation complete! There is 1 dependency from the Podfile and 3 total pods installed.

**Comment by yaodong-li** [comment]
And here are error messages and actual bundle path, Everytime I had to move these 3 bundles maually to make this error dismiss:

<img width="708" alt="screenshot 2016-04-11 16 21 06" src="https://cloud.githubusercontent.com/assets/6023208/14420959/8661212c-0001-11e6-9081-104f05f91c12.png">
<img width="617" alt="screenshot 2016-04-11 16 21 38" src="https://cloud.githubusercontent.com/assets/6023208/14420960/866f35dc-0001-11e6-983f-d4f2a3076b17.png">

**Comment by yaodong-li** [comment]
HI upgraded. It's a bug in cocoapods beta 6 version. They already fixed this. Thanks a lot for your help

**Comment by Raikerian** [comment]
@fans3210 Glad to see you have fixed it, if you are still having any other troubles feel free to create separate issue.
