### ISSUE TITLE
Push notification won't be sent if the app inactive or active (foreground)

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#178]
I noticed that during the chat p2p when clientA send to clientB message and clientB in foreground push notification won't be send.
A. Is it possible to send a push notification even though clientB in Foreground.
   A.1 If not - Can I disable push notification on sending message (so I will be able to generate my own Event ).
B. can I added some costumeData to message?

**Comment by Raikerian** [comment]
Hi,

A. You need to configure them in admin panel. Follow our guide [here](http://quickblox.com/developers/Chat#Alerts).
A1. Yes you can disable them, follow same guide.
B. You cannot add custom data to server-side pushes yourself, but there are some possible values available starting from PRO plan.

**Comment by Raikerian** [comment]
@mikeRozen If you are still having any other troubles please let us know by creating a separate issue.
