### ISSUE TITLE
Push Notification not Arriving.

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#181]
ClientA (android) sending to ClientB(IOS) message with push. But the push notification never arrives.
We do see in the dashboard the following:
![screen shot 2016-04-14 at 14 42 04](https://cloud.githubusercontent.com/assets/11506268/14526926/431b2aca-024f-11e6-93a2-97f5308874e4.png)
![screen shot 2016-04-14 at 14 42 15](https://cloud.githubusercontent.com/assets/11506268/14526934/51e3ce40-024f-11e6-9a2f-53cbdc839b1e.png)
1.As you can see my device is registered with different notifications tokens.(Yes we do logIn and LogOut to different devices.).Why does it attempt to send push notifications to all of them why not the last updated one?
![screen shot 2016-04-14 at 14 46 22](https://cloud.githubusercontent.com/assets/11506268/14526995/b687236a-024f-11e6-9bf8-703ec42247d1.png)
2.Print screen above describe the last push as you can see delivered = 0  queued = 4(so it wasn't really sent), why?
As far as I understand it get queued by previous tokens but there is no need to send them the push?
Can you please explain why it not really sent (delivered) or delivered with very long delay?

Thanks a lot.

**Comment by ghost** [comment]
Hi @mikeRozen, please provide full logs (iOS). For enable debug logs please use:

``` objective-c
    // File AppDelegate.h
    // Enables Quickblox REST API calls debug console output
    [QBSettings setLogLevel:QBLogLevelDebug];

    // Enables detailed XMPP logging in console output
    [QBSettings enableXMPPLogging];
```

**Comment by mikeRozen** [comment]
Hi **Pro100Andrey**,
Unfortunately we can't reproduce it, when the issue happens again we will add the logs.(It happened on Android side)
A.In any case can you please clarify/confirm that push notification is sent to all the tokens user have?(even though those are old tokens).
B. Another thing that maybe caused a little confusion (to the push notifications) is the case that push notifications are not sent when the app is in foreground while sending message.
- On iOS side I do listen to proper delegate and manage to handle it properly.
- But on Android side we struggle to find the proper way .Can you please show/forward us to proper implementation for some sort of listener on android side when the app in foreground?

Thank you.

**Comment by mikeRozen** [comment]
**Pro100Andrey**,
Do u have any update?

**Comment by mikeRozen** [comment]
Ok, I succeed to reproduce it .
Image from dashboard:
![screen shot 2016-04-19 at 16 21 04](https://cloud.githubusercontent.com/assets/11506268/14640610/f79d0212-064a-11e6-8ba9-a1b69f357c86.png)

[attachment log](https://gist.github.com/Pro100Andrey/64ce7c905c766c2d8e8e0d396836f36c)

No Push notification arrive. The app in the background.
**Edit:** Notifications start to arrive after around 1hr delay

**Comment by ghost** [comment]
@mikeRozen , Have u resolved this issue?

**Comment by mikeRozen** [comment]
**VitaliyGuru** 
I deleted all the notification tokens in the dashboard and login again with the user(**its not a solution at all** ).I believe  they try to send the notification to all registered tokens of that user (even the old ones), as a result it cause a  queue  which cause a delay .(of course it might be wrong).
Its really upset me that quickblox team doesn't replay to that issue.
Regarding Android listener I still have no idea how to listen to message when app in the foreground.

**Comment by ghost** [comment]
@mikeRozen , Could you please provide your AppID from the Admin panel?
We will investigate this issue with the server team.

**Comment by mikeRozen** [comment]
Sure,
![screen shot 2016-04-21 at 11 47 29](https://cloud.githubusercontent.com/assets/11506268/14703128/e99d60c2-07b6-11e6-8d7f-dc5f4f5f825e.png)
**VitaliyGuru** maybe you can forward/link me to correct implementation of android listener while app is in foreground? 
I asked that [question](https://github.com/QuickBlox/quickblox-android-sdk/issues/172) , but nobody answer (also I saw some threads on StackOverflow without any answer).

**Comment by ghost** [comment]
@mikeRozen , I'l ask the Android team to help you.

**Comment by ghost** [comment]
@mikeRozen ,
As for notifications on IOS,  we got logs from APNS server:

```
[2016-04-21 08:23:32] [ERROR] 25307_d is banned due to OpenSSL::SSL::SSLError, SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
[2016-04-21 08:06:38] [ERROR] 25307_d is banned due to OpenSSL::SSL::SSLError, SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
```

It means that your token or certificate is not valid. Could you please try to generate and upload new certificate to the admin panel? We suppose it will resolve the issue.

**Comment by mikeRozen** [comment]
Ok, I will update you.
But the notifications do arrive but sometimes with really long delay.

**Comment by mikeRozen** [comment]
**VitallyGuru**
Sorry I will not revoke my certificates. Its the same certificates I use on the server.
As I told before the notifications DO arrive but some times they arrive with DELAY.
We have the same issue on Android.
In the dashboard we see some sort of queue which created  with delivered 0. After some time its get delivered.

**Comment by ghost** [comment]
@mikeRozen , 
There is no need to revoke your existing certificate. Just create new one and upload it to the admin panel.

**Comment by jellelute** [comment]
Hello,

I encounter about the same problem. Push notificaties from android to IOS or IOS to IOS are significantly delayed (couple of hours) or do not arrive at all. I think this situations exists for 2 days now (based on usage stats). 

The problem exists also when i send messages via the admin panel. 

Today I did as you suggested and renewed the certificates, but it makes no difference. 

My application Id is 12660. 

Could you please have a look. 
Best regards,
Jelle

**Comment by ghost** [comment]
Hello @jellelute ,
I'll ask server team to check your application. BTW, do you have any logs from sent/not sent push notifications in the admin panel?

**Comment by jellelute** [comment]
Thanks @VitaliyGuru 

Here is one example of not sent push (my latest test):

Message 6754672 log
APNS (Apple Push) Delivered: 0, failed: 0 
Download detailed log 

Event log
2016-04-29 12:46:37 UTC : queued 1 notifications

**Comment by jellelute** [comment]
Another example of one that was delivered but with couple hours delay (ID:  6744921):

{"notification":{"aps":{"alert":"Jelle Lute in Klaverjassen!!!!: Dat is prima! Tot morgen ","badge":1,"sound":"default"},"type":"2","eventId":"1461617629gzxzlvY90F"},"log":[{"device_token":"81ddc8ba72dbf8cdb6cbcf5a29e0be2006ad77b177de13e2d878c7969ad8a20a","created_at":"2016-04-28T19:55:18Z","delivered_at":"2016-04-29T03:05:02Z","failed_at":null,"error_code":null,"error_description":null}]}

**Comment by ghost** [comment]
@jellelute , Do you have failed push notifications?  If you do, please download detailed log and attach here.

**Comment by ghost** [comment]
@jellelute , Do you send pushes from production or development environment? What's Quickblox iOS SDK version you're using?

**Comment by ghost** [comment]
@jellelute , We got the following logs:
[2016-04-28 12:29:38] [ERROR] [12660_p] The APNs disconnected before any notifications could be delivered. This usually indicates you are using an invalid certificate.
[2016-04-28 12:29:38] [ERROR] [12660_p] The APNs disconnected before any notifications could be delivered. This usually indicates you are using an invalid certificate.
[2016-04-28 01:49:19] [ERROR] [12660_p] The APNs disconnected before any notifications could be delivered. This usually indicates you are using an invalid certificate.
[2016-04-28 01:49:19] [ERROR] [12660_p] The APNs disconnected before any notifications could be delivered. This usually indicates you are using an invalid certificate.

**Comment by jellelute** [comment]
@VitaliyGuru, Thanks for the investigation. We are using production environment to send push notifications as the app is in production. We are currently using SDK 2.6.4 for IOS. We've tested version 2.7 and did not get stable results connecting to the chat. That's why we've not upgraded. 
- I've not found examples of push notifications failing. Notifications are delivered with a delay. 
- Do these errors refer to the certificate under push notifications -> settings? 
- I'm using Quickblox for a few years now and it did always work and now it stopped working. I did not change the certificate until today. Therefore I doubt that the certificate is invalid. But anyway, with the renewed certificate of today it should wrok. 
- Today I created and uploaded a new production certificate. Can you see any of these errors with date later than 2016-04-29 12:00:00 UTC?

Here is a recent example of a push notification created on the admin panel (created 30 min ago and still queued):

Message 6755265 log
APNS (Apple Push) Delivered: 0, failed: 0 
Download detailed log 

Event log
2016-04-29 14:04:03 UTC : queued 1 notifications

{"notification":{"aps":{"alert":"test2","sound":"default"}},"log":[{"device_token":"0be735688d6cb102a4e1936feac3b760538cdd12281f108862a87bf9f3be2351","created_at":"2016-04-29T14:04:03Z","delivered_at":null,"failed_at":null,"error_code":null,"error_description":null}]}

---

## This is whats the admin panel states about the apns production certificate: 

Apple Push Notification Service (APNS)

Production certificate

Bundle: Apple Push Services: com.xxx
Valid until 29-05-2017
ACTIVE
Delete View error log

**Comment by ghost** [comment]
@jellelute @mikeRozen , Thank you for being patient. We will investigate and try to fix it ASAP.

**Comment by mikeRozen** [comment]
**VitaliyGuru**
Just short update.
I replaced the certificate as you asked and we bought first "advance".(First I checked on our pre prod servers and it worked).
Now I check the live version which wasn't changed at all and push notification simply not arrive.
`{"notification":null,"log":[]}` - this the log from dashboard with _delivered - 0 and failed - 0_
Right now push notification stop work on our live version.
Also do we need to set production/Development in the SDK somewhere?(or it should pick up automatically) we use `QuickBlox (~> 2.5)`. Right now it happened between Android and IOS only.
Please help.

**Comment by ghost** [comment]
@mikeRozen , 

> Also do we need to set production/Development in the SDK somewhere?(or it should pick up automatically) we use QuickBlox (~> 2.5)

Please, refer to [#338](https://github.com/QuickBlox/quickblox-ios-sdk/issues/338)

**Comment by mikeRozen** [comment]
**VitaliyGuru**
Thanks for reply. Can you please ask one of your Android team refer to [#172](https://github.com/QuickBlox/quickblox-android-sdk/issues/172)

**Comment by mikeRozen** [comment]
**update:**
When sending message from IOS to Android and vica versa on production version (Ad hoc). NO Push Notification arrive. Sending from IOS to Android generated only ONE push notification(first one) in Quickblox dashboard.
After each sending any message:
`- (void)chatDidDeliverMessageWithID:(NSString *)messageID dialogID:(NSString *)dialogID toUserID:(NSUInteger)userID`
is triggered with 
`NSParameterAssert(dialogID != nil) - Will fail here messageID = 5731f9e57eaab1a2260041b6,dialogID = (null) , userID = 12490118
`(my own log which tell that dialog is empty).
When Anroid send to IOS :
Push notification GET generated in dashboard :(0 delivered , 0 failed)
`{"notification":null,"log":[]}` but no notification arrive.
 Neither Android nor IOS receive a notification. (if we send from IOS to IOS or Android to Android everything works as expected).

Thanks for help.

**Comment by ghost** [comment]
@mikeRozen , @jellelute 
Hi guys, yesterday our server team uploaded new updates. I hope this updates resolved issues with push notifications. Please try now. Waiting for your reply.

**Comment by mikeRozen** [comment]
**@VitaliyGuru** 
Its not working between Android an IOS (its do work between IOS to IOS and Android to Android).
When Sending Android to IOS I do see the notification in the dashboard queue:
![screen shot 2016-05-24 at 2 50 28 pm](https://cloud.githubusercontent.com/assets/11506268/15502835/00eaa0d8-21bf-11e6-95b3-055d9b4d9d8d.png)
`{"notification":null,"log":[]}`
but no notifications arrive to IOS.
When sending IOS to Android we don't see the notification in the dashboard queue at all and Android receive no notification.
Please tell me if you need any further information.

**Comment by Raikerian** [comment]
Hey @mikeRozen 

Are you sure that you are using [Universal push notifications](http://quickblox.com/developers/SimpleSample-messages_users-ios#Universal_push_notifications)?

**Comment by mikeRozen** [comment]
Hi **Raikerian**,
So we tried both on Production version and on Development version (both version use the same code).
On development version everything work as expected.
On Production version push notification doesn't arrive at all (iOS-> Android and Android ->IOS).
**Case 1: (IOS->Android)**
![screen shot 2016-06-05 at 11 08 50 am](https://cloud.githubusercontent.com/assets/11506268/15804470/04bddc8c-2b12-11e6-9fc5-e015c946ad76.png)
![screen shot 2016-06-05 at 11 10 35 am](https://cloud.githubusercontent.com/assets/11506268/15804471/14af5422-2b12-11e6-99ad-4324aea9dcb4.png)

[7251442_log.txt](https://github.com/QuickBlox/q-municate-services-ios/files/299259/7251442_log.txt)
**Case 2: (Android->IOS)**
![screen shot 2016-06-05 at 11 15 09 am](https://cloud.githubusercontent.com/assets/11506268/15804485/aabc1202-2b12-11e6-9813-9a28754de1d3.png)
![screen shot 2016-06-05 at 11 17 45 am](https://cloud.githubusercontent.com/assets/11506268/15804487/b315e3e2-2b12-11e6-8121-0c7b1447f5a5.png)
[7251488_log.txt](https://github.com/QuickBlox/q-municate-services-ios/files/299260/7251488_log.txt)

Code which get triggered every time after sending message:

```
 - (void)createEventWithMessage: (NSString *)message {
    NSLog(@"createEventWithMessage: Entry message = %@",message);
    // removing current user from occupantIDs
    NSMutableArray *occupantsWithoutCurrentUser = [NSMutableArray array];
    for (NSNumber *identifier in self.dialog.occupantIDs) {
        if (![identifier isEqualToNumber:@([QBServiceManager instance].currentUser.ID)])
            [occupantsWithoutCurrentUser addObject:identifier];
    }
 // Sending push with event
    QBMEvent *event = [QBMEvent event];
    event.notificationType = QBMNotificationTypePush;
    event.usersIDs = [occupantsWithoutCurrentUser componentsJoinedByString:@","];
    event.type = QBMEventTypeOneShot;

    // custom params
    if (IsEmpty(message) || IsEmpty(self.dialog.ID) || IsEmpty([QBServiceManager instance].currentUser.login) || IsEmpty([QBServiceManager instance].currentUser.fullName))
        return;

    NSDictionary  *dictPush = @{kPushNotificationDialogMessageKey : message,
                                kPushNotificationDialogIdentifierKey : self.dialog.ID,
                                @"userGuid" : [QBServiceManager instance].currentUser.login,
                                @"name" : [QBServiceManager instance].currentUser.fullName,
                                @"ios_sound" : @"notification_and_message.wav",
                                @"ios_badge" : @"1"
                                };
    //
    //NSLog(@"dictPush = %@",dictPush);
    NSError *error = nil;
    NSData *sendData = [NSJSONSerialization dataWithJSONObject:dictPush options:NSJSONWritingPrettyPrinted error:&error];
    NSString *jsonString = [[NSString alloc] initWithData:sendData encoding:NSUTF8StringEncoding];
    //
    event.message = jsonString;

    [QBRequest createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
        if (!response.error)
            NSLog(@"push sent succefully");
    } errorBlock:^(QBResponse *response) {
        //
    }];
    NSLog(@"createEventWithMessage: Exit");
}

```

```
- QMServices (0.3.3):
    - Bolts (= 1.3.0)
    - libextobjc/EXTKeyPathCoding (= 0.4.1)
    - libextobjc/EXTScope (= 0.4.1)
    - QuickBlox (~> 2.5)
  - QuickBlox (2.5)
```

Thanks a lot, Please suggest if you need any further information.

**Comment by ghost** [comment]
How did you test iOS -Android ?

In order to test the production push notification service choose the Adhoc dist profile to code sign your app. Archive ipa and save for adhoc distribution. Add the ipa to your device and test push. It will use production push certs as opposed to development cert.

Did you test the same way as written above?

**Comment by mikeRozen** [comment]
No,
We just downloaded the last versions from the app Store.(Should be the same).

**Comment by ghost** [comment]
try to add UIAlertView in this method: 
`[QBRequest createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
        if (!response.error)
            NSLog(@"push sent succefully");
    } errorBlock:^(QBResponse *response) {
        //
    }];`

in success and error block. Ant try to test production pushes using AdHoc. We should be sure that event added successfully.

**Comment by mikeRozen** [comment]
**VitaliyGuru**
Thanks for your help. 
IOS to IOS and Android to Android work as expected.(IOS app used AD-Hocked provision Archived as Release distributed by Crashlytics, android was downloaded from store) 
As you  asked I inserted the following Alerts.

```
[QBRequest createEvent:event successBlock:^(QBResponse *response, NSArray *events) {
        if (!response.error){
            NSLog(@"push sent successfully"
            [DZCommonViews createAlertViewWithTitle:@"Success" Msg:@"message sent succefully " Cancel:nil Confirm:@"OK" delegate:nil];
        }else{
            [DZCommonViews createAlertViewWithTitle:@"Error" Msg:[NSString stringWithFormat:@"Error = %@",response.error] Cancel:nil Confirm:@"OK" delegate:nil];
        }

    } errorBlock:^(QBResponse *response) {
        [DZCommonViews createAlertViewWithTitle:@"Error" Msg:[NSString stringWithFormat:@"ErrorBlock = %@",response.error] Cancel:nil Confirm:@"OK" delegate:nil];
    }];
```

When sending from IOS to Android we receive the following Error on push: (No push received BUT message DO arrive, we don't see any push in the dashboard in contrast to previous time)
![screen shot 2016-06-12 at 5 54 11 pm](https://cloud.githubusercontent.com/assets/11506268/15991820/d809900e-30c6-11e6-9100-50403f11069b.png)
![screen shot 2016-06-12 at 5 37 51 pm](https://cloud.githubusercontent.com/assets/11506268/15991828/ffafdaaa-30c6-11e6-96a8-f590fb3d94db.png)

We did check the Id of the user we send them the message it exist and valid .

Thanks again, please tell me if you need any additional information.

**Comment by ghost** [comment]
Could you please show you code where you create subscription on android side?
What version of Quickblox AndroidSDK are you using?

**Comment by Aento** [comment]
Quickblox  SDK version is 2_2_6
Android SDK 23

And code of  subscription on android side:

```
            QBMessages.subscribeToPushNotificationsTask(regId, deviceId, QBEnvironment.DEVELOPMENT, new QBEntityCallbackImpl<ArrayList<QBSubscription>>() {
                @Override
                public void onSuccess(ArrayList<QBSubscription> qbSubscriptions, Bundle bundle) {
                    Log.d(TAG, "subscribed");
                }

                @Override
                public void onError(List<String> strings) {
                    Log.d(TAG, "not subscribed");
                }
            });
```

**Comment by ghost** [comment]
QBEnvironment.DEVELOPMENT
Have you try to set  QBEnvironment to production?

**Comment by mikeRozen** [comment]
We set both Apps to dev mode:
IOS does receive all push notifications in all three states (Active, background ,terminated).
Android does not receive push notification when its terminated (in all other states it work correctly)
![screen shot 2016-06-19 at 6 28 05 pm](https://cloud.githubusercontent.com/assets/11506268/16178306/a4fed080-364c-11e6-84f7-4afb17df6b0c.png)
[Logs.txt](https://github.com/QuickBlox/q-municate-services-ios/files/322357/Logs.txt)

On the Production Mode:(iOS and android)
The notifications doesn't arrive at all iOS Android, Android IOS.
![screen shot 2016-06-19 at 7 21 33 pm](https://cloud.githubusercontent.com/assets/11506268/16178514/1a0e566a-3653-11e6-93b2-45bb89f512b8.png)
[logIosAndroid.txt](https://github.com/QuickBlox/q-municate-services-ios/files/322379/logIosAndroid.txt)

![screen shot 2016-06-19 at 7 23 37 pm](https://cloud.githubusercontent.com/assets/11506268/16178527/7d8e8b06-3653-11e6-93fd-153d44cc01ea.png)
[AndroidIos.txt](https://github.com/QuickBlox/q-municate-services-ios/files/322380/AndroidIos.txt)

Please have a look at iOS Android logs "_Unauthorized, check your App auth_key._"
Thanks.

**Comment by ghost** [comment]
Hello @mikeRozen , as you can see from logIosAndroid.txt  your device_token is null. That's why you're receiving `Unauthorized, check your App auth_key.`

**Comment by mikeRozen** [comment]
Hello **VitaliyGuru**,
I see that its null BUT (Android doesn't receive an error when he subscribe AND we do see the new token in the dashboard, as you can see from the image/icon it recognize Android .)Furthermore Development and production Environment use the same code.
- I still don't understand why IOS stop to receive notification on Production (I release the build via Crashlytics but I don't think that a problem).
-  On Development why Android stop to receive notification when it terminated. 
- Do u have a suggestion how can it be tested to understand where is the problem?

Thanks.

**Comment by ghost** [comment]
@mikeRozen I gave all these information to Android team. They're investigating this problem.

**Comment by tatanka987** [comment]
Hello @mikeRozen, for checking work android push notification you need:
- create subscription for device (see this [link](http://quickblox.com/developers/SimpleSample-messages_users-android#Giving_a_user_a_Push_Notification_subscription) about creating subscription);
- check subscription in admin panel for recipient (see this links for information about  [creating app in Google Developer Console](http://quickblox.com/developers/How_to_generate_Google_App_Project_number) and about [generating API key and configure QuickBlox admin panel for working with Android pushes](http://quickblox.com/developers/How_to_generate_API_key_and_set_it_in_QuickBlox_admin_panel));
- try to send push notification from admin panel (instruction [there](http://quickblox.com/developers/SimpleSample-messages_users-android#Send_Push_Notifications_from_Admin_panel));
- check work android pushes on our [Pushnotifications Sample ](https://github.com/QuickBlox/quickblox-android-sdk)  with your credentials;

**Comment by mikeRozen** [comment]
Hi **tatanka987**,
Sorry for late response as you can see from the thread Android to Android does work as expected (Android to iOS and vice versa doesn't work properly) so I believe Android side made the correct configuration.
Currently, as this issue take too much time we will send Push notification through our servers.
Appreciate your help. Thanks.

**Comment by lakshmibomma** [comment]
Hi,
Push notifications are not working from **iOS to Android** and **Android to iOS** on release (production) version. It was working earlier almost 20 days back on both development and production. Now my app is only working on development on both the platforms. Can you guys please lets us know what will be the fix for that. We are using Quickblox framework 2.7.4 version

**Comment by Raikerian** [comment]
Hi everyone.

There was lots of updates for push notification module since date of the last post in this issue. I recommend every one of you to check it of you haven't had any luck before.
If the issue is still there for you, I suggest you to create a new issue in our main repository here: https://github.com/QuickBlox/quickblox-ios-sdk/ and we will take a look one more time.

**Comment by MahadevT** [comment]
Hi,
    In my application am Sending push notification for multiple action like buddy request, event request. But for me if i send buddy request or event request notification is Arriving occupationally not all the time and For chat push notification completely not working. I checked in the QuickBlox dashboard ,There i can see notification list.Please can anyone  help.

**Comment by MahadevT** [comment]
Hi,
    Am receiving notification if i send from QuickBlox dashboard but from device to device push notification not working please suggest me to fix this issue

**Comment by phiren** [comment]
Same problem, it delivers after long time

**Comment by phiren** [comment]
@MahadevT , same problem, it shows status active and clicking on active, it shows below information:
APNS (Apple Push) Delivered: 0, failed: 0 

There were no recipients for this scheduled event. You may need to check 'Subscriber filtering' settings for your event. For example: there are no users with specified tags. 

![screen shot 2017-07-10 at 5 04 55 pm](https://user-images.githubusercontent.com/8377260/28016449-01b043f2-6592-11e7-87c1-e556edbc809e.png)

**Comment by khlystov** [comment]
@Raikerian same problem, on IOS and Android. Thanks for "good" services

**Comment by Raikerian** [comment]
@khlystov please create a separate issue and describe your problem in details. Because it probably will need help from our server team as well. If you have set up every push certificate right, this shouldn't be an iOS problem.

Does your issue relate to QMServices by the way? If not, please move to this main repository:
https://github.com/QuickBlox/quickblox-ios-sdk
