### ISSUE TITLE
0.3.9 Crash on dispatch_once in swift

### ISSUE THREAD

**Issue by yaodong-li** [QuickBlox/q-municate-services-ios#185]
QBSettings are fine, but I still cannot use QMServicesManager.instance(), app will crash. I don't whether I've done anything wrong. Here is the sample project I just set up. Thank you

https://www.dropbox.com/s/ih6qcuo8yec97h5/TestAddQM16APR.zip?dl=0

<img width="715" alt="screenshot 2016-04-16 12 48 30" src="https://cloud.githubusercontent.com/assets/6023208/14579173/09759f38-03d2-11e6-85c6-90fc0c323d87.png">
<img width="742" alt="screenshot 2016-04-16 12 47 57" src="https://cloud.githubusercontent.com/assets/6023208/14579175/0c7d76e2-03d2-11e6-99ce-e9a8860ed5d3.png">
<img width="741" alt="screenshot 2016-04-16 12 48 06" src="https://cloud.githubusercontent.com/assets/6023208/14579176/0e57cea4-03d2-11e6-8d74-68848867a3bd.png">

**Comment by Raikerian** [comment]
Hi,

Have you checked your other linker flags build settings? Are they same according to guide?

**Comment by yaodong-li** [comment]
Yes I've already set the other linker flags according to the instructions. I've attached my newly created project https://www.dropbox.com/s/ih6qcuo8yec97h5/TestAddQM16APR.zip?dl=0

**Comment by Raikerian** [comment]
@fans3210 checkout my working swift project [here](https://dl.dropboxusercontent.com/u/55192255/QMTest.zip).

**Comment by yaodong-li** [comment]
Ok. I ran your project without error. I will check on your settings. If I face further issues, I will file new tickets for it. Thanks a lot!

**Comment by Raikerian** [comment]
@fans3210 We were able found an error in your project, you have wrong flag for "-ObjC". It was "-ObjC," with coma at the end. Thats why you received the crash. Please modify your project and use it instead of mine (it has old SDK and services in it).

If you are still having any other questions, feel free to let us know by creating a separate issue.
