### ISSUE TITLE
QBUUser category modification

### ISSUE THREAD

**Issue by budlight** [QuickBlox/q-municate-services-ios#186]
q-municate-services-ios/QMUsersService/QMUsersService/Categories/QBUUser+CustomData.m

these three methods/properties should be made "public"

```
@property (strong, nonatomic) NSMutableDictionary *context;
- (void)syncronize {
- (NSMutableDictionary *)jsonObject {
```

there might already be methods on QBUUser equivalent to them I'm not aware of.

**Comment by ghost** [comment]
Hi @budlight ,
Do you have any reasons to do this?
You can fork our repo and modify it for your needs.

**Comment by budlight** [comment]
what is the point of you guys allowing custom data if there is no easy way to modify/read it? These methods make reading the custom data of a QBUUser much easer.

Is there any reason not to do this?  You could have already changed it in the time it took to reply to this.

**Comment by Raikerian** [comment]
Hi @budlight 

Thank you for your suggestion, it is good indeed. We will investigate the best possible way to open it and post update soon.

In order for you to use them now, you can fork from our repository, or you can also install QMServices as [development pods](https://guides.cocoapods.org/making/making-a-cocoapod.html). In that way you can modify files as you want.

**Comment by budlight** [comment]
i don't wish to maintain my own fork for me a much easier solution is to just rename context to context1 and copy the methods into my own category

**Comment by Raikerian** [comment]
@budlight added in 0.4.
