### ISSUE TITLE
LICENSE` for the spec `QM Chat View Controller (0.3.6)`

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#188]
Hi I'm trying to install pod 'QMServices' but i get the next error:

[!] Unable to read the license file `/Users/user/Shantiapp-IoS/Pods/LICENSE` for the spec `QMChatViewController (0.3.6)`

[!] Unable to read the license file `/Users/user/Shantiapp-IoS/Pods/LICENSE.txt` for the spec `QMServices (0.3.9)`

[!] Unable to read the license file `/Users/user/Shantiapp-IoS/Pods/LICENSE` for the spec `QMChatViewController (0.3.6)`

[!] Unable to read the license file `/Users/user/Shantiapp-IoS/Pods/LICENSE.txt` for the spec `QMServices (0.3.9)`

what can I do?

**Comment by Raikerian** [comment]
Hi,

You can just ignore those warnings without any worries. Will be fixed in the next release. Thanks for reporting.

**Comment by RivkiGlick** [comment]
but I get errors and it dosen't give me to run the application

**Comment by Raikerian** [comment]
@RivkiGlick those are not errors. It is just a warnings, if you have any errors - post a full log here.

**Comment by RivkiGlick** [comment]
ok thank you

**Comment by RivkiGlick** [comment]
I'm having  a problem with bolds.framework it's giving me many of  error's

**Comment by Raikerian** [comment]
Post full log with **all errors** here.

**Comment by RivkiGlick** [comment]
n file included from /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/iOS/BFAppLinkNavigation.m:13:
In file included from /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/Bolts.h:15:
/Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:52:31: error: expected '>'
@interface BFTask<__covariant ResultType> : NSObject
                              ^
/Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:52:31: error: unknown type name 'ResultType'; did you mean 'ResType'?
@interface BFTask<__covariant ResultType> : NSObject
                              ^~~~~~~~~~
                              ResType
In module 'UIKit' imported from /Users/hodayaohana/Shantiapp-IoS2/Pods/Target Support Files/Bolts/Bolts-prefix.pch:2:
In module 'Darwin' imported from /Applications/Xcode 3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKitDefines.h:8:
/Applications/Xcode 3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/include/MacTypes.h:292:41: note: 'ResType' declared here
typedef FourCharCode                    ResType;
                                        ^
In file included from /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/iOS/BFAppLinkNavigation.m:13:
In file included from /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/Bolts.h:15:
/Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:52:41: error: expected identifier or '('
@interface BFTask<__covariant ResultType> : NSObject
                                        ^
/Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:63:42: error: expected ')'
- (instancetype)taskWithResult:(nullable ResultType)result;
                                       ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:63:32: note: to match this '('
- (instancetype)taskWithResult:(nullable ResultType)result;
                             ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:63:1: error: missing context for method declaration
- (instancetype)taskWithResult:(nullable ResultType)result;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:69:1: error: expected method body
- (instancetype)taskWithError:(NSError *)error;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:75:1: error: missing context for method declaration
- (instancetype)taskWithException:(NSException *)exception;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:80:1: error: expected method body
- (instancetype)cancelledTask;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:87:70: error: expected '>'
- (instancetype)taskForCompletionOfAllTasks:(nullable NSArray<BFTask *> *)tasks;
                                                                   ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:87:71: error: expected ')'
- (instancetype)taskForCompletionOfAllTasks:(nullable NSArray<BFTask *> *)tasks;
                                                                    ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:87:45: note: to match this '('
- (instancetype)taskForCompletionOfAllTasks:(nullable NSArray<BFTask *> *)tasks;
                                          ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:87:1: error: missing context for method declaration
- (instancetype)taskForCompletionOfAllTasks:(nullable NSArray<BFTask *> *)tasks;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:95:1: error: expected method body
- (instancetype)taskForCompletionOfAllTasksWithResults:(nullable NSArray<BFTask *> *)tasks;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:103:69: error: expected '>'
- (instancetype)taskForCompletionOfAnyTask:(nullable NSArray<BFTask *> *)tasks;
                                                                  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:103:70: error: expected ')'
- (instancetype)taskForCompletionOfAnyTask:(nullable NSArray<BFTask *> *)tasks;
                                                                   ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:103:44: note: to match this '('
- (instancetype)taskForCompletionOfAnyTask:(nullable NSArray<BFTask *> *)tasks;
                                         ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:103:1: error: missing context for method declaration
- (instancetype)taskForCompletionOfAnyTask:(nullable NSArray<BFTask *> *)tasks;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:110:1: error: expected method body
- (instancetype)taskWithDelay:(int)millis;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:118:1: error: missing context for method declaration
- (instancetype)taskWithDelay:(int)millis cancellationToken:(nullable BFCancellationToken *)token;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:130:1: error: expected method body
- (instancetype)taskFromExecutor:(BFExecutor *)executor withBlock:(nullable id (^)())block;
  ^
  /Users/hodayaohana/Shantiapp-IoS2/Pods/Bolts/Bolts/Common/BFTask.h:137:1: error: unexpected '@' in program
  @property (nullable, nonatomic, strong, readonly) ResultType result;
  ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.

**Comment by Raikerian** [comment]
Can you post everything that console output after pod command? If its too long use gist or pastebin.

**Comment by RivkiGlick** [comment]
this 
Updating local specs repositories

CocoaPods 1.0.0.beta.8 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
Downloading dependencies
Using Bolts (1.7.0)
Installing QMServices (0.3.9)
Using QMServicesDevelopment (0.3.9)
Installing QuickBlox (2.7.1)
Using SVProgressHUD (2.0.3)
Using TWMessageBarManager (1.7.2)
Generating Pods project
Integrating client project
Sending stats
Sending stats

[!] Unable to read the license file `/Users/hodayaohana/Shantiapp-IoS2/Pods/LICENSE.txt` for the spec `QMServices (0.3.9)`

[!] Unable to read the license file `/Users/hodayaohana/Shantiapp-IoS2/Pods/LICENSE.txt` for the spec `QMServices (0.3.9)`

**Comment by Raikerian** [comment]
What is Xcode version you are using?

**Comment by RivkiGlick** [comment]
8.4

**Comment by Raikerian** [comment]
Please check your xcode version, not an iOS one. Open Xcode, in upper menu press Xcode -> About Xcode.

**Comment by RivkiGlick** [comment]
6.4

**Comment by Raikerian** [comment]
You are receiving those errors for Bolts framework, cause Bolts has generics that were added as a new feature with Xcode 7+.

I can suggest you to try adding `pod 'Bolts', '~> 1.5.0'` into your podfile before QMServices. AFAIK 1.5.0 version of Bolts was without generics and nullability and it should work for you.

**Comment by RivkiGlick** [comment]
this is what i get back
Updating local specs repositories

CocoaPods 1.0.0.beta.8 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
[!] Unable to satisfy the following requirements:
- `Bolts (~> 1.5.0)` required by `Podfile`
- `Bolts (= 1.7.0)` required by `Podfile.lock`

and this is my podfile;
pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'
#pod 'QMChatViewController'
pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'
pod 'Bolts', '~> 1.5.0'
pod 'QMServices'

**Comment by Raikerian** [comment]
Remove Podfile.lock file, Pods folder and .xcworkspace file. Then run `pod install` again.

**Comment by Raikerian** [comment]
@RivkiGlick any updates?

**Comment by RivkiGlick** [comment]
Im cheking

**Comment by RivkiGlick** [comment]
I get the next error: 
duplicate symbol _OBJC_CLASS_$_QBError in:
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBConnection.o)
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBError.o)
duplicate symbol _OBJC_IVAR_$_QBError._error in:
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBConnection.o)
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBError.o)
duplicate symbol _OBJC_IVAR_$_QBError._reasons in:
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBConnection.o)
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBError.o)
duplicate symbol _OBJC_METACLASS_$_QBError in:
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBConnection.o)
    /Users/hodayaohana/Shantiapp-IoS2/Pods/QuickBlox/Quickblox.framework/Quickblox(QBError.o)
ld: 552 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RivkiGlick** [comment]
do you have an answere

**Comment by Raikerian** [comment]
Seems like you have 2 copies of Quickblox iOS Framework.

**Comment by RivkiGlick** [comment]
this is my podfile: 
pod 'SVProgressHUD'
pod 'TWMessageBarManager', '~> 1.7.2'
pod 'QMChatViewController'
#pod 'QMServicesDevelopment', :git => 'https://github.com/QuickBlox/q-municate-services-ios.git', :branch => 'development'
pod 'Bolts', '~> 1.5.0'
pod 'QMServices'

**Comment by Raikerian** [comment]
Send me your sample project if you can.

**Comment by RivkiGlick** [comment]
its a problem for me its code of the coumpany
 do you have any idea?
it worked for me until yesterday

**Comment by Raikerian** [comment]
As I said:

> Seems like you have 2 copies of Quickblox iOS Framework.

Try to look for extra unexpected copies of framework in your project.

**Comment by RivkiGlick** [comment]
ok Im sending it in email

thank you

**Comment by RivkiGlick** [comment]
Download full resolution images
Available until 19 May 2016
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAUCSO83tcGEva-JedDM9W0jIT4JoATp0_4HYv0cQatlp6RMRuZ_N3vy-%2F%24%7Bf%7D%3Fo%3DAueCdb8mQ0iWJjKOhmc4gadYcvI9GRj8VyR7--xJhqn_%26v%3D1%26x%3D3%26a%3DBa42gAPg7sRRAwc1MwEA_wHIAP8L3nB7%26e%3D1463658642%26k%3D%24%7Buk%7D%26fl%3D%26r%3D4A5825CE-D542-4061-86E3-B48765218E1E-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DBB3A9F15-B61A-4A92-8F94-87FA1D40CFB1%26p%3D41%26s%3Df491v4KjrqUzmGxYJsZxFmLzeH0&uk=388DXDCHqpQ2O7_EHOhP6Q&f=Images.zip&sz=133461>Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAfQWzeRh-QqJkHcyCEOEJIASiS-bATb5Mb7cnkmvm2aefdZQ37seU4fi%2F%24%7Bf%7D%3Fo%3DAuJx0xySdsQnQ3zw4aupsxzkznyznhBead7WtqSUb-cf%26v%3D1%26x%3D3%26a%3DBRwRk9B8Of60Awc1MwEA_wHIAP8vQ440%26e%3D1463658641%26k%3D%24%7Buk%7D%26fl%3D%26r%3D38897EE5-EC8D-42C3-AF86-1F55BB2BF22F-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DBB3A9F15-B61A-4A92-8F94-87FA1D40CFB1%26p%3D41%26s%3DDM9zID8GOi-Ko4KIWaygMztDTCk&uk=9Ym4haGs4AX7Ro6QrfbcDQ&f=Shantiapp-IoS2.zip&sz=153010234>Shantiapp-IoS2.zip
153 MB


Confidentiality Agreement
Quickblox or designate employees agree that they shall treat the Shanti project between the parties, and the contents as absolutely confidential. Quickblox or designate employees shall not disclose anything
regarding this code to any other person or entity not directly affiliated
with the parties, unless legally compelled to do so, and then, only upon timely prior
notice to Shantiapp, giving it sufficient time to contest any such disclosure.


Mrs. Glick

**Comment by RivkiGlick** [comment]
did you get it?

**Comment by Raikerian** [comment]
Yes, let me check, I will investigate the problem and post update soon.

**Comment by RivkiGlick** [comment]
ok thank you

**Comment by Raikerian** [comment]
@RivkiGlick Thank you for reporting the issue. I was able to spot the error in our iOS SDK. We will push hot fix soon today and I will let you know.

**Comment by Raikerian** [comment]
@RivkiGlick we have pushed an update for both sdk and services. Just remove Pods folder, Podfile.lock file and .xcworkspace file and perform `pod install` again.

**Comment by RivkiGlick** [comment]
thank you so much it worked for me
