### ISSUE TITLE
Reload user when his name was changed

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#195]
Hi,
When a user change his name how can't his opponent to know that name was changed and load him.
Currently I load all users with theirs ids when I log in with 
`- (BFTask QB_GENERIC(NSArray QB_GENERIC(QBUUser *) *) *)getUsersWithIDs:(NSArray QB_GENERIC(NSNumber *) *)usersIDs;` 
The problem that this method only load users which is not already cached BUT all my users are cached so it doesn't reload them. 
Thanks.

**Comment by Raikerian** [comment]
Hi @mikeRozen 

We will implement such functionality in a near future (something like foreceReload flag). For now you can either clear your cache and load users again or implement your own method, that will always load users from server and cache them even though they were already cached.

**Comment by mikeRozen** [comment]
Thanks.

**Comment by ghost** [comment]
@mikeRozen  Added in v 0.4.2.
