### ISSUE TITLE
Outdated Cocoapods repository

### ISSUE THREAD

**Issue by thdvdev** [QuickBlox/q-municate-services-ios#20]
Could you update cocoapods repository please? I think it is outdated.
Thanks.

**Comment by Forsarion** [comment]
Hello!

We can't update cocoapods, until we will release next version of Quickblox SDK. Current services are not compatible with public Quickblox SDK.
Will try to make this release as soon as possible!

**Comment by thdvdev** [comment]
Thank you for your hard work. These services are great.
