### ISSUE TITLE
add user to group

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#203]
I'm trying to add user to group but I'm geting the next message: You don't have appropriate permissions to perform this operation what does it mean?

**Comment by VitaliyGuru** [comment]
Hi @RivkiGlick, Are you sure that you dialog’s owner? Cause only dialog’s owner can update group dialog. 
Please, refer to [this documentation](http://quickblox.com/developers/SimpleSample-chat_users-ios#Update_group_dialog) for additional info.

**Comment by Raikerian** [comment]
@RivkiGlick @VitaliyGuru 

Everyone, who are existent in group dialog occupants list can update group dialog. But only the owner of dialog can remove occupants from it.
You are getting this error because you are probably not in the occupants list of it.

**Comment by ghost** [comment]
@RivkiGlick  have we resolved your issue? If YES please close the issue.

**Comment by RivkiGlick** [comment]
hi 
I have this code to send message in group:
     self.dialog.sendMessage(message, completionBlock: { (error: NSError?) -> Void in
                    print("error:(error)")
                    if error == nil{
                    self.sendUserDialogNotification(self.txtMessage.text!)
                    }
                });
if I send message text i works great but if I'm trying to send message image in the same group i get the next error message:
▿ Optional<NSError>
- Some : Error Domain=com.quickblox.chat Code=-1001 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not joined to the dialog.}

**Comment by Raikerian** [comment]
See https://github.com/QuickBlox/q-municate-services-ios/issues/212
