### ISSUE TITLE
xcode crash

### ISSUE THREAD

**Issue by RivkiGlick** [QuickBlox/q-municate-services-ios#204]
hi

i added quickblox with pods and in the past week the xcode closes  automatic when it gets to  a brake point

**Comment by ghost** [comment]
Hi
Could you please provide test project with reproducible crash?
Are you sure that the source of this issue is QuickBlox SDK?

**Comment by RivkiGlick** [comment]
ן don't know but in a project the dosen't have quickblox in pods it dosen't appen

**Comment by RivkiGlick** [comment]
I send the project in email
thank you

**Comment by ghost** [comment]
@RivkiGlick , Have you already sent the project you were talking about? Cause there are no messages with project.

**Comment by RivkiGlick** [comment]
yes i did in email

**Comment by RivkiGlick** [comment]
Download full resolution images
Available until 7 Jun 2016
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAR1auj-2ABtLL63mWZPh_Mn3o5X5AfA-N1kyj0WPYTUXr7Q78BVMOq4I%2F%24%7Bf%7D%3Fo%3DAii2JGi5FMwdVJvpOu6oLfwXDsHpv5eaofGX5Bn37CeJ%26v%3D1%26x%3D3%26a%3DBb7au376BqiGA5ieMwEA_wHIAP9TAVM5%26e%3D1465280107%26k%3D%24%7Buk%7D%26fl%3D%26r%3DEB0F888E-AE74-4442-8898-633220E1B73F-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DBB3A9F15-B61A-4A92-8F94-87FA1D40CFB1%26p%3D41%26s%3DN5d1H0fTrknTYtjk235Am1CvPWc&uk=2qb7nMbdchaWPQKUG5v21A&f=Images.zip&sz=133461>Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FATT7ZurJciYFZZoqRjrtCfN8eL8AAdIM6Yy3XL0cpFwZt8BdFgkxZ0Xp%2F%24%7Bf%7D%3Fo%3DAgjUzNds5Q1spfJfMHSQpwL9db8S8C2VGo7aDfwBexjw%26v%3D1%26x%3D3%26a%3DBdmAylVlxmSoA5ieMwEA_wHIAP8X6BJC%26e%3D1465280107%26k%3D%24%7Buk%7D%26fl%3D%26r%3D6D2AB29F-4466-409D-A4A5-EED66742422B-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DBB3A9F15-B61A-4A92-8F94-87FA1D40CFB1%26p%3D41%26s%3DqsZ1_bbuhwLRPy_LxhRG3KArsfM&uk=ueyDwKbQS3JB6FEdOvFvtQ&f=Shantiapp-IoS%202.zip&sz=176966359>Shantiapp-IoS 2.zip
177 MB

Mrs. Glick

**Comment by RivkiGlick** [comment]
did you get it?
can you help me?

**Comment by ghost** [comment]
Hi @RivkiGlick , I will investigate the problem in your project and answer ASAP.

**Comment by RivkiGlick** [comment]
ok thank you

**Comment by ghost** [comment]
@RivkiGlick , unfortunately we don't support projects with swift v < 2.0.
You can update your project to the latest swift syntax and resend it.

**Comment by Raikerian** [comment]
@RivkiGlick any updates on this?

**Comment by Raikerian** [comment]
We haven't heard any updates from you on this issue. If you are still experiencing it, just reopen it. If you are having any other troubles, feel free to create a separate issue.

**Comment by RivkiGlick** [comment]
thank you but after me updating the xcode its working greate
