### ISSUE TITLE
Push notification not arriving, this is the  error log : APNS (Apple Push) Delivered: 0, failed: 0 

### ISSUE THREAD

**Issue by Arun1k** [QuickBlox/q-municate-services-ios#211]
I am trying to receive a push  notification from QuickBlox dashboard. However I am getting an error the details of which are below:

detailed error log : {"notification":{"aps":{"alert":"Helloooo","sound":"default"}},"log":[{"device_token":"fc5f3c0b090232d39aa8b75e0c3edc41e4a6f6596baff8f0db890c5ad220bf3d","created_at":"2016-05-20T12:07:27Z","delivered_at":null,"failed_at":null,"error_code":null,"error_description":null}]}

I'm Using SDK Ver.  2.7.2

I have checked the APN certificate using APN tester app and I'm able to receive push notification.

When I try to send notification using dashboard they don't arrive. Following is the message I receive: 
APNS (Apple Push) Delivered: 0, failed: 0 

Also, when I check the dashboard I see that  the notification has been successfully added to the queue.

"Success
Apns channel. Notification has been successfully added to queue"

Our Account ID is: 51726

Please provide assistance regarding this issue.
Thank You

**Comment by ghost** [comment]
@Arun1k  Hello, yesterday our server team uploaded new updates. Looks like this updates resolved issues with push notifications. Please try now.

**Comment by Arun1k** [comment]
Ok thanks @VitaliyGuru 
Will I have to update the SDK or its just on server end.

**Comment by ghost** [comment]
@Arun1k  It's just on server end.

**Comment by Arun1k** [comment]
Ok thanks @VitaliyGuru I will check and update you soon thanks again

**Comment by Arun1k** [comment]
Still the same issue APNS (Apple Push) Delivered: 0, failed: 0 
one thing more let me tell you that also, I am not using pod file just drag droping the framework as given instruction to official site. Is that causing this error ?

**Comment by ghost** [comment]
@Arun1k  Any updates on this? If you are still having this issue, please give me your application ID and your endpoints from the admin panel. 

>  I am not using pod file just drag droping the framework as given instruction to official site. Is that causing this error ?

It doesn't matter which way you have chosen for adding the framework.

**Comment by Arun1k** [comment]
Our Account ID is: 51726 this is the account id and still facing the issue

**Comment by ghost** [comment]
@Arun1k , do you use Shared Cloud hosting?

**Comment by Arun1k** [comment]
what I did is just added the framework into app and configure that in my app and after that created a user and what I have to do with notification I done means send device token to quickBlox dashboard and after that when user registered to quickBlox just send a notification to that user using dashboard.
This is what I have done. but i don't received any notification

**Comment by Arun1k** [comment]
Any news ?

**Comment by ghost** [comment]
@Arun1k We've got this from our server team:
`[2016-06-13 17:09:21] [ERROR] 40937_d is banned due to OpenSSL::SSL::SSLError, SSL_connect returned=1 errno=0 state=SSLv3 read server session ticket A: sslv3 alert certificate unknown
`
The server team recommend to check certificates.

**Comment by Arun1k** [comment]
Ok i will provide you by tomorrow.

**Comment by ghost** [comment]
@Arun1k Do you have any updates?

**Comment by Arun1k** [comment]
No but I can give you the certificate APN if you want and on which notification is arriving tested by me

**Comment by Arun1k** [comment]
@VitaliyGuru  please assist me after successfully implementation i have to buy plans also for quick blox. Still waiting for your response.

**Comment by Raikerian** [comment]
Hi @Arun1k 

Were you able to accomplish this at the end?

**Comment by Arun1k** [comment]
Yes sir ,  I bought your paid subscription and then its working fine.
Thanks

On Wed, Dec 14, 2016 at 8:19 PM, Vitaliy Gorbachov <notifications@github.com

**Comment by Raikerian** [comment]
Thanks for the response, closing due to issue being resolved.
