### ISSUE TITLE
Unit Testing Failed In Swift Project Which Used Manual Installation

### ISSUE THREAD

**Issue by yaodong-li** [QuickBlox/q-municate-services-ios#218]
**Environment details**
All latest version

**Description**
My project is a swift one. I imported qmservices manually. The problem is: I cannot add unit test classes. Every time I added a new test case class, the error will come:

"Failed to import QMServices.h"

I think it's because qmservices is in subproject, not my main project. I tried writing some test cases for my some objc classes in my main project and everything works fine. 

How should I config my test target for this case? I tried Changing header search path and frame search path for the unit test target with no luck.

Thanks a lot for your help!

**Comment by yaodong-li** [comment]
Currently I found a solution. I followed your readme manual and edited "header search path" and "framework search path" for my unit test target. Everything is fine for now except webrtc because I imported webrtc in bridging header too. I think I can try to use webrtc pod as dynamic framework instead thus no need to import it in bridging header. @Raikerian , am I in the right direction?

**Comment by ghost** [comment]
@fans3210 We still support iOS7. So you can't  use webrtc pod as dynamic framework. 
If you have any questions or troubles please create separate issue.

**Comment by yaodong-li** [comment]
Hi. After reading the doc, webrtc can be used as dynamic framework already since version 2.4 right?
