### ISSUE TITLE
Delete message from all users

### ISSUE THREAD

**Issue by ab-rdarts** [QuickBlox/q-municate-services-ios#223]
How can I delete own message from all users?
As I understand current user can delete own message by calling deleteMessagesWithIDs. It works fine for current user, but all other users still see this message event I forAllUsers: as YES. Also other users has no any notifications about message was deleted.

**Environment details**
_iOS version, Quickblox iOS SDK version, QMServices version_
Any iOS version, QuickBlox 2.7.3, QMServices 0.4.2

**Did this work before?**
No

**Expected behavior**
All users was notified about deleted message and updates its history

**Actual behavior**
Other users are not notified about message was deleted

**Comment by ghost** [comment]
@ab-rdarts  There is no such functionality for now
