### ISSUE TITLE
Manual Installation in swift 3, xcode 8 beta

### ISSUE THREAD

**Issue by yaodong-li** [QuickBlox/q-municate-services-ios#227]
I've post an issue two months ago. (Please refer #177). Thanks for your help and it was resolved.

Now issues come again in xcode 8 beta with swift 3. Attached are the two sample projects.

. The first one is what I made before and it worked well in xcode 7 with swift 2.2. But crash in xcode 8 beta with swift 3.

https://www.dropbox.com/s/js0jeacs2f860jz/JsqumunicateTest_22Jun.zip?dl=0

. The second one is what I just created by following the "manual installation of QMServices". I also faced crash issue in this newly created project.

https://www.dropbox.com/s/gen91w3x8c0nbp4/ConnectedLife_22Jun.zip?dl=0

Is there any suggestion? I have to use manual installation because I have to use 'QMServices' as framework. Thanks a lot!

**Comment by Raikerian** [comment]
Hi,

We haven't tested our project with Swift 3 yet.
Can you provide the crash logs? Also please add exception breakpoints, to see which line of code is causing the problem for you.

**Comment by Raikerian** [comment]
We have recently updated our sample-chat-swift with swift 3 syntaxes, supporting latest Xcode 8. Please take a look here: https://github.com/QuickBlox/quickblox-ios-sdk

Closing due to lack of information and feedback from reporter.
