### ISSUE TITLE
Error After installation of QMServices 

### ISSUE THREAD

**Issue by Dhiru-Dev** [QuickBlox/q-municate-services-ios#228]
i am installing QMService  into my project.

`pod 'QMServices'`

installation Error Logs

`pod install`

```
Re-creating CocoaPods due to major version update.
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.7.0)
Installing QMServices (0.4.2)
Installing QuickBlox (2.7.3)

[!] Error installing QuickBlox
[!] /usr/bin/curl -f -L -o /var/folders/20/bsnm0hgn7mg2v6fzr_wlkxv00000gn/T/d20160627-2029-z6agl8/file.zip http://sdk.quickblox.com/ios/iOS-QuickBlox-SDK-2.7.3.zip --create-dirs --netrc

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    259      0 --:--:-- --:--:-- --:--:--   259
 81 14.3M   81 11.6M    0     0  45290      0  0:05:31  0:04:30  0:01:01     0curl: (56) SSLRead() return error -9806


```

When i try to Build ,
The Error is  
`Type arguments cannot be applied to non-parameterized class 'BFTask'` 

![screen shot 2016-06-27 at 11 24 17 am](https://cloud.githubusercontent.com/assets/16178823/16370138/dc5168f4-3c5a-11e6-8e3d-5d0990d39ad4.png)

plz help me out , thanks in advance.

**Comment by ghost** [comment]
Hi @DhiruServer 
try to remove from your podfile Bolts framework and reinstall pods.
This issue caused by duplicated Bolts framework in your project.

**Comment by Dhiru-Dev** [comment]
i had installed QMServices using  below pod .

`pod 'QMServices'`

The Bolt Framework was downloaded  with QMServices , I had done manual integration with Facebook .
 This was the Conflict , but i am interested to know ,
 will  new New Bolt framework  work for me ?
 with Facebook SDK

**Comment by ghost** [comment]
As Bolts framework is dependency for QMServices there is no need to add it to podfile. Also if you are still facing with this issue try to add facebook SDK via pods too.

**Comment by ghost** [comment]
@DhiruServer Have you resolved this issue?

**Comment by Dhiru-Dev** [comment]
nope ,,,,, Still getting same Error :(

**Comment by ghost** [comment]
Show me please your podfile

**Comment by ghost** [comment]
And are there any frameworks added manually? 
Check that you haven't duplicated Bolts framework.

**Comment by ghost** [comment]
@DhiruServer  Any updates?

**Comment by Dhiru-Dev** [comment]
@VitaliyGuru First of all  Sorry for late reply..... But Yes i did it ,,,,, there was lots  of conflict in my project due to  manual Installation of SDK , 

Thanks a lot !! :)

when i was removing the Bolt.Framework the FBSDK was giving lots of Error , 
1 . i have installed Bolt Using POD and than removed framework from our project.
2. Than set Non-moduler includes framework to YES than, Build.....   

This was  the solution for me ....

![screen shot 2016-07-12 at 10 52 10 am](https://cloud.githubusercontent.com/assets/16178823/16758817/968ec6e4-4831-11e6-961d-17833489cfbd.png)
