### ISSUE TITLE
CBDialog.m complile error 

### ISSUE THREAD

**Issue by gizmeondev** [QuickBlox/q-municate-services-ios#229]
Hi 

pod install code as follows

pod 'QMChatViewController'
pod 'QMServices'
pod 'SDWebImage'
pod 'GoogleMaps'
pod 'Firebase/Messaging'
pod 'AFNetworking'
pod 'FBSDKShareKit'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

i am getting a error CBDialog.m
 dialog.roomJID = self.roomJID;   -- Assigment to readonly property

Thanks
Nicky Patson

**Comment by ghost** [comment]
@gizmeondev  Do you set somewhere in your code  `roomJID` explicitly?
If Yes, then there is no need to set it now, our SDK will manage this field itself. Just remove all setters for roomJID from your app and you are good to go.

**Comment by gizmeondev** [comment]
its there in the pod SDK file , I didn't change anything 

Thanks

**Comment by gizmeondev** [comment]
Could you please advice us

**Comment by ghost** [comment]
Hi @gizmeondev, please provide version of SDK

**Comment by ghost** [comment]
@gizmeondev, please check QBChatDialog interface https://github.com/QuickBlox/quickblox-ios-sdk/blob/master/Framework/Quickblox.framework/Versions/A/Headers/QBChatDialog.h

**Comment by gizmeondev** [comment]
Installing QMChatViewController (0.3.8)
Installing QMServices (0.2.5)
Installing QuickBlox (2.7.3)
Installing SDWebImage (3.7.2)
Installing TTTAttributedLabel (1.13.4)

**Comment by gizmeondev** [comment]
Can i comment those lines 

self.tDialog.roomJID

**Comment by ghost** [comment]
@gizmeondev  Try to update QMServices to the latest

**Comment by gizmeondev** [comment]
pod 'QMChatViewController'
pod 'QMServices'
pod 'SDWebImage'
pod 'GoogleMaps'
pod 'Firebase/Messaging'
pod 'AFNetworking'
pod 'FBSDKCoreKit'

**Comment by gizmeondev** [comment]
this is my pod file

**Comment by gizmeondev** [comment]
Installing QMChatViewController (0.3.8)
Installing QMServices (0.2.5)
Installing QuickBlox (2.7.3)

is this is the latest one , Please confirm i am getting compilation error

**Comment by ghost** [comment]
Try to edit podfile with this changes:
pod 'QMServices', '~> 0.4'

**Comment by gizmeondev** [comment]
Thanks broo , will check keep you posted the status!!

**Comment by gizmeondev** [comment]
Worked like a charm !!

**Comment by ghost** [comment]
@gizmeondev  It's good to hear that it is resolved
