### ISSUE TITLE
You are not connected to chat Error.

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#231]
Hello,

In the last days I receive this "Error NSLocalizedRecoverySuggestion=You are not connected to chat" when a new user try to SIGN UP. (It never happened ).
I use the following Method: "`[[[QBServiceManager instance] authService] signUpAndLoginWithUser:user completion:^(QBResponse *response, QBUUser *userProfile)`".
The user does Sign up and does login successfully.
I check the session before sending new message and it valid.
When I do send Message via : `"[[QBServiceManager instance].chatService sendMessage:qBmessage toDialog:_dialog saveToHistory:YES saveToStorage:YES completion:^(NSError * _Nullable error)`"
It Failed: "`Error Domain=com.quickblox.chat Code=-1002 "(null)" UserInfo={NSLocalizedRecoverySuggestion=You are not connected to chat.}`"

When the user restart the App and launch it again all work as expected: via `[[QBServiceManager instance] logInWithUser:user completion:^(BOOL success, NSString *errorMessage)`

[logs.txt](https://github.com/QuickBlox/q-municate-services-ios/files/341271/logs.txt)

Please help.

**Comment by ghost** [comment]
@mikeRozen  You are getting this error because there is no connection to chat in the method below:
`[[[QBServiceManager instance] authService] signUpAndLoginWithUser:user completion:^(QBResponse *response, QBUUser *userProfile)`

In completion block you should connect to chat using e.g `[ServicesManager.instance.chatService connectWithCompletionBlock:nil];`

 `[[QBServiceManager instance] logInWithUser:user completion:^(BOOL success, NSString *errorMessage)` In this method we connect to chat after login so you didn't get an error.

**Comment by ghost** [comment]
or, if you are using QMServices in AppDelegate you can use this method:

```
- (void)applicationWillEnterForeground:(UIApplication *)application {
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.

    // Login to QuickBlox Chat
    //
    [ServicesManager.instance.chatService connectWithCompletionBlock:nil];
}
```

**Comment by mikeRozen** [comment]
**VitaliyGuru** 
As the name of the method says "**signUpAndLoginWithUser**", it make sign up and than login. (I didn't write this method.)

```
- (QBRequest *)signUpAndLoginWithUser:(QBUUser *)user completion:(void(^)(QBResponse *response, QBUUser *userProfile))completion {

    __weak __typeof(self)weakSelf = self;

    //1. Signup
    QBRequest *request = [QBRequest signUp:user successBlock:^(QBResponse *response, QBUUser *newUser) {
        //2. Login
        [weakSelf logInWithUser:user completion:completion];

    } errorBlock:^(QBResponse *response) {

        [weakSelf.serviceManager handleErrorResponse:response];

        if (completion) {
            completion(response, nil);
        }
    }];

    return request;
}

```

it should and does login after successful sign up.(It always worked for me).As you say u do make connection on  `logInWithUser` .(and indeed after second launch the `logInWithUser` does make the connection as it should do on the first time after sign up).
I don't mind to add `[ServicesManager.instance.chatService connectWithCompletionBlock:nil];`
Thanks.

**Comment by mikeRozen** [comment]
**VitaliyGuru**
It solved the problem.`logInWithUser:`\- this method with same  name is defined in different classes but the the implementation is different the one which triggered from `signUpAndLoginWithUser` doesn't make connection. (I would expect it to do).
Thanks again.

**Comment by ghost** [comment]
@mikeRozen  So I can close this issue?

**Comment by mikeRozen** [comment]
Yes.

**Comment by ghost** [comment]
Just FYI auth service responds only for REST API  auth.
