### ISSUE TITLE
Can some one suggest me how to Copy Image and attachment from Chat in iOS . And make them paste on other chat window . 

### ISSUE THREAD

**Issue by ajayrigaps** [QuickBlox/q-municate-services-ios#234]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-services-ios/issues)_

**Environment details**
_iOS version, Quickblox iOS SDK version, QMServices version_

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by ghost** [comment]
@ajayrigaps  Take a look at our chat sample in the development branch.
There you can find implementation for image copy and paste.
