### ISSUE TITLE
How to remove the reconnect and attempt to reconnect notification banners.

### ISSUE THREAD

**Issue by ajay2c9** [QuickBlox/q-municate-services-ios#246]
when the network is off i am getting this type of log and one banner and below type of view is displaying on the top of the view . it is not a custom design. Below is the image

![screen shot 2016-08-01 at 12 15 05 pm](https://cloud.githubusercontent.com/assets/9112899/17286150/300d516a-57e5-11e6-9464-9d01cd665b55.png)

This is the log when there is no internet connection
Socket reconnect delay: 1
 [ChatService] Did disconnect with error: Error Domain=kCFStreamErrorDomainNetDB Code=8 "nodename nor servname provided, or not known" UserInfo={NSLocalizedDescription=nodename nor servname provided, or not known}

Socket reconnect delay: 0.5
 [ChatService] Did disconnect with error: Error Domain=NSPOSIXErrorDomain Code=57 "Socket is not connected"
[ChatService] Did disconnect with error: Error Domain=kCFStreamErrorDomainNetDB Code=8 "nodename nor servname provided, or not known" UserInfo={NSLocalizedDescription=nodename nor servname provided, or not known}
 Socket reconnect delay: 1
[ChatService] Did disconnect with error: Error Domain=kCFStreamErrorDomainNetDB Code=8 "nodename nor servname provided, or not known" UserInfo={NSLocalizedDescription=nodename nor servname provided, or not known}

and when the internet connection is low this type of indication (banners) is displaying on the top of the Viewcontrollers.

**Comment by Raikerian** [comment]
Hi @ajay2c9 

We do not have any kind of custom view that will display that notification. QMServices is a pure wrapper over our SDK (which does not contains any UI). So unfortunately this banner is represented by your own custom UI. Not sure what do you want us to do with that.

**Comment by ajay2c9** [comment]
Thank you for reply.Can you suggest me at which method in Chat services this log  presents. 
Socket reconnect delay: 1
[ChatService] Did disconnect with error: Error Domain=kCFStreamErrorDomainNetDB Code=8 "nodename nor servname provided, or not known" UserInfo={NSLocalizedDescription=nodename nor servname provided, or not known}

**Comment by Raikerian** [comment]
You are getting this error probably because of bad internet connection. Any extended logs on this?
