### ISSUE TITLE
QMAuthService is missing loginWithTwitter

### ISSUE THREAD

**Issue by dpfaffenbauer** [QuickBlox/q-municate-services-ios#247]
Hey,

i just tried to implement Twitter Social Auth, but the AuthService Class is missing a loginWithTwitter method, which results in that the isAuthorized variable is not set to true and, for example, the allDialogsWithPageLimit method will always return null as result.

Can you please add this method?

Regards
Dominik

**Comment by ghost** [comment]
Hi @dpfaffenbauer. loginWithTwitter will be added in the next QMServices release.

**Comment by dpfaffenbauer** [comment]
Great, thanks. Can you tell me when the next version is going to be released?

**Comment by ghost** [comment]
Hi @dpfaffenbauer , [login with twitter](https://github.com/QuickBlox/q-municate-services-ios/pull/248)
