### ISSUE TITLE
Can not run QMServices 0.4.4

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#252]
<img width="1381" alt="screen shot 2016-08-17 at 9 48 34 am" src="https://cloud.githubusercontent.com/assets/1511264/17769976/8cebba4c-6565-11e6-878e-5b80fd49b7b0.png">
Please check the screenshot.

**Comment by ghost** [comment]
Hi @tranngoclinh88 , Could you please provide your podfile?

**Comment by tranngoclinh88** [comment]
platform :ios, '8.0'
inhibit_all_warnings!

pod 'QuickBlox'
pod 'Quickblox-WebRTC', '~> 2.1'
pod 'QMChatViewController', '~> 0.3'
pod 'QMServices'

![screen shot 2016-08-22 at 5 52 20 pm](https://cloud.githubusercontent.com/assets/1511264/17852372/3eda6824-6891-11e6-84d6-0231c56bd671.png)

**Comment by ghost** [comment]
@tranngoclinh88  I have created the new project with podfile like yours and I haven't got this error. Could you please attach the test project here?

**Comment by ghost** [comment]
@tranngoclinh88 
Any updates?
