### ISSUE TITLE
Is there any possibility to block user?

### ISSUE THREAD

**Issue by ab-rdarts** [QuickBlox/q-municate-services-ios#259]
Is it possible to use QBPrivacyList with QMServices/QMChatViewController? I'm trying to implement blocking user based on it, but it doesn't work.
Privacy list is stored and retrieved from server. It seems to work. But blocked user still can send messages.

QMChatViewController (0.3.10)
QMServices (0.4.4)
QuickBlox (2.7.6)
iOS 9.3.5

**Expected behavior**
Blocked user will not able to send messages.

**Actual behavior**
Blocked user is still able to send messages even if he's blocked

**Comment by ghost** [comment]
@ab-rdarts Hello. Could you please provide the code snippet used for blocking from your project?

**Comment by ghost** [comment]
@ab-rdarts If you have any updates just reopen this issue.
