### ISSUE TITLE
Cannot install the Pod: Error 

### ISSUE THREAD

**Issue by fstephany** [QuickBlox/q-municate-services-ios#26]
When trying to install from CocoaPods:

```
$ pod install
...
Installing QMServices (0.2.2)
...
[!] The 'Pods-app' target has transitive dependencies that include static binaries
```

This is exactly the same issue as https://github.com/QuickBlox/QMChatViewController-ios/issues/5.

**Comment by Raikerian** [comment]
Hi!

We are aware of this issue, unfortunately we don't have Quickblox built as a dynamic framework. Mainly because we still need to support iOS 7.
So, removing option 'use_frameworks!' from your Podfile will fix described issue.

We will try to find out more appropriate solution in nearest future.

**Comment by loksland** [comment]
Would you be able to give any indication when the dynamic framework solution you mention would be implemented? I have existing swift-based pods in the project that require the 'use_frameworks!' flag. 
Is there a work around I can implement in the meantime?
Thanks.

**Comment by samuMukkala** [comment]
I'm facing the same issue as Ioksland. Would appreciate a work around for this also.

**Comment by obernal** [comment]
+1 I have the exact same issue and I can't work around it because my app relies heavily on swift libraries. Your swift user base must be growing at a much faster rate than your iOS 7 users. Do you have plans at all to release a version addressing this problem? Removing `use_frameworks!` is not an option

**Comment by UtkuDalmaz** [comment]
Please FIX this !!!!!!!!

**Comment by ghost** [comment]
We're going to refuse iOS 7 support this summer.
