### ISSUE TITLE
Not working in Xcode 7.3 - swift project - pod installation

### ISSUE THREAD

**Issue by phiren** [QuickBlox/q-municate-services-ios#272]
Hi,

I have used Xcode 7.3 and added QMServices using pod as below

```
pod 'QMServices', '~> 0.4'
```

The project is swift - uses most of swift files and few objective c files.
So while importing QMServices in bridging header, it gives error that file not found.

  `
 #import <QMServices.h>
`

Also tried with importing below statement but no luck
# import "QMServices.h"

Not sure what could be the problem.

**Comment by sushmithaGope** [comment]
Even I'm facing same issue with pod 'QMServices'. Can someone help us.

**Comment by phiren** [comment]
I have added header search path from private directory to solve this issue

**Comment by sushmithaGope** [comment]
Hi,
Actually, I'm able to run the project with out errors in New Xcode Project 
by using below steps

$ git submodule add https://github.com/QuickBlox/q-municate-services-ios.git 
Vendor/QMServices
$ git commit -m "Added QMServices submodule"
also in pod file I used pod 'QMServices'
So, it is working fine.

But when I use same steps in existing project, it is not working.
I’m getting error at this line
 #import "QMServices.h" QMServices file not found.

I also tried installing QMservices once by only using pod ‘QMServices’ and once only by $ git submodule add https://github.com/QuickBlox/q-municate-services-ios.git 
Vendor/QMServices

Either I’m getting QMServices file not found OR Redeclaration/duplicate errors in many files (like QMDBStorage.h)

Can you please help me to solve this issue.

**Comment by Raikerian** [comment]
Hi @phiren and @sushmithaGope 

@phiren If you are still having any other troubles, please let us know by creating a separate issue.
@sushmithaGope I have answered you in your issue, lets continue it there.

**Comment by phiren** [comment]
See my initial comment, you have to add header search path for QMservices.
There is some prb with the pod, it does not add header search path for
QMservices. Also those headers not in public folder , only in private
folder. So give path to private folder. If you have other working pods too,
then see how header search path was added for those library, it just not
add path of QMServices, not sure what's wrong with the pod.

Thanks
