### ISSUE TITLE
[NSURL initFileURLWithPath:]: nil string parameter

### ISSUE THREAD

**Issue by sushmithaGope** [QuickBlox/q-municate-services-ios#273]
I have checked existing issues, but I couldn't resolve this.
I'm using Cocoa pods QMServices (0.4.3). I have used -ObjC flag in Other Linker Flags
App is getting crashed **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[NSURL initFileURLWithPath:]: nil string parameter'.
Please help me to solve this issue.

My Podfile is

platform :ios, "8.0"
use_frameworks!

target ‘QuickBloxChat’ do
pod 'QMServices'
pod 'QuickBlox'
pod 'QMChatViewController'
pod 'SVProgressHUD', '~> 1.1.3'
end

**Comment by Raikerian** [comment]
Hi,

Can you screenshot your other linker flags please.

**Comment by ghost** [comment]
@sushmithaGope , any updates?

**Comment by sushmithaGope** [comment]
Hi Vitaliy,

I'm using Swift. I can able to solve this issue when i updated pod (using
pod update) with new pod QMServices version, I think issues has been
solved. And thanks a lot for your reply.

Regards,
Sushmitha

**Comment by ghost** [comment]
@sushmithaGope I'm glad to hear that you resolved this issue!
