### ISSUE TITLE
how to add QMServices classes in Bridging_Header_h when i installed  'QMServices' with pods.

### ISSUE THREAD

**Issue by swetaagicent** [QuickBlox/q-municate-services-ios#274]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-services-ios/issues)_

**Environment details**
_iOS version, Quickblox iOS SDK version, QMServices version_

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

Please take a look on our swift chat sample [here](https://github.com/QuickBlox/quickblox-ios-sdk).

**Comment by swetaagicent** [comment]
thnkx,but now m getting error in QMChatViewController..i.e use of undeclared type QMChatViewController..my  bridging header file is 

@import UIKit;
@import Foundation;
@import SystemConfiguration;
@import MobileCoreServices;
@import Quickblox;
@import QMServices;

#import "QMMessageNotificationManager.h"
#import "MPGNotification.h"
#import "UIImage+fixOrientation.h"
#import "SearchEmojiOnString/NSString+EMOEmoji.h"

but now i am stuck how to use QMChatViewController

**Comment by Raikerian** [comment]
Show your podfile please.

**Comment by swetaagicent** [comment]
thanku now i fix it
