### ISSUE TITLE
Bolts/Bolts.h not found, when i installed qmservices manually

### ISSUE THREAD

**Issue by swetaagicent** [QuickBlox/q-municate-services-ios#275]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-services-ios/issues)_

**Environment details**
_iOS version, Quickblox iOS SDK version, QMServices version_

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Raikerian** [comment]
Hi,

You need to install [Bolts framework](https://github.com/BoltsFramework/Bolts-ObjC), cause it is not installing automatically using our manual installation guide.
