### ISSUE TITLE
Able to integrate QuickBlox and QMServices in new xcode project but not in existing project.

### ISSUE THREAD

**Issue by sushmithaGope** [QuickBlox/q-municate-services-ios#276]
Hi,
Actually, I'm able to run the project with out errors in New Xcode Project 
by using below steps

$ git submodule add https://github.com/QuickBlox/q-municate-services-ios.git 
Vendor/QMServices
$ git commit -m "Added QMServices submodule"
also in pod file I used pod 'QMServices'
So, it is working fine.

But when I use same steps in existing project, it is not working.
I’m getting error at this line
 #import "QMServices.h" QMServices file not found.

I also tried installing QMservices once by only using pod ‘QMServices’ and once only by $ git submodule add https://github.com/QuickBlox/q-municate-services-ios.git 
Vendor/QMServices

Either I’m getting QMServices file not found OR Redeclaration/duplicate errors in many files (like QMDBStorage.h)

Can you please help me to solve this issue.

**Comment by Raikerian** [comment]
Hi,

Is your project written in swift or objective-c"?
Try removing QMServices completely from your project and install with pods one more time.

**Comment by sushmithaGope** [comment]
I'm using Swift. I can able to solve this issue when i updated pod (using pod update) with new pod QMServices version, I think issues has been solved. Thanks a lot.

**Comment by Raikerian** [comment]
Glad to hear you were able to fix it. I can also suggest you to check our swift chat sample [here](https://github.com/QuickBlox/quickblox-ios-sdk) (it is still swift 2.2 though, we are currently working on updating it into 3.0).

If you are still having any other troubles, please let us know by creating a separate issue.

**Comment by sushmithaGope** [comment]
Sure, I have seen your sample, that was really great. Thanks so much :)

On Mon, Oct 24, 2016 at 3:20 PM, Vitaliy Gorbachov <notifications@github.com

**Comment by sushmithaGope** [comment]
Hi Vitaliy,

I'm using Swift. I can able to solve this issue when i updated pod (using
pod update) with new pod QMServices version, I think issues has been
solved. And thanks a lot for your reply.

Regards,
Sushmitha

On Mon, Oct 24, 2016 at 3:07 PM, Vitaliy Gorbachov <notifications@github.com
