### ISSUE TITLE
QMBaseService.h warning

### ISSUE THREAD

**Issue by UtkuDalmaz** [QuickBlox/q-municate-services-ios#278]
I am having this warning

![screen shot 2016-10-22 at 13 28 53](https://cloud.githubusercontent.com/assets/2130592/19618722/a40aaa2a-985b-11e6-9b5c-9966486fd46f.png)

Any thing to do ?

**Comment by Raikerian** [comment]
Hi,

You can ignore this warning for now or change `QB_NULLABLE` for `QB_NONNULL` to make it gone. Will be fixed in next version.

**Comment by Raikerian** [comment]
This was fixed in 0.4.5.
