### ISSUE TITLE
Cannot point cocoapods pod to the forked repository 

### ISSUE THREAD

**Issue by icarasiaofficial** [QuickBlox/q-municate-services-ios#282]
**Environment details**
*QMServices latest version*

**Expected behavior**
Should be able to fork and point the pod in podfile to the forked repository.

pod 'QMServices’, :git => 'https://github.com/*username*/q-municate-services-ios.git'

**Actual behavior**
After forking and pointing the pod to the forked repository, it produces the following error

[!] Unable to find a specification for 'QMServices'.

**Steps to reproduce the behavior**
1- For a repository
2- Point the pod to forked repository

**Comment by ghost** [comment]
@icarasiaofficial , Hello.
You should modify your podfile with:
`pod 'QMServicesDevelopment', :git => 'https://github.com/*username*/q-municate-services-ios.git'`

**Comment by icarasiaofficial** [comment]
Thanks , after that this issue has been solved.
