### ISSUE TITLE
removeDelegate method try to add delegate

### ISSUE THREAD

**Issue by ahmetws** [QuickBlox/q-municate-services-ios#286]
in QMAuthService.m in remove delegate file:

- (void)removeDelegate:(id <QMAuthServiceDelegate>)delegate {
    
    [self.multicastDelegate addDelegate:delegate];
}

in QMChatService.m file this method looks like:

- (void)removeDelegate:(id<QMChatServiceDelegate, QMChatConnectionDelegate>)delegate {
    
    [self.multicastDelegate removeDelegate:delegate];
}

I guess there is something wrong with auth service file.

**Comment by ghost** [comment]
@ayalcinkaya Thanks. Fixed.
