### ISSUE TITLE
Forking repository and pointing the pod to new repository generates error 'Quickblox/Quickblox.h' file not found

### ISSUE THREAD

**Issue by icarasiaofficial** [QuickBlox/q-municate-services-ios#288]
**Environment details**
*iOS version 8, Quickblox iOS SDK version 2.8.0.1 , QMServicesDevelopment version 0.4.5

**Did this work before?**
No

**Expected behavior**
When forking q-municate-services-ios and pointing to pod like
 pod 'QMServicesDevelopment’, :git => ‘https://github.com/icarasiaofficial/q-municate-services-ios.git’
app should work.

**Actual behavior**
When forking q-municate-services-ios and pointing the pod to new repository like
 pod 'QMServicesDevelopment’, :git => ‘https://github.com/icarasiaofficial/q-municate-services-ios.git’
following error comes up:
Pods/Target Support Files/QMServicesDevelopment/QMServicesDevelopment-prefix.pch:5:9: 'Quickblox/Quickblox.h' file not found

Although the QuickBlox pod is also added like: 
pod 'QuickBlox’, ‘2.8.0.1’

**Steps to reproduce the behavior**
1-  For the q-municate-services-ios repository
2- Point the pod to the forked repository as shown in "Actual behavior" section

**Comment by Raikerian** [comment]
Hi,

Unfortunately information you have given is not enough.
If you are still having this issue some test project with it would be really helpful to see.

**Comment by ghost** [comment]
@icarasiaofficial, Hello. Do you have any updates related to this issue?

**Comment by icarasiaofficial** [comment]
Hi,
After investigating we found out that "QMServicesDevelopment" was not able to find "QuickBlox" pod path. So removing "QuickBlox" from main project pod file and adding it as a dependency in forked "QMServicesDevelopment" podspec did the trick. 

**## The current sturcture looks like this:**

**Project Pod File:**
pod 'QMServicesDevelopment’, :git => ’https://github.com/icarasiaofficial/q-municate-services-ios.git’

**Forked "QMServicesDevelopment" repository**
 s.dependency "Bolts",  '>= 1.5.0'
 s.dependency "QuickBlox", ">= 2.6.5"

https://github.com/icarasiaofficial/q-municate-services-ios/blob/master/QMServicesDevelopment.podspec
