### ISSUE TITLE
Doubt about multiple and simultaneous update to same entity

### ISSUE THREAD

**Issue by nissivm** [QuickBlox/q-municate-services-ios#291]
Hello,

I'm using QuickBlox in two projects for clients and I'm really enjoying it =]

But I have a doubt: 
What happens if, for example, I start updating a QBChatDialog and, 0.5 seconds later, another person starts updating same dialog, with different changes. Which changes will prevail? How is version control in QuickBlox servers, how version conflicts are solved?

My platform is iOS and I'm using Swift

Thank you!

**Comment by Raikerian** [comment]
Hi,

There are actually not that much changes possible to do. You can now update chat name, photo and pull/push occupants
As of chat name and photo fields, it is working as simple as the newest change will always take affect.
As of pulling/pushing occupants, it is working on diffs.

Here is more information on who can do which operation: http://quickblox.com/developers/Chat#Update_dialog

**Comment by nissivm** [comment]
And for custom parameters (my case), I imagine is the same rule for chat name and photo fields right (newest change prevails)?

**Comment by Raikerian** [comment]
Custom parameters of QBChatDialog are part of Custom objects and respect all custom objects rules.

**Comment by nissivm** [comment]
Ok, and which are the rules for custom objects (Regarding changes/updates)? Newest change always prevails?
