### ISSUE TITLE
Semantic Issue

### ISSUE THREAD

**Issue by josefrm** [QuickBlox/q-municate-services-ios#292]
![captura de pantalla 2016-12-06 a la s 21 45 50](https://cloud.githubusercontent.com/assets/10215739/20954051/83cf7d10-bbfd-11e6-8e30-db5922e3b267.png)

![captura de pantalla 2016-12-06 a la s 21 47 34](https://cloud.githubusercontent.com/assets/10215739/20954061/92f9c192-bbfd-11e6-9b27-6bf865b09611.png)

Any Idea??

**Comment by Raikerian** [comment]
Hi,

Data property to QBChatAttachment was added in 2.7.4. I see that your pods are using 2.7.6. But, check if framework search paths are not looking into an older version of Quickblox.

If that doesn't help and you recently updated Quickblox framework version, try to clean derived data before compile.

Let me know if that helps.

**Comment by ghost** [comment]
@josefrm, Any updates?

**Comment by josefrm** [comment]
Negative, @VitaliyGuru what I did was undo changes on my github project, then fix POD references & paths, but i'm afraid when executing an update/upgrade wont work, but i can work with the project atm, then i'll figure out about that.

keep in touch, best regards.

**Comment by ghost** [comment]
@josefrm,  Have you resolved this issue?
