### ISSUE TITLE
Unable to login using QMServices Manager. Client Error 422

### ISSUE THREAD

**Issue by unoiatech** [QuickBlox/q-municate-services-ios#293]

**Comment by Raikerian** [comment]
Hi,

Please provide full logs.

**Comment by unoiatech** [comment]
Thanks for your response. I was able to solve this issue. But I am getting another issue while retrieving user profile. In sample provided by QuickBlox, there's a method 

`QBUUser *recipient = [[ServicesManager instance].usersService.usersMemoryStorage userWithID:chatDialog.recipientID];`

I am using this in same way as sample. but it returns recipient null. Please help me on this.

**Comment by ghost** [comment]
@unoiatech This means that there is no user with given ID(chatDialog.recipientID) in memory storage. You should retrieve this user using the method below:

```objective-c
    [[[QMServicesManager instance].usersService getUserWithID:chatDialog.recipientID forceLoad:YES] continueWithBlock:^id _Nullable(BFTask<QBUUser *> * _Nonnull t) {
        //
        //
        QBUUser *user = t.result;
        //
        return nil;
    }];
```

**Comment by ghost** [comment]
@unoiatech , Any updates?

**Comment by unoiatech** [comment]
Thank you. First I have to retrieve user with this method. Then they get added to the cache. Next time i was able to retrieve from cache.

**Comment by ghost** [comment]
@unoiatech, Can i close the issue?

**Comment by unoiatech** [comment]
I have a question. When does the cache gets cleared ? I am facing an issue with messages cache. Sometimes I am not able to retrieve message history from cache.

**Comment by ghost** [comment]
@unoiatech, Please create a separate issue. 
Closed as resolved.
