### ISSUE TITLE
Segmentation fault error when using `continue` method on a task on swift 3

### ISSUE THREAD

**Issue by singhnitesh** [QuickBlox/q-municate-services-ios#295]
Hi,

Whenever I try to call `continue(successBlock:` or `continue` methods on a task (eg login user with authService) I get "Command failed due to signal: Segmentation fault: 11" error. Any advice?

**Environment details**
*iOS version : 10.1, Quickblox iOS SDK version: 2.9, QMServices version: 0.4.5*

**Comment by ghost** [comment]
Hi @singhnitesh   check code bellow:

```swift
ServicesManager.instance().authService.login(with: currentUser).continue({ (task) -> Any? in
    return nil;
})
```

<img width="1367" alt="screen" src="https://cloud.githubusercontent.com/assets/1109916/21923649/ee50af2c-d97d-11e6-8946-5df9f1f03cec.png">

or provide your code snippet for reproduce this issue in our side

**Comment by singhnitesh** [comment]
Hi @Pro100Andrey, following is my scenario :

- ChatServices class contains signup, login, autologin methods
![screen shot 2017-01-13 at 2 50 32 pm](https://cloud.githubusercontent.com/assets/1753710/21924788/9682d964-d9a0-11e6-858d-e8bfb87f3c5d.png)
- The services are called from the login view controller
![screen shot 2017-01-13 at 2 52 32 pm](https://cloud.githubusercontent.com/assets/1753710/21924789/96909c02-d9a0-11e6-8bfb-bfbe248afc15.png)
- Segmentation fault logs
![screen shot 2017-01-13 at 2 53 19 pm](https://cloud.githubusercontent.com/assets/1753710/21924791/970028a6-d9a0-11e6-977b-49eb5d9bb2c6.png)

Can you also point me to the above project source, maybe I can download & compile and see for my self?

Thanks

**Comment by singhnitesh** [comment]
I think I've got the problem, I was using `continue({ (task) -> Void` instead of `continue({ (task) -> Any?`. Though my signup request is timing out, but I'll explore that and raise separate issue if needed.

It would be great if you could point me to that swift sample in any case.
Thanks
