### ISSUE TITLE
Problem with private url link

### ISSUE THREAD

**Issue by phiren** [QuickBlox/q-municate-services-ios#301]
Uploaded file with private option and send it as attachment, yesterday it is working, today it stoped playing video, when tried open link in browser, it gives below error
{"errors":{"base":["Required session does not exist"]}}

The url is : https://api.quickblox.com/blobs/14dad7a45be94f92af7020588dfc5afd00.json?token=060c5aab6b5e9eb6a66441d2511329b60200bb9b

**Comment by ghost** [comment]
@phiren, Hello. The private link consists of blob id and token. The token is taken from QBSession.
The session can expire and generate a new token. So this link will be broken. 

1. You should save link without the token.

```objective-c
//Saving link 
 - (NSURL *)remoteURLWithString:(NSString *)stringURL {
    NSURLComponents *components = [NSURLComponents componentsWithString:stringURL];
    components.queryItems = nil;
    return components.URL;
}
```
2. Then you can get correct link by using the method below:

```objective-c
//getting link
- (NSURL *)remoteURL {
    NSURL *savedURL = //saved url without token
    NSURLComponents *components = [NSURLComponents componentsWithURL:savedURL
                                             resolvingAgainstBaseURL:false];
    
    components.query = [NSString stringWithFormat:@"token=%@",[QBSession currentSession].sessionDetails.token];
    return components.URL;
}
```
