### ISSUE TITLE
How to keep message history of particular time period?

### ISSUE THREAD

**Issue by DeepakMaheshwari05** [QuickBlox/q-municate-services-ios#309]
Hi, I am creating a chat application in which I have to give the option for keep message history with some options like for 7 days or for 1 month.
So anybody helps me how I will achieve that. I have not found any API's which will delete messages according to time stamp

**Comment by ghost** [comment]
@DeepakMaheshwari05,
Hello. 
There is no such API. This behavior should be implemented by yourself.

Use the method below to remove messages on the server.

```obj-c
/**
 Delete existent chat messages completely for all users
 @param messageIDs The IDs of messages to delete.
 @param forAllUsers Delete message for the current user or remove it for all users.
 @param successBlock Block with response instance if the request succeeded.
 @param errorBlock Block with response instance if the request failed.
 
 @discussion Passing YES to 'forAllUsers' requires current user to be the owner of the message! If the current user is not the owner - request fails.
 
 @return An instance of QBRequest for cancel operation mainly.
 */
+ (QBRequest *)deleteMessagesWithIDs:(NSSet<NSString *> *)messageIDs
                         forAllUsers:(BOOL)forAllUsers
                        successBlock:(nullable void(^)(QBResponse *response))successBlock
                          errorBlock:(nullable QBRequestErrorBlock)errorBlock;
```

**Comment by DeepakMaheshwari05** [comment]
@VitaliyGuru 
Will this method delete all the messages regarding messageIDs?

**Comment by ghost** [comment]
@DeepakMaheshwari05, Yes. I've added documentation to my answer.

**Comment by DeepakMaheshwari05** [comment]
Ok.
I will work on it.

**Comment by DeepakMaheshwari05** [comment]
@VitaliyGuru 

By using the above method and passing all dialogs Id, it was giving an error.
The log of error is


```
 Some : Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: not found (404)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x17022a1a0> { URL: https://api.quickblox.com/chat/Message/58f06b0fa0eb4770dd000011,58e63978a0eb47383b000011,58f06dafa28f9ac2a600001e,58f8a5e8a28f9af1f2000001,58f0b527a0eb4765c5000001,58f06db2a28f9a7361000002.json } { status code: 404, headers {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 40;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Tue, 25 Apr 2017 12:07:05 GMT";
    "QB-Token-ExpirationDate" = "2017-04-25 14:05:44 +0000";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "openresty/1.9.15.1";
    Status = "404 Not Found";
    "X-Rack-Cache" = "invalidate, pass";
    "X-Request-Id" = 1915b75972b98ec4da58a9eab92aa6b3;
    "X-Runtime" = "0.027975";
    "X-UA-Compatible" = "IE=Edge,chrome=1";
} }, NSErrorFailingURLKey=https://api.quickblox.com/chat/Message/58f06b0fa0eb4770dd000011,58e63978a0eb47383b000011,58f06dafa28f9ac2a600001e,58f8a5e8a28f9af1f2000001,58f0b527a0eb4765c5000001,58f06db2a28f9a7361000002.json, NSLocalizedRecoverySuggestion={"errors":["The resource wasn't found"]}, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a5b22 54686520 7265736f 75726365 20776173 6e277420 666f756e 64225d7d>, NSLocalizedDescription=Request failed: not found (404)}
```

The code for deleting message was
 
```
let extendedRequest = ["sort_desc" : "_id"]
        
        let page = QBResponsePage()
        
        QBRequest.dialogsForPage(page, extendedRequest: extendedRequest, successBlock: { (response: QBResponse, dialogs: [QBChatDialog]?, dialogsUsersIDs: Set<NSNumber>?, page: QBResponsePage?)  in
            if dialogs?.count > 0 {
                for dialog in dialogs! {
                    self.arrDialogIdsArray.addObject(dialog.ID!)
                }
                print(self.arrDialogIdsArray)
                if arrDialogIdsArray.count > 0 {
        var dialogIdsSet = Set<String>()
            for id in arrDialogIdsArray {
                dialogIdsSet.insert(id as! String)
            }
        
        QBRequest.deleteMessagesWithIDs(dialogIdsSet, forAllUsers: false, successBlock: { (response: QBResponse!) -> Void in
            kAppdelegate.stopHud()
            kAppdelegate.showAlertViewMethod(Tmessage, message: "All Messages Deleted successfully.")
        }) { (response: QBResponse!) -> Void in
            kAppdelegate.stopHud()
            print(response.error)
            kAppdelegate.showToast((response.error?.debugDescription)!)
        }
        }
            }
            
        }) { (response: QBResponse)  in
            kAppdelegate.stopHud()
            if response.status.rawValue == 422 {
                kAppdelegate.loginWithDasboard()
                kAppdelegate.showToast("Try again later.")
            }
            else {
            print(response.error)
            kAppdelegate.showToast((response.error?.debugDescription)!)
        }
        }
        
```
 
If am i doing something wrong?

**Comment by DeepakMaheshwari05** [comment]
@VitaliyGuru 
Have you got a chance for looking at this?

**Comment by ghost** [comment]
@DeepakMaheshwari05, Why do you put dialogsIDs, when the method needs messagesIDs?

**Comment by DeepakMaheshwari05** [comment]
@VitaliyGuru 
So, How I get the messages ids of all users?

**Comment by DeepakMaheshwari05** [comment]
Any Updates????

**Comment by DeepakMaheshwari05** [comment]
@VitaliyGuru 
Please help on this, its urgent.

**Comment by ghost** [comment]
@DeepakMaheshwari05, 

You can use the following approach:

 QBChatDialog instance has the property named [`data`](https://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters).

```obj-c
/**
 *  The dictionary with custom data.
 *
 *  @see https://quickblox.com/developers/SimpleSample-chat_users-ios#Custom_parameters
 */
@property (nonatomic, copy, nullable) NSDictionary<NSString *, id> *data;
```

You should use the additional schema for this property. This is a [QBCOCustomObject  class](https://quickblox.com/developers/Custom_Objects#Create_data_schema).

 IDs of sent messages can be stored as the field of this custom object. (Array of strings).

**Comment by EugeneHordieiev** [comment]
For QuickBlox enterprise customers we provide an option to enable custom retention policy.
Moving to an enterprise plan (with a dedicated server) will allow to request a certain time period for messages to be stored on the server.
Feel free to contact me directly (eugene.hordieiev@quickblox.com) for any additional questions

**Comment by DeepakMaheshwari05** [comment]
@VitaliyGuru 
On API calling, I get response status 422 most of the time

**Comment by ghost** [comment]
@DeepakMaheshwari05, 
Please provide logs.

**Comment by DeepakMaheshwari05** [comment]
Here is the log : 

> 2017-05-03 16:59:33.919992 NudgeBuddies[902:286641] [DYMTLInitPlatform] platform initialization successful
> newStatusBarFrame (0.0, 0.0, 0.0, 20.0)
> oldStatusBarFrame (0.0, 0.0, 0.0, 0.0)
> 2017-05-03 16:59:35.182497 NudgeBuddies[902:286526] [Crashlytics] Version 3.8.4 (121)
> 2017-05-03 16:59:35.338678 NudgeBuddies[902:286526] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
> 2017-05-03 16:59:35.341351 NudgeBuddies[902:286526] [MC] Reading from public effective user settings.
> 2017-05-03 16:59:35.440 rtc::[RTCClient] iPhone9,3, 10.1.1, SDK: 2.4, webrtc: 16262
> 2017-05-03 16:59:35.486 rtc::[RTCClient] Initializing SSL...
> 2017-05-03 16:59:35.487 rtc::[RTCClient] Wating signaling channel
> Bundle launchData.plist file is --> Optional("{\n    123456789 =     {\n        EmailAddress = \"advantala@gmail.com\";\n        ImageBlobId = 0;\n        IsAutoLogging = 0;\n        IsFirstLogin = 0;\n        IsRememberMe = 0;\n        LoginType = LoginNormal;\n        Name = Advantal;\n        Password = qwerty12345;\n        UserId = 123;\n        UserObjectData = <>;\n        Username = Advantal;\n    };\n}")
> copy
> Block Says Unreachable
> Block Says Reachable
> 2017-05-03 16:59:36.511762 NudgeBuddies[902:286708] [QBCore] Request URL:https://api.quickblox.com/account_settings.json
> 2017-05-03 16:59:36.511868 NudgeBuddies[902:286708] [QBCore] Request method: GET
> 2017-05-03 16:59:36.511937 NudgeBuddies[902:286708] [QBCore] Request parameters:(null)
> 2017-05-03 16:59:36.512003 NudgeBuddies[902:286708] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "QB-Account-Key" = Jwf3LjW3k7vhqNzX6Vhq;
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> My token is:-  021604b46615bffefbef061862de33942d6bae22a3a40d164ce0016e7c9b79d8
> 2017-05-03 16:59:36.778697 NudgeBuddies[902:286625] [QBCore] Request URL:https://api.quickblox.com/account_settings.json
> 2017-05-03 16:59:36.778852 NudgeBuddies[902:286625] [QBCore] Request method: GET
> 2017-05-03 16:59:36.778985 NudgeBuddies[902:286625] [QBCore] Request parameters:(null)
> 2017-05-03 16:59:36.779118 NudgeBuddies[902:286625] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "QB-Account-Key" = Jwf3LjW3k7vhqNzX6Vhq;
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> 2017-05-03 16:59:37.639249 NudgeBuddies[902:286625] [QBCore] Response headers: {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "max-age=0, private, must-revalidate";
>     Connection = "keep-alive";
>     "Content-Length" = 175;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:29:37 GMT";
>     Etag = "\"dc95c0a604da3772a4420356762fee2c\"";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "200 OK";
>     "Strict-Transport-Security" = "max-age=15768000;";
>     "X-Rack-Cache" = miss;
>     "X-Request-Id" = 3ae7a4281de72fd1d7af7c75e831a7a2;
>     "X-Runtime" = "0.007072";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> }
> 2017-05-03 16:59:37.639722 NudgeBuddies[902:286625] [QBCore] Response object: {
>     "account_id" = 40243;
>     "api_endpoint" = "https://api.quickblox.com";
>     "chat_endpoint" = "chat.quickblox.com";
>     "s3_bucket_name" = qbprod;
>     "turnserver_endpoint" = "turnserver.quickblox.com";
> }
> 2017-05-03 16:59:37.652392 NudgeBuddies[902:286711] [Core] accountSettings: 
>  apiEndpoint: https://api.quickblox.com
>  chatEndpoint: chat.quickblox.com, 
>  turnServerEndpoint: turnserver.quickblox.com, 
>  S3BucketName: qbprod, 
>  lastCheckDate: 2017-05-03 11:29:37 +0000
> 2017-05-03 16:59:37.658418 NudgeBuddies[902:286711] [QBCore] Request URL:https://api.quickblox.com/session.json
> 2017-05-03 16:59:37.658637 NudgeBuddies[902:286711] [QBCore] Request method: POST
> 2017-05-03 16:59:37.658836 NudgeBuddies[902:286711] [QBCore] Request parameters:{
>     "application_id" = 31721;
>     "auth_key" = SduskRsPsq7tmg3;
>     nonce = 573;
>     signature = bffb90b112feb64e15139f4a88e5527dcfdc1f18;
>     timestamp = 1493810977;
> }
> 2017-05-03 16:59:37.659036 NudgeBuddies[902:286711] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "Content-Type" = "application/x-www-form-urlencoded";
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> 2017-05-03 16:59:38.072834 NudgeBuddies[902:286675] [QBCore] Response headers: {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "max-age=0, private, must-revalidate";
>     Connection = "keep-alive";
>     "Content-Length" = 175;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:29:37 GMT";
>     Etag = "\"dc95c0a604da3772a4420356762fee2c\"";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "200 OK";
>     "Strict-Transport-Security" = "max-age=15768000;";
>     "X-Rack-Cache" = miss;
>     "X-Request-Id" = 48a06425071e30d12feaf81fe8166138;
>     "X-Runtime" = "0.004943";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> }
> 2017-05-03 16:59:38.075320 NudgeBuddies[902:286675] [QBCore] Response object: {
>     "account_id" = 40243;
>     "api_endpoint" = "https://api.quickblox.com";
>     "chat_endpoint" = "chat.quickblox.com";
>     "s3_bucket_name" = qbprod;
>     "turnserver_endpoint" = "turnserver.quickblox.com";
> }
> 2017-05-03 16:59:38.079641 NudgeBuddies[902:286675] [Core] accountSettings: 
>  apiEndpoint: https://api.quickblox.com
>  chatEndpoint: chat.quickblox.com, 
>  turnServerEndpoint: turnserver.quickblox.com, 
>  S3BucketName: qbprod, 
>  lastCheckDate: 2017-05-03 11:29:38 +0000
> 2017-05-03 16:59:38.084549 NudgeBuddies[902:286674] [QBCore] Request URL:https://api.quickblox.com/session.json
> 2017-05-03 16:59:38.084946 NudgeBuddies[902:286674] [QBCore] Request method: POST
> 2017-05-03 16:59:38.085751 NudgeBuddies[902:286674] [QBCore] Request parameters:{
>     "application_id" = 31721;
>     "auth_key" = SduskRsPsq7tmg3;
>     nonce = 429;
>     signature = cae2bc8a21155c0c70b6d85d6a4a918897ba0a14;
>     timestamp = 1493810978;
> }
> 2017-05-03 16:59:38.086162 NudgeBuddies[902:286674] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "Content-Type" = "application/x-www-form-urlencoded";
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> 2017-05-03 16:59:38.679129 NudgeBuddies[902:286711] [QBCore] Response headers: {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "max-age=0, private, must-revalidate";
>     Connection = "keep-alive";
>     "Content-Length" = 230;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:29:38 GMT";
>     Etag = "\"872798621b96b4e2fc84566239ad06a0\"";
>     "QB-Token-ExpirationDate" = "2017-05-03 13:29:38 UTC";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "201 Created";
>     "Strict-Transport-Security" = "max-age=15768000;";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = d913e26b0c2f86ef0902cf3ed8c3ea72;
>     "X-Runtime" = "0.047835";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> }
> 2017-05-03 16:59:38.691167 NudgeBuddies[902:286711] [QBCore] Response object: {
>     session =     {
>         "_id" = 92857526;
>         "application_id" = 31721;
>         "created_at" = "2017-05-03T11:29:38Z";
>         id = 92857526;
>         nonce = 573;
>         token = dde8c5f17e2b6594db218f9500630631f8007be9;
>         ts = 1493810977;
>         "updated_at" = "2017-05-03T11:29:38Z";
>         "user_id" = 0;
>     };
> }
> 2017-05-03 16:59:38.721909 NudgeBuddies[902:286711] [QBCore] Request URL:https://api.quickblox.com/subscriptions.json
> 2017-05-03 16:59:38.722326 NudgeBuddies[902:286711] [QBCore] Request method: POST
> 2017-05-03 16:59:38.722855 NudgeBuddies[902:286711] [QBCore] Request parameters:{
>     device =     {
>         platform = ios;
>         udid = "57A5C618-3FE0-4793-BA3B-63635E6CB151";
>     };
>     "notification_channels" = apns;
>     "push_token" =     {
>         "bundle_identifier" = "com.distribution.nudgebuddies";
>         "client_identification_sequence" = 08e773fadcde4318a9370efdd4c96dd6fdf598a72b87095c411ac15170e44ee1;
>         environment = development;
>     };
> }
> 2017-05-03 16:59:38.723281 NudgeBuddies[902:286711] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "Content-Type" = "application/x-www-form-urlencoded";
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QB-Token" = dde8c5f17e2b6594db218f9500630631f8007be9;
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> $$$$$$$$$$$$$$$ Error In Push subscription ------ $$$$$$$$$$$$$$$ [QBRespons2017-05-03 16:59:38.969370 NudgeBuddies[902:286711] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x1700361e0> { URL: https://api.quickblox.com/subscriptions.json } { status code: 422, headers {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "no-cache";
>     Connection = "keep-alive";
>     "Content-Length" = 45;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:29:38 GMT";
>     "QB-Token-ExpirationDate" = "2017-05-03 13:29:38 +0000";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "422 Unprocessable Entity";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = 41bde30c26c9e7b59185a9b91036079e;
>     "X-Runtime" = "0.007891";
>     "X-UA-Compatible" = "IE=Edge,ce]hrome=1";
> } }, NSErrorFailingURLKey=https://api.quickblox.com/subscriptions.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 466f7262 69646465 6e2e204e 65656420 75736572 2e225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}
> , status: 422
> 2017-05-03 16:59:38.971918 NudgeBuddies[902:286711] [QBCore] Response error reasons: {
>     errors =     {
>         base =         (
>             "Forbidden. Need user."
>         );
>     };
> }
> 2017-05-03 16:59:39.078736 NudgeBuddies[902:286651] [QBCore] Response headers: {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "max-age=0, private, must-revalidate";
>     Connection = "keep-alive";
>     "Content-Length" = 230;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:29:38 GMT";
>     Etag = "\"d46a1b22c7af0fab351e32bede722f19\"";
>     "QB-Token-ExpirationDate" = "2017-05-03 13:29:38 UTC";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "201 Created";
>     "Strict-Transport-Security" = "max-age=15768000;";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = 7c8bfcb421cb6d5cccffe5b048e702dd;
>     "X-Runtime" = "0.014533";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> }
> 2017-05-03 16:59:39.082355 NudgeBuddies[902:286651] [QBCore] Response object: {
>     session =     {
>         "_id" = 92857541;
>         "application_id" = 31721;
>         "created_at" = "2017-05-03T11:29:38Z";
>         id = 92857541;
>         nonce = 429;
>         token = 485db662cb06076fdf975657fd636687af007be9;
>         ts = 1493810978;
>         "updated_at" = "2017-05-03T11:29:38Z";
>         "user_id" = 0;
>     };
> }
> 2017-05-03 16:59:39.117971 NudgeBuddies[902:286651] [QBCore] Request URL:https://api.quickblox.com/subscriptions.json
> 2017-05-03 16:59:39.118528 NudgeBuddies[902:286651] [QBCore] Request method: POST
> 2017-05-03 16:59:39.118895 NudgeBuddies[902:286651] [QBCore] Request parameters:{
>     device =     {
>         platform = ios;
>         udid = "57A5C618-3FE0-4793-BA3B-63635E6CB151";
>     };
>     "notification_channels" = apns;
>     "push_token" =     {
>         "bundle_identifier" = "com.distribution.nudgebuddies";
>         "client_identification_sequence" = 021604b46615bffefbef061862de33942d6bae22a3a40d164ce0016e7c9b79d8;
>         environment = development;
>     };
> }
> 2017-05-03 16:59:39.119276 NudgeBuddies[902:286651] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "Content-Type" = "application/x-www-form-urlencoded";
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QB-Token" = 485db662cb06076fdf975657fd636687af007be9;
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> $$$$$$$$$$$$$$$ Error In Push subscription ------ $$$$$$$$$$$$$$$ [QBResponse], status: 422
> 2017-05-03 16:59:39.380952 NudgeBuddies[902:286652] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x170035700> { URL: https://api.quickblox.com/subscriptions.json } { status code: 422, headers {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "no-cache";
>     Connection = "keep-alive";
>     "Content-Length" = 45;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:29:39 GMT";
>     "QB-Token-ExpirationDate" = "2017-05-03 13:29:38 +0000";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "422 Unprocessable Entity";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = 1207b6118311c67c3832c1fd9c721bd3;
>     "X-Runtime" = "0.008209";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> } }, NSErrorFailingURLKey=https://api.quickblox.com/subscriptions.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 466f7262 69646465 6e2e204e 65656420 75736572 2e225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}
> 2017-05-03 16:59:39.382711 NudgeBuddies[902:286652] [QBCore] Response error reasons: {
>     errors =     {
>         base =         (
>             "Forbidden. Need user."
>         );
>     };
> }
> Access is granted2017-05-03 17:00:05.590209 NudgeBuddies[902:286848] [QBCore] Request URL:https://api.quickblox.com/subscriptions.json
> 2017-05-03 17:00:05.590301 NudgeBuddies[902:286848] [QBCore] Request method: POST
> 2017-05-03 17:00:05.590641 NudgeBuddies[902:286848] [QBCore] Request parameters:{
>     device =     {
>         platform = ios;
>         udid = "57A5C618-3FE0-4793-BA3B-63635E6CB151";
>     };
>     "notification_channels" = apns;
>     "push_token" =     {
>         "bundle_identifier" = "com.distribution.nudgebuddies";
>         "client_identification_sequence" = 08e773fadcde4318a9370efdd4c96dd6fdf598a72b87095c411ac15170e44ee1;
>         environment = development;
>     };
> }
> 2017-05-03 17:00:05.590747 NudgeBuddies[902:286848] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "Content-Type" = "application/x-www-form-urlencoded";
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QB-Token" = 485db662cb06076fdf975657fd636687af007be9;
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> My token is:-  021604b46615bffefbef061862de33942d6bae22a3a40d164ce0016e7c9b79d8
> 2017-05-03 17:00:05.598134 NudgeBuddies[902:286848] [QBCore] Request URL:https://api.quickblox.com/subscriptions.json
> 2017-05-03 17:00:05.598203 NudgeBuddies[902:286848] [QBCore] Request method: POST
> 2017-05-03 17:00:05.598248 NudgeBuddies[902:286848] [QBCore] Request parameters:{
>     device =     {
>         platform = ios;
>         udid = "57A5C618-3FE0-4793-BA3B-63635E6CB151";
>     };
>     "notification_channels" = apns;
>     "push_token" =     {
>         "bundle_identifier" = "com.distribution.nudgebuddies";
>         "client_identification_sequence" = 021604b46615bffefbef061862de33942d6bae22a3a40d164ce0016e7c9b79d8;
>         environment = development;
>     };
> }
> 2017-05-03 17:00:05.598296 NudgeBuddies[902:286848] [QBCore] Request headers: {
>     "Accept-Language" = "en-IN;q=1";
>     "Content-Type" = "application/x-www-form-urlencoded";
>     "QB-OS" = "iOS 10.1.1";
>     "QB-SDK" = "iOS 2.9.2";
>     "QB-Token" = 485db662cb06076fdf975657fd636687af007be9;
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     "User-Agent" = "NudgeBuddies/1.0 (iPhone; iOS 10.1.1; Scale/2.00)";
> }
> $$$$$$$$$$$$$$$ Error In Push subscription ------ $$$2017-05-03 17:00:05.869638 NudgeBuddies[902:286652] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x170039c00> { URL: https://api.quickblox.com/subscriptions.json } { status code: 422, headers {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "no-cache";
>     Connection = "keep-alive";
>     "Content-Length" = 45;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:30:05 GMT";
>     "QB-Token-ExpirationDate" = "2017-05-03 13:29:38 +0000";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "422 Unprocessable Entity";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = 4155516d8dff4993f86f3dcff9688da5;
>     "X-Runtime" = "0.023708";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> } }, NSError$$$$$$$$$$$$ [QBResponse], status: 422
> $$$$$$$$$$$$$$$ Error In Push subscription ------ $$$$$$$$$$$$$$$ [QBRespoFailingURLKey=https://api.quickblox.com/subscriptions.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 466f7262 69646465 6e2e204e 65656420 75736572 2e225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}
> nse], status: 422
> 2017-05-03 17:00:05.872062 NudgeBuddies[902:286652] [QBCore] Response error reasons: {
>     errors =     {
>         base =         (
>             "Forbidden. Need user."
>         );
>     };
> }
> 2017-05-03 17:00:05.872842 NudgeBuddies[902:286652] [QBCore] Response error: Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: client error (422)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x174037580> { URL: https://api.quickblox.com/subscriptions.json } { status code: 422, headers {
>     "Access-Control-Allow-Origin" = "*";
>     "Cache-Control" = "no-cache";
>     Connection = "keep-alive";
>     "Content-Length" = 45;
>     "Content-Type" = "application/json; charset=utf-8";
>     Date = "Wed, 03 May 2017 11:30:05 GMT";
>     "QB-Token-ExpirationDate" = "2017-05-03 13:29:38 +0000";
>     "QuickBlox-REST-API-Version" = "0.1.1";
>     Server = "openresty/1.9.15.1";
>     Status = "422 Unprocessable Entity";
>     "X-Rack-Cache" = "invalidate, pass";
>     "X-Request-Id" = 7a255ab9df6e970be2a76f83407fa1de;
>     "X-Runtime" = "0.010225";
>     "X-UA-Compatible" = "IE=Edge,chrome=1";
> } }, NSErrorFailingURLKey=https://api.quickblox.com/subscriptions.json, com.alamofire.serialization.response.error.data=<7b226572 726f7273 223a7b22 62617365 223a5b22 466f7262 69646465 6e2e204e 65656420 75736572 2e225d7d 7d>, NSLocalizedDescription=Request failed: client error (422)}
> 2017-05-03 17:00:05.873130 NudgeBuddies[902:286652] [QBCore] Response error reasons: {
>     errors =     {
>         base =         (
>             "Forbidden. Need user."
>         );
>     };
> }
>

**Comment by ghost** [comment]
@DeepakMaheshwari05, 
Your logs are not related to the main issue "How to keep message history of particular time period?".
Please create a separate issue and attach these logs.
