### ISSUE TITLE
+setAutoCreateSessionEnabled from QBConnection does not exist anymore 

### ISSUE THREAD

**Issue by MKOshel** [QuickBlox/q-municate-services-ios#31]
I have installed Quickblox version 2.4.3 I can't find this method so my question is: Before sign up or login  should I create a session ? I always get 401,  "Required session does not exist".

It says in the docs that sessions are managed automatically...

**Comment by Raikerian** [comment]
Hi,

In the latest versions SDK creates and manages the session automatically, so you dont have to set up anything.
If you are still recieving any errors regarding session creation please provide us more details on it.

**Comment by MKOshel** [comment]
Hi , thanks for answering
