### ISSUE TITLE
Online\Offline status

### ISSUE THREAD

**Issue by DeepakMaheshwari05** [QuickBlox/q-municate-services-ios#312]
Hi, I have to check user is online or offline.Currently, I am using this method to determine if user online or offline now. 

`QBUUser *user = ...;
` 
`NSInteger currentTimeInterval = [[NSDate date] timeIntervalSince1970];
``NSInteger userLastRequestAtTimeInterval   = [[user lastRequestAt] timeIntervalSince1970];
` 

` // if user didn't do anything last 1 minute (60 seconds)    
``if((currentTimeInterval - userLastRequestAtTimeInterval) > 60){ 
`   
`  // user is offline now
``}`

But this work only for one time
If, I have to call this repeatedly in some time interval for continuous presence of a user.

**Comment by DeepakMaheshwari05** [comment]
Any solution for these??

**Comment by ghost** [comment]
@DeepakMaheshwari05, Maybe [contact list](https://quickblox.com/developers/SimpleSample-chat_users-ios#Contact_list) will suit your needs?
You can get the time of the last activity associated with a contact list item.

**Comment by DeepakMaheshwari05** [comment]
Thanks, It's Working now.
