### ISSUE TITLE
EXC_BAD_ACCESS in QM_createEntityWithDescription: inContext:

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#322]
**Environment details**
Currently inspectableon IOS 10.2,
- QMServices (0.4.5):
    - Bolts (>= 1.5.0)
    - QuickBlox (>= 2.6.5)
  - QuickBlox (2.9.2)

**Did this work before?**
YES

**Expected behavior**
Not to have Crash 

**Actual behavior**
Crash

**Logs**
We opened a ticket #47222 and I added my logs (Not sure if I opened it under correct Department).
I prefer not to attach any logs here as it expose too much.

**Steps to reproduce the behavior**
It happened sometimes currently to one user (which have pretty much dialogs around 100 I think)

**Any others comments?**
![screen shot 2017-07-30 at 5 59 55 pm](https://user-images.githubusercontent.com/11506268/28754660-357099ec-7552-11e7-836f-644533835e97.png)

**Comment by mikeRozen** [comment]
Any updates?

**Comment by ghost** [comment]
Fixed in QMServices v.5.0.
