### ISSUE TITLE
Change Default Text for Chat Push Notification Send

### ISSUE THREAD

**Issue by AghaSyed** [QuickBlox/q-municate-services-ios#345]
Hi I have use my credentials in Q-municate app and test the app. Application runs perfectly just the way i want even it sends push perfectly but the problem is when i send a text message to other user it sends a push notification with title "You have 1 New messages". I have searched in Q-municate code that at which point you are setting this text so that i could change the Push text with the message content but there were no code in this application.
I own a enterprise account and check on the admin panel as well that may be you have provided an option there to choose message content in push notification.
I cannot use bellow method to send Push because i am not certain about the device type of other user.
// Send push to users with ids 292,300,1395 [QBRequest sendPush:pushMessage toUsers:@"292,300,1395" successBlock:^(QBResponse *response, QBMEvent *event) { // Successful response with event } errorBlock:^(QBError *error) { // Handle error }];

While i cannot use the simple text Push because i want to send some custom information with push as well.

**Comment by Raikerian** [comment]
Hi,

Take a look at this guide https://quickblox.com/developers/Chat/Push_notifications#Message_content_.28text.29
You can change this in your admin panel in Chat -> Alerts: http://take.ms/LsH72
