### ISSUE TITLE
User Authentication Problem

### ISSUE THREAD

**Issue by 9001118524** [QuickBlox/q-municate-services-ios#351]
When i was fill the e-mail Id and password then i clicked in verify button. I can't access the another page/Screen(welcome Screen) of the app. 
my log shows this:- 

POST URL:https://api.quickblox.com/session.json
headers: {
    "Accept-Language" = "en;q=1";
    "Content-Type" = "application/x-www-form-urlencoded";
    "QB-OS" = "iOS 10.3.1";
    "QB-SDK" = "iOS 2.12-int1";
    "QuickBlox-REST-API-Version" = "0.1.1";
    "User-Agent" = "Q-municate/2.6 (iPhone; iOS 10.3.1; Scale/3.00)";
}
parameters: {
    "application_id" = 65442;
    "auth_key" = hCaN;
    nonce = 895;
    signature = 42e1462b02649408a6009b3c37d;
    timestamp = 1511932275;
    "user[email]" = "anuraags@gmail.com";
    "user[password]" = 12345678;
}
2017-11-29 10:41:18.319 Q-municate[979:20975] [QBCore]: Response[1]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    Connection = "keep-alive";
    "Content-Length" = 27;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Wed, 29 Nov 2017 05:11:18 GMT";
    Duration = "2.918495";
    "QB-Token-ExpirationDate" = "2017-11-29 07:11:18 UTC";
    "QuickBlox-REST-API-Version" = "0.1.1";
    Server = "nginx/1.8.1";
    "Set-Cookie" = "_mkra_ctxt=777d9db784acb6959fe1ecf577464503--401; path=/; max-age=5; HttpOnly; secure";
    Status = "401 Unauthorized";
    "Strict-Transport-Security" = "max-age=31536000";
    "Www-Authenticate" = "OAuth realm=auth";
    "X-Content-Type-Options" = nosniff;
    "X-Frame-Options" = SAMEORIGIN;
    "X-Request-Id" = "e96f1d06-7690-4c60-bc69-e4b5c14e9c4c";
    "X-Runtime" = "0.037822";
    "X-XSS-Protection" = "1; mode=block";
}
error: Request failed: unauthorized (401)
reasons: {
    errors =     (
        Unauthorized
    );
}
2017-11-29 10:41:18.322 Q-municate[979:20975] [QBAuth]: Create Session request error: (null)
2017-11-29 10:41:18.340 Q-municate[979:20975] [QBCore]: Response[0]
error: Request failed: unauthorized (401)

**Comment by ghost** [comment]
@9001118524, you should have this user signed up in the application in order to perform the login.
