### ISSUE TITLE
USER LOGIN WITH PHONE NUMBER

### ISSUE THREAD

**Issue by 9001118524** [QuickBlox/q-municate-services-ios#352]
USer login with phone number is not working.when i clicked on verify button only alert occur with message "Something Went wrong. please try again."

**Comment by martyndix** [comment]
I'm having the same problem. Have you got a solution yet?

**Comment by ghost** [comment]
@9001118524 , @martyndix  you should perform login on the device because Firebase sends push notification to check and complete the login.
