### ISSUE TITLE
Make custom parameter keys consistent with android

### ISSUE THREAD

**Issue by jkmathew** [QuickBlox/q-municate-services-ios#356]
We have some issues with creating group dialogs across platforms.
Like, if group is created from android, it was not reflecting in iOS. From further investigation we could realize that in android and iOS using different keys from custom parameters for the system message after creating group.

See logs when receiving system message after creating group

Created From Android
```
[ChatService]: RCV: <message xmlns="jabber:client" type="headline" from="43679395-61386@chat.quickblox.com/android_ffffffff-fead-9764-c690-d6b934da3014" to="43678275-61386@chat.quickblox.com" id="5a97f79f154a8f8a030ccec9">
  <extraParams xmlns="jabber:client">
    <dialog_id>5a97f79fa0eb47308527cfeb</dialog_id>
    <dialog_type>2</dialog_type>
    <moduleIdentifier>SystemNotifications</moduleIdentifier>
    <dialog_name>ten</dialog_name>
    <notification_type>creating_dialog</notification_type>
    <occupants_ids>43678275,43678330,43678386,43679395</occupants_ids>
  </extraParams>
</message>
```

fCreated from rom iOS
```
[ChatService]: RCV: <message xmlns="jabber:client" type="headline" from="43678330-61386@chat.quickblox.com/E161F4AB-E157-42D0-9C72-5BCC13B9280E" to="43678275-61386@chat.quickblox.com" id="5a97fe2a45ac9817430041b4">
  <body>jmathew انشأ مجموعة مع johny,telvin,ajinn</body>
  <extraParams xmlns="jabber:client">
    <moduleIdentifier>SystemNotifications</moduleIdentifier>
    <notification_type>1</notification_type>
    <dialog_id>5a97fe2aa0eb47394927d02a</dialog_id>
    <room_name>19</room_name>
    <room_updated_date>1519910442</room_updated_date>
    <type>2</type>
    <current_occupant_ids>43678275,43678330,43678386,43679395</current_occupant_ids>
    <date_sent>1519910442</date_sent>
  </extraParams>
</message>
```

### Differences

Parameter      |in android        |in IOS    |
------------- | ------------- | ------------- |
value for notification_type            |creating_dialog   |1         | 
dialog type key  |dialog_type        |type            |

I could find inconsistency in the following codes.
https://github.com/QuickBlox/q-municate-services-ios/blob/3370000d584c46051077b99f81bf603bf8fe7682/QMChatService/QMChatService/Categories/QBChatMessage%2BQMCustomParameters.m#L34-L40
https://github.com/QuickBlox/quickblox-android-sdk/blob/69c6bae30daa550c9149abeebc825508c80ffb4f/sample-chat/src/main/java/com/quickblox/sample/chat/managers/DialogsManager.java#L26-L30

**Comment by ghost** [comment]
@jkmathew, Hello.
You are right. These keys are different. 
Mentioned parameters are custom, so it depends on you how they will be named. 
As for QMServices(iOS) they were initially designed for cross-platform application Q-municate and parameters are taken from our internal cross-platform specification.
 
As for Android, please take a look at [these parameters](https://github.com/QuickBlox/q-municate-android/blob/a6d60557110c1eb91e7b8ab105dc08d2d0d52934/Q-municate_core/src/main/java/com/quickblox/q_municate_core/models/NotificationType.java#L3-L3) and [this class](https://github.com/QuickBlox/q-municate-android/blob/4ccddbbd85ac6aff7d5fddc9ada060a39598c0a2/Q-municate_core/src/main/java/com/quickblox/q_municate_core/utils/ChatNotificationUtils.java#L158-L158).

There are no inconsistencies in these parameters in Q-municate application either in Android, iOS or JS platforms.

**Comment by jkmathew** [comment]
Okay, Thank you for your clarification
