### ISSUE TITLE
loadEarlierMessages returning zero messages

### ISSUE THREAD

**Issue by ziad-neo** [QuickBlox/q-municate-services-ios#357]
**Environment details**
*iOS version, Quickblox iOS SDK version, QMServices version*

**Did this work before?**
I am not sure

**Expected behavior**
I expect to return history messages

**Actual behavior**
it is returning zero messages

**Logs**
*Attach full logs that will describe your problem (please, use github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
1- Close app
2- Receive new message notification
3- open the app
4- open the dialog chat and see only the new messages without the history chat

**Any others comments?**

**Comment by MuheethMA** [comment]
@ziad-neo Did you solve this issue ? I am facing the same issue as well.

**Comment by ziad007** [comment]
@MuheethMA 
no i repost another issue about it https://github.com/QuickBlox/q-municate-services-ios/issues/358
