### ISSUE TITLE
earlierMessagesWithChatDialogID returning zero messages

### ISSUE THREAD

**Issue by ziad007** [QuickBlox/q-municate-services-ios#358]
Environment details
iOS version, Quickblox iOS SDK version, QMServices version

Did this work before?
I am not sure

Expected behavior
I expect to return history messages

Actual behavior
it is returning zero messages

Logs
Attach full logs that will describe your problem (please, use github gist)

Steps to reproduce the behavior
1- Close app
2- Receive new message notification
3- open the app
4- open the dialog chat and see only the new messages without the history chat

Any others comments?

**Comment by ghost** [comment]
@ziad007, Hello. Could you please provide full logs?
