### ISSUE TITLE
Quickblox does not send all notifications

### ISSUE THREAD

**Issue by unoiatech** [QuickBlox/q-municate-services-ios#363]
**Environment details**
*10.3.3, Latest one*

**Did this work before?**
No

**Expected behavior**
If user1 is offline and user2 sends 15 messages, It should send 15 push notifications to user1. 

**Actual behavior**
When user continuously sends messages to offline user, It does not send notification for all messages.It should send notifications for all the messages.

**Steps to reproduce the behavior**
Try sending messages continuously to Offline user

**Comment by ghost** [comment]
Hi @unoiatech 

[From Apple Guides:](https://developer.apple.com/library/content/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG23)

**Some Notifications Received, but Not All**

> If you are sending multiple notifications to the same device or computer within a short period of time, the push service will send only the last one.
> 
> Here's why. The device or computer acknowledges receipt of each notification. Until the push service receives that acknowledgment, it can only assume that the device or computer has gone off-line for some reason and stores the notification in the quality of service (QoS) queue for future redelivery. The round-trip network latency here is of course a major factor.
> 
> As described in the Local and Remote Notification Programming Guide, the QoS queue holds a single notification per app per device or computer. If the service receives another notification before the one in the queue is sent, the new notification overwrites the previous one.
> 
> If your notification payload contains the content-available key, your app will receive the notification if iOS or OS X determines it is energy-efficient to do so. If the energy or data budget for the device has been exceeded, your app will not receive any more notifications with the content-available key until the budget has been reset. This occurs once a day and cannot be changed by user or developer action. This throttle is disabled if the app is run from Xcode, so be sure to test your app by running it from the device to have the same user experience your customers will have.
> 
> All of this points out that the intent is that a notification indicates to an app that something of interest has changed on the provider, and the app should check in with the provider to get the details. Notifications should not contain data which isn't also available elsewhere, and they should also not be stateful.
> 
> Any push notification that isn't delivered immediately was queued for future redelivery because your device was not connected to the service. "Immediately" of course needs to take latency for your connection into account. Outlying cases would be beyond 60 seconds as APNs will time out at that point.

**Comment by unoiatech** [comment]
Thanks @pro100andrey
