### ISSUE TITLE
 Type arguments cannot be applied to non-parameterized class 'BFTask'

### ISSUE THREAD

**Issue by mikeRozen** [QuickBlox/q-municate-services-ios#60]
When I try to inherit from   _QMServicesManager_ as suggested I always receive the following Error
**Type arguments cannot be applied to non-parameterized class BFTask**
It may be related to the same problem :[ link ](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/297) 
Did you encounter the same problem in Xcode 7.

**Comment by Raikerian** [comment]
Hi,

Have you tried to follow the steps in the linked issue?

**Comment by mikeRozen** [comment]
Hi,
Sorry It was totally my fault I messed up old Facebook framework with CocaoPods.
