### ISSUE TITLE
 'parse issue:expected a type'

### ISSUE THREAD

**Issue by Smartebucks** [QuickBlox/q-municate-services-ios#62]
![xqwad](https://cloud.githubusercontent.com/assets/13176641/11262520/246092a4-8ea6-11e5-8fd9-f892083748eb.png)

 I am new to Quickblox,I need to integrate with my Application,I have an issue with QMServiceDeployment.
Steps Followed:
 i)Creating a Xcode Project
 ii)Created a Cocoapods
 pod 'QMServices'
iii)After successfully created the pods and opened my xcode workspace,It shows me 'parse issue:expected a type'
Can you please give me an idea/redirect me to solve my issue.

 Thanks,
 Shangari c.

**Comment by Raikerian** [comment]
Hi,

Seems like you are using Xcode 6 instead of 7, thats why it can't understand generics. You need to update your Xcode.

**Comment by Raikerian** [comment]
We will fix this issue for Xcode 6 in the next version.

**Comment by Raikerian** [comment]
Fixed in 0.3.2.
