### ISSUE TITLE
[Question] QMChatService fetch messages issue

### ISSUE THREAD

**Issue by buithuyen** [QuickBlox/q-municate-services-ios#66]
Hi Quickblox team,

I'm facing problem when I try fetch message from GroupDialog.

``` objective-c
    // Retrieving message from Quickblox REST history and cache.
    [[ServicesManager instance].chatService messagesWithChatDialogID:self.dialog.ID completion:^(QBResponse* response, NSArray* messages) {
        if (response.success) {
            if (showingProgress && !self.isSendingAttachment) {
                [SVProgressHUD dismiss];
            }
        } else {
            [SVProgressHUD showErrorWithStatus:@"Can not refresh messages"];
            NSLog(@"can not refresh messages: %@", response.error.error);
        }
    }];
```

Could you guys let me know my mistake.
Thank you in advance.

<img width="1884" alt="screen shot 2015-11-27 at 6 19 08 pm" src="https://cloud.githubusercontent.com/assets/5087522/11440430/f2c14cf8-9534-11e5-9f3a-227fa89d0f50.png">

**Comment by Raikerian** [comment]
Hi,

According to your crash you are trying to insert nil as dialog into cache. This happens after you call 'readMessages:forDialogID:' method, where you are marking message as read and updating dialog by ID in your cache. So, dialog with that ID that you sent there wasn't found for some reason in memory storage. Double check that your dialogID is correct one.

**Comment by LetstrackApp** [comment]
I'm also facing same issue when we try to read messages. 
This is how we read messages:

` func readMessages(messages : [QBChatMessage]){
        DKChatServices.instance().chatService.read(messages, forDialogID: friend?.dialoId ?? "", completion: { (error) in
            if error == nil{
                print("Messages Read")
            }
            else{
                print("Unable to readf message")
            }
        })
    }`

And This is how we fetch dialog:

` func getDialoges(completion: @escaping ([DKChatDialog]?, Set<NSNumber>?, [[String : Any]]?, String?)->Void){
        
        if let lastActivityDate = DKChatServices.instance().lastActivityDate {
            DKChatServices.instance().chatService.fetchDialogsUpdated(from: lastActivityDate as Date, andPageLimit: 500, iterationBlock: { (response, dialogObjects, dialogsUsersIDs, stop) -> Void in
                
                if dialogObjects?.count ?? 0 > 0{
                    let newDialogs = getNewDialogs(dialogObjects ?? [])
                    completion(newDialogs,dialogsUsersIDs,[],nil)
                }
                else{
                    completion([],[],[],nil)
                }
                
            }, completionBlock: { (response) -> Void in
                if (response.isSuccess) {
                    DKChatServices.instance().lastActivityDate = NSDate()
                }
                else{
                    completion(nil,nil,nil,response.error?.description)
                }
            })
        }
        else {
            DKChatServices.instance().chatService.allDialogs(withPageLimit: kDialogsPageLimit, extendedRequest: nil, iterationBlock: { (response: QBResponse?, dialogObjects: [QBChatDialog]?, dialogsUsersIDS: Set<NSNumber>?, stop: UnsafeMutablePointer<ObjCBool>) -> Void in
                
                if dialogObjects?.count ?? 0 > 0{
                    let newDialogs = getNewDialogs(dialogObjects ?? [])
                    completion(newDialogs,dialogsUsersIDS,[],nil)
                }
                else{
                    completion([],[],[],nil)
                }
                
            }, completion: { (response: QBResponse?) -> Void in
                
                guard response != nil && response!.isSuccess else {
                    completion(nil,nil,nil,response?.error?.description)
                    return
                }
                DKChatServices.instance().lastActivityDate = NSDate()
                
            })
        }'
![Screenshot 2019-07-21 at 4 39 22 PM](https://user-images.githubusercontent.com/49427636/61590492-e6340d00-abd7-11e9-9fe4-501904d33800.png)


I'm unable to find out why our dialog is not available in local memory.
