### ISSUE TITLE
Not able to get QMChatCacheModel.bundle, QMContactListCacheModel.bundle..

### ISSUE THREAD

**Issue by jpatel956** [QuickBlox/q-municate-services-ios#67]
Hi

I have followed your steps to produce "QMContactListCacheModel.bundle", "QMUsersCacheModel.bundle" and  "QMChatCacheModel.bundle". but still color is in red. so can you please help me to sort out this issue. it is most preferable if you provide direct link to download that bundles.

Thanks
Jatin Patel

**Comment by Raikerian** [comment]
Hi,

Try to build bundles by yourself. Open QMServices.xcodeproj, in schemes select QMChatCacheModel and build it, after that build QMContactListCacheModel and QMUsersCacheModel in a same way. You should be able to find bundles in each cache folder after that.
