### ISSUE TITLE
Pod version issue

### ISSUE THREAD

**Issue by dhavaldev** [QuickBlox/q-municate-services-ios#73]
Hey I want to 0.3 version.

pod 'QMServices', '~> 0.3'

I wrote this but it's downloading 0.3.2. That is giving error in my code. Please help me how can I get this version.

**Comment by Raikerian** [comment]
Hi,

Which error are you getting? Please post them here so we can help to migrate your code for the newest methods that were updated. Some old deprecated methods were deleted in the latest QMServices version.

**Comment by AndreyMoskvin** [comment]
@dhavaldev To download 0.3 version:

pod 'QMServices', '0.3'
