### ISSUE TITLE
Update Bolts to 1.5.0

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#87]
I'm trying to integrate QuickBlox with my project but when using version 0.3.3, it conflict with Facebook SDK because Facebook using Bolts 1.5.0.
Please update Bolts framework to 1.5.0

**Comment by Raikerian** [comment]
Hi!

Thank you for reporting the issue, we will update Bolts for the enxt release.
Latest Facebook iOS SDK (4.8.0) is working with Bolts 1.3.0 fine, so you shoudn't have any problems. Can you please attach error log of conflict?
Also make sure you don't have 'Bolts' pod in your podfile.

**Comment by tranngoclinh88** [comment]
I'm using Facebook iOS SDK and your framework in Pod file.
I removed Facebook iOS SDK and keep your framework but it still can not install version 0.3.3

Here is the result:

Using QMChatViewController (0.3.2)
Installing QMServices 0.3.3 (was 0.3.2)

[!] Error installing QMServices
[!] /Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/y8/540lbgjx4g14nrcc91qm5st40000gn/T/d20151223-4091-lhakdd --single-branch --depth 1 --branch 0.3.3

Cloning into '/var/folders/y8/540lbgjx4g14nrcc91qm5st40000gn/T/d20151223-4091-lhakdd'...
Note: checking out '9f6a8c6d493520580a8ec0763edeb8f1abb050e0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by tranngoclinh88** [comment]
Still can not install version 0.3.3

**Comment by Raikerian** [comment]
Please show your podfile content

**Comment by tranngoclinh88** [comment]
Here is mine.

# Platform, Min OS Version

platform :ios, '7.0'
inhibit_all_warnings!

# Default Pods

pod 'FontAwesome', '~> 4.3'
pod 'IFVideoPicker', '~> 1.0'
pod 'IQKeyboardManager', '~> 3.3'
pod 'JSQMessagesViewController', '~> 7.2'
pod 'MGSwipeTableCell'
pod 'MTDates', '~> 1.0'
pod 'QuickBlox', '~> 2.6'
pod 'Quickblox-WebRTC', '~> 2.1'
pod 'QMChatViewController', '~> 0.3'
pod 'QMServices', '~> 0.3'
pod 'RKNotificationHub', '~> 2.0'
pod 'RMUniversalAlert', '~> 0.7'
pod 'SCRecorder', '~> 2.6'
pod 'SVProgressHUD', '2.0-beta'
pod 'TWMessageBarManager', '~> 1.8'
pod 'UIColor+Additions', '~> 2.0'

**Comment by Raikerian** [comment]
I was able to successfully install pods with your podfile.
Please, try the following:
1. Delete Podfile.lock (file)
2. Delete Pods (folder)
3. Delete .xcworkspace (file)
4. Run pod install

**Comment by tranngoclinh88** [comment]
Still can not install

Last login: Thu Dec 24 17:24:21 on ttys000
Linh-Trans-MacBook-Pro:QuickBloxChatting TranNgocLinh88$ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.3.0)
Installing Crashlytics (3.4.1)
Installing Fabric (1.6.1)
Installing FontAwesome (4.3.0)
Installing IFVideoPicker (1.0.3)
Installing IQKeyboardManager (3.3.4)
Installing JSQMessagesViewController (7.2.0)
Installing JSQSystemSoundPlayer (2.0.1)
Installing MGSwipeTableCell (1.5.3)
Installing MTDates (1.0.3)
Installing QMChatViewController (0.3.2)
Installing QMServices (0.3.3)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/y8/540lbgjx4g14nrcc91qm5st40000gn/T/d20151224-64731-1p4j5hi --single-branch --depth 1 --branch 0.3.3

Cloning into '/var/folders/y8/540lbgjx4g14nrcc91qm5st40000gn/T/d20151224-64731-1p4j5hi'...
Note: checking out '9f6a8c6d493520580a8ec0763edeb8f1abb050e0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

git-lfs smudge 'Frameworks/Bolts.framework/Versions/A/Bolts': git-lfs: command not found
error: external filter git-lfs smudge %f failed -1
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

![screen shot 2015-12-24 at 5 29 47 pm](https://cloud.githubusercontent.com/assets/1511264/11993488/0ea97492-aa64-11e5-8f0b-0f8101b1da87.png)

**Comment by Raikerian** [comment]
According to your error you need to install git-lfs.
Just run this command:

```
git lfs install
```

and try pod install again.

Here is more info about it: https://git-lfs.github.com

**Comment by Raikerian** [comment]
Any updates?

**Comment by tranngoclinh88** [comment]
Thank @Raikerian. Successful installing!

**Comment by mh-prophet** [comment]
Same issue with me and after following all steps i stuck with the solution,As "git lfs install" generate error that ---> git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
    log

**Comment by Raikerian** [comment]
Hi!

Please create separate issue for your problem.
To answer you now, please follow installation rules here: https://git-lfs.github.com

Also please don't forget to delete Podfile.lock, Pods folder and .xcworkspace file before next pod install.

**Comment by mh-prophet** [comment]
Yeah i did that,Deleted Podfile.lock and pods folder and after that trying to install QMServices again which leads me to following issue.
<img width="820" alt="screen shot 2015-12-27 at 8 08 56 pm" src="https://cloud.githubusercontent.com/assets/13645851/12010653/a92eaad2-acd5-11e5-8ac6-c8847951ee92.png">

**Comment by Raikerian** [comment]
Please follow installation rules here: https://git-lfs.github.com
You can download lfs there.

**Comment by mh-prophet** [comment]
Yeah, i did that and it is showing:
<img width="823" alt="screen shot 2015-12-27 at 8 12 07 pm" src="https://cloud.githubusercontent.com/assets/13645851/12010662/1a4ad808-acd6-11e5-933d-2948032be398.png">

**Comment by Raikerian** [comment]
It is basically telling you that you haven't install latest command line extension.
Have you downloaded zip file from the link?
Have you run install.sh script in terminal?

**Comment by mh-prophet** [comment]
yes i did that and here are the results:
<img width="570" alt="screen shot 2015-12-27 at 8 19 15 pm" src="https://cloud.githubusercontent.com/assets/13645851/12010689/306dc932-acd7-11e5-939b-c91df4de6f70.png">

**Comment by RivkiGlick** [comment]
hi 
I'm trying to integrate QuickBlox with my project but when I'm trying to Installing QMServices I get the next result:

hodayas-iMac:TryChat1 hodayaohana$ pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.3 is available.
To update use: gem install cocoapods --pre
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.0)
Installing QMServices (0.3.6)

[!] Error installing QMServices
[!] /usr/bin/git clone https://github.com/QuickBlox/q-municate-services-ios.git /var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg --single-branch --depth 1 --branch 0.3.6

Cloning into '/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg'...
Note: checking out 'a9db8f8f861153729936dac692c2fc71174ae50e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b

Downloading Frameworks/Bolts.framework/Versions/A/Bolts (940.64 KB)
Error downloading object: Frameworks/Bolts.framework/Versions/A/Bolts (238480d343f8e10def84cf56218ab6c54868dafc0e2c803ecdf989b1a2f2efb8)

Errors logged to /private/var/folders/31/gsb7b0615ps_1ds0ck44k3c40000gn/T/d20160216-22878-sgwomg/.git/lfs/objects/logs/20160216T140807.145508476.log
Use git lfs logs last to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: Frameworks/Bolts.framework/Versions/A/Bolts: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by tranngoclinh88** [comment]
It also happen with me with version 0.3.6
