### ISSUE TITLE
How to download a file not image from attachment message?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#89]
I tried to upload some video file and audio file through attachment service but I can not find any function to download them except this method:
- (void)getImageForAttachmentMessage:(QBChatMessage *)attachmentMessage completion:(void(^)(NSError *error, UIImage *image))completion {}

Please let me know how.

**Comment by Raikerian** [comment]
Hi,

Right now our attachment service supports only image attachments, but we will implement all media attachments in it soon.
For now if you want to achieve such functionality you need to modify '(void)getImageForAttachmentMessage' method to return any media file, or create your own methods for different attachments.

**Comment by tranngoclinh88** [comment]
@Raikerian 
I've tried to install service by using submodule follow your document but I stuck in here:

*\* NOTE**: By default, the Quickblox framework is set to ~/Documents/Quickblox. To change the path to Quickblox.framework, you need to open Quickblox.xcconfig file and replace ~/Documents/Quickblox with your path to the Quickblox.framework.

Can not find ~/Documents/Quickblox and don't know how to continue :(.
Please help me.
