### ISSUE TITLE
How can I remove/delete one member from group chat?

### ISSUE THREAD

**Issue by tranngoclinh88** [QuickBlox/q-municate-services-ios#92]
I look through your framework and not found any method to remove/delete one member in group chat.
Can you show me how to do that?

**Comment by Raikerian** [comment]
Hi,

Unfortunately this feature is not available yet. We will add it in the near future.

**Comment by Raikerian** [comment]
In order to receive updates about Quickblox new features, follow our [blog here](http://quickblox.com/blog/).

We are closing this thread for tracking purposes.
If you have any other questions please create separate issue.
