### ISSUE TITLE
Can't integrate as pod to swift project with use_frameworks!

### ISSUE THREAD

**Issue by yakubbaev** [QuickBlox/q-municate-services-ios#98]
My pod:

```
use_frameworks!
pod 'QMServices'
```

Error:

> MyApp target has transitive dependencies that include static binaries:
> (path_to_project/Pods/QuickBlox/Quickblox.framework)

**Comment by yakubbaev** [comment]
Disabling this check

```
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end
```

produces linker error
![Image of error](http://i.imgur.com/9uEN7dP.png)

**Comment by yakubbaev** [comment]
Forgot to mention, my pod file has

```
use_frameworks!
```

If add this to your <code>sample_chat_swift</code> demo, error reproduces.

**Comment by Raikerian** [comment]
Hi,

Check this issue with answers: https://github.com/QuickBlox/QMChatViewController-ios/issues/5

**Comment by yakubbaev** [comment]
So, short answer is that Quickblox can't be integrated as pod with `use_frameworks!`?

**Comment by Raikerian** [comment]
For now - yes.

**Comment by yakubbaev** [comment]
Then how should I integrate? Tried second approach in your docs - with subprojects - it doesn't work either. I've created issue for this - #100.

**Comment by Raikerian** [comment]
We will investigate issue with manual installation as soon as possible.
